### ISSUE TITLE
Total amount changes

### ISSUE THREAD

**Issue by sew0ns** [Blair2004/NexoPOS-4x#100]
he demo shop NexoPOS, I met the same error as me. The total amount of the order is $ 5450, but in the end, in the list of orders and in the dashboard, it shows $ 5, instead of$5450

**Comment by sew0ns** [comment]
![1](https://user-images.githubusercontent.com/15718165/102450736-2b1bd780-4048-11eb-8d77-7938dcf99119.png)
![2](https://user-images.githubusercontent.com/15718165/102450742-2c4d0480-4048-11eb-9fbb-a1566561e4bf.png)
![3](https://user-images.githubusercontent.com/15718165/102450744-2ce59b00-4048-11eb-8acc-975423af4941.png)

**Comment by Blair2004** [comment]
Thank you i'm checking.

**Comment by Cyaaaaaaaaan** [comment]
This happens when the product's **stock management** is set to **no**, btw.

**Comment by sew0ns** [comment]
> This happens when the product's **stock management** is set to **no**, btw.

Where to set it up? I can't find product management.

**Comment by sew0ns** [comment]
> stock management

I chose "no" in stock management, nothing has changed, the total amount remains $ 1,$5

**Comment by Cyaaaaaaaaan** [comment]
> > This happens when the product's **stock management** is set to **no**, btw.
> 
> Where to set it up? I can't find product management.

try setting it to yes by editing the product and then adjust the stock to your likings.

**Comment by sew0ns** [comment]
> > > This happens when the product's **stock management** is set to **no**, btw.
> > 
> > 
> > Where to set it up? I can't find product management.
> 
> try setting it to yes by editing the product and then adjust the stock to your likings.

It doesn't help. The total amount is $ 2 instead of$ 2500.

**Comment by sew0ns** [comment]
@Blair2004 
![940F38A2-ADC3-4D4B-9D5A-2E7CF880ED50](https://user-images.githubusercontent.com/15718165/102521282-900e1680-40b6-11eb-9fec-12bb0df3f0f4.jpeg)
![C6052DC3-161C-4EFC-9B77-CB065D940FC9](https://user-images.githubusercontent.com/15718165/102521296-94d2ca80-40b6-11eb-9179-5a4238cfe322.jpeg)
![859A89D6-4073-4130-9C1C-856BD324AED3](https://user-images.githubusercontent.com/15718165/102521301-9603f780-40b6-11eb-9a15-b232b73a8a37.jpeg)
![D6203F9A-313C-4C64-BECA-A76B2C5DBCFA](https://user-images.githubusercontent.com/15718165/102521305-969c8e00-40b6-11eb-9dd3-52fe1605728d.jpeg)

**Comment by Blair2004** [comment]
Hi, please check if the latest commit fixed that issue : https://github.com/Blair2004/NexoPOS-4x/commit/d208d97585590d02fb8db45f717ec9e3d9163b3a

**Comment by sew0ns** [comment]
> Hi, please check if the latest commit fixed that issue : [d208d97](https://github.com/Blair2004/NexoPOS-4x/commit/d208d97585590d02fb8db45f717ec9e3d9163b3a)

Problem fixed. Thank you.
