### ISSUE TITLE
Dashboard's report summary showing wrong "net income" computation.

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#101]
![image](https://user-images.githubusercontent.com/16180446/102527752-8bf2f080-40d8-11eb-90b4-b08f9e8ae8bd.png)

**Comment by Blair2004** [comment]
can you provide a screenshot of the annual report ?
![image](https://user-images.githubusercontent.com/5265663/102553848-d0c05c80-40c3-11eb-85fe-f95fd27a1906.png)

**Comment by Cyaaaaaaaaan** [comment]
Here's my annual report.
![image](https://user-images.githubusercontent.com/16180446/102559194-3a635980-410a-11eb-9530-ae2e3684287e.png)

Net Income's still messed up

**Comment by Blair2004** [comment]
Based on what I see, you dont have any expenses therefore the value of the income looks correct. What is the expected behavior according to you.

**Comment by Cyaaaaaaaaan** [comment]
Weekly sales shows the right value but not for Net Income and Expenses. They're both multiplied by 10.
![image](https://user-images.githubusercontent.com/16180446/102718935-f0ef5600-4325-11eb-9d34-702033e517c6.png)

**Comment by Blair2004** [comment]
I'll test.

**Comment by Blair2004** [comment]
Not able to reproduce, can you share a concrete example of images that shows the sales (2 order max) the dashboard (actual on the issue), the report (cash flow). Please consider doing these tests on a fresh installation.

**Comment by Cyaaaaaaaaan** [comment]
> Not able to reproduce, can you share a concrete example of images that shows the sales (2 order max) the dashboard (actual on the issue), the report (cash flow). Please consider doing these tests on a fresh installation.

Alright let me do it real quick

**Comment by Blair2004** [comment]
With no proper tests and reproducing steps I'm unable to sort the issue. Please as soon as you have More information reopen the thread
