### ISSUE TITLE
NPS not Loaded while creating new kitchen screen

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#1010]
the first 4 photos are shown the configuration had been done and it is shown while selecting the customer printer but while creating new kitchen it is shown an error as shown in the last picture:
![issue1](https://user-images.githubusercontent.com/87772530/186582953-8b2973e3-d67e-420c-bd4a-3c3fc6986fdb.png)

![issue2](https://user-images.githubusercontent.com/87772530/186582963-7c5d91d6-fdde-4112-affe-826d515c19b8.png)

![issue3](https://user-images.githubusercontent.com/87772530/186583001-9bd368fe-7f60-4c6d-934d-eb27bdc265e0.png)
![issue4](https://user-images.githubusercontent.com/87772530/186583013-994c7394-aa95-4a6a-9f47-92cce71496ac.png)

![issue5](https://user-images.githubusercontent.com/87772530/186583021-21ccc5b0-0236-4f34-aab4-db874e261e33.png)

Gastro Module: 4.8.7
Pin Login: 4.7.2
NPS Adapter: 4.7.5
Pin Login: 4.7.2
My Nexo POS: 4.8.3

**Comment by magedfathi** [comment]
the same error is shown while creating new register but after adding the NPS url http://localhost:3236 all printers are shown
but in the case of creating new kitchen no way to add the NPS url manually from the new kitchen screen and the following screenshot is a proof that the NPS is correctly configured and the printers are shown for other screen

![issue6](https://user-images.githubusercontent.com/87772530/186638134-e720e1bf-ae25-437e-8e34-45e798e8f40e.png)

**Comment by nexopos** [comment]
Hi, 
What version of NexoPOS are you usign ?

**Comment by magedfathi** [comment]
4.8.3

**Comment by Blair2004** [comment]
Hi, we need direct access to your setup (through AnyDesk preferably). 
Reach support on WhatsApp : +1 (424) 231-4091

**Comment by magedfathi** [comment]
Noted with thanks

**Comment by Blair2004** [comment]
closed for inactivity.
