### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#1013]
sometime while i am using the NexoPOS if i am idle for 2-3 minutes and wen to products or modifiers i get the following screen shoot and i have to refresh the browser then it works fine.
kindly advice for that

![issue12](https://user-images.githubusercontent.com/87772530/186659368-dbfd27bb-40e1-4e73-9b42-3c05011cb129.png)

Gastro Module: 4.8.7
Pin Login: 4.7.2
NPS Adapter: 4.7.5
My Nexo POS: 4.8.3

**Comment by Blair2004** [comment]
Are you using the built-in server (php artisan serve) ?

**Comment by magedfathi** [comment]
No,

**Comment by Blair2004** [comment]
This error seems specific to XAMPP. NexoPOS comes with bundled assets, so there is no reason to have the assets missing.
Alternatively, we'll recommend you switching to WSL or Laragon which offer a better envrionment for NexoPOS
