### ISSUE TITLE
Product status hidden feature is not working

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#1015]
while changing the product status to hidden, we expect not to be shown on pos but this is not happening in my local system and your production system

Also i need clarification, the hidden means the product will not be active and cant be sold or only hidden on POS and we can reach it with searching. i am asking this cause some products i am assigning to modifier group i dont need to be shown on POS 

 Gastro Module: 4.8.7
Pin Login: 4.7.2
NPS Adapter: 4.7.5
My Nexo POS: 4.8.3

**Comment by Blair2004** [comment]
Hi,
The status hidden should make the product not available for sale, but it can be sold as a modifier.

**Comment by magedfathi** [comment]
thanks for your confirmation and this is what i need can be sold as a modifier
