### ISSUE TITLE
Different report values

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#1018]
Really i dont know is there something wrong with my installation or it is from the system
i had done some sales on 25-8-2022
so kindly check the reports i got different values for each one, kindly check the following screenshots

![report issue1](https://user-images.githubusercontent.com/87772530/186784067-c8422fcc-2ce4-43b4-9815-94ef9f45d1c1.png)

![report issue2](https://user-images.githubusercontent.com/87772530/186783104-7ad8f958-537d-44f4-acfc-6faca8b239a3.png)

![report issue3](https://user-images.githubusercontent.com/87772530/186783122-e0735aee-7a43-4876-9a39-70ad43d17c48.png)

 Gastro Module: 4.8.7
Pin Login: 4.7.2
NPS Adapter: 4.7.5
My Nexo POS: 4.8.3

**Comment by Blair2004** [comment]
Hi, have you noticed (last screenshot), the report sems to be for 2022-08-26 ?

**Comment by magedfathi** [comment]
no this is the date i print the report.
you can check the following screen shoot

![issue13](https://user-images.githubusercontent.com/87772530/186976831-47117acf-fb2c-4410-b3ff-b0d04e0ede80.png)

**Comment by Blair2004** [comment]
Hi, Can you please share your databse at contact@nexopos.com, we'll try to see that issue live with it.

**Comment by Blair2004** [comment]
Closed for inactivity.
