### ISSUE TITLE
Sales Filters are not shown sales after 23:55

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#1019]
Sales Filters are not shown sales after 23:55 and we cant change 23:55 to 23:59

kindly see the first screen shoot without applying the filters which shown i have 4 sales on 25-8-2022

and the second photo after applying the filter with date and time range as shown, only shown 3 sales

![reportissue1](https://user-images.githubusercontent.com/87772530/186785840-c0db0044-85cc-4246-9250-a105f154340c.png)

![reportissue2](https://user-images.githubusercontent.com/87772530/186785856-0c8e041c-510c-465a-b186-44862c82475d.png)

this is shown the date range i had applied

![report issue3](https://user-images.githubusercontent.com/87772530/186786001-ff377330-4704-4527-9e0e-5c4ee609cc8a.png)

this is shown the result after applying the filters

Gastro Module: 4.8.7
Pin Login: 4.7.2
NPS Adapter: 4.7.5
My Nexo POS: 4.8.3

**Comment by Blair2004** [comment]
Hi,
How about applying the next day at 00:00 ?

**Comment by magedfathi** [comment]
i will do and it will fix but from your side also u can change the today and yesterday tab parameters to be until 23:59 so it will be easy for us.
u can mark this ticket as closed 
thank you
