### ISSUE TITLE
Setting the preferred timezone doesn't do anything.

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#102]
![image](https://user-images.githubusercontent.com/16180446/102527893-c78dba80-40d8-11eb-904d-ac682e2288aa.png)

I tried setting the timezone to my preferred one but it's not doing anything. Created orders are still recorded in the default timezone which is Europe/London.

**Comment by Blair2004** [comment]
Another commit coming up to complete this previous one.

**Comment by Cyaaaaaaaaan** [comment]
Hi @Blair2004 , I'm getting this error after pulling the latest commit.

![image](https://user-images.githubusercontent.com/16180446/102561937-e8720200-4110-11eb-87d6-cbef40cab9a4.png)
