### ISSUE TITLE
[Issue] problem creating products

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#1020]
**Describe the bug**
When creating products or categories, they do not appear, only the first category created and the first product created appear

If I hide the category it continues to show

**To Reproduce**

1. create product and categories as normal

**Expected behavior**
That the products and categories created appear

**Screenshots**
![Captura de Pantalla 2022-08-27 a las 02 41 38](https://user-images.githubusercontent.com/80654041/187018941-2368b8b9-ed81-40f9-8b1e-2ae80cad33c2.png)
![Captura de Pantalla 2022-08-27 a las 02 41 17](https://user-images.githubusercontent.com/80654041/187018946-32645dd6-1442-4bfb-992f-405f82508985.png)

**Environment:**
 - NexoPOS 4.8.3
 - Premium Extensions: [Nexo Print Adapter (4.7.5), Gastro (4.8.7), MultiStore (4.8.2]

**Comment by Blair2004** [comment]
Hi,
If I get it right, if I create 2 category (with no parent) only the first category will be created ?

**Comment by ahorasoyfelipe** [comment]
yes, and if you create more products they no longer appear

**Comment by Blair2004** [comment]
Hi, my message is actually about categories. If you're talking about some products not appearing on the POS, you might consider reading this: https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-the-products-not-appearing-for-sale-on-nexopos-4-x

Let us know if that helped.

**Comment by ahorasoyfelipe** [comment]
I know how to create products, I create products and categories in the same way, this error goes from version 4.8.0 to 4.8.3 with multistore, Gastro and printer adapter

**Comment by ahorasoyfelipe** [comment]
the problem occurs when I am not using the subdomain mode in the multistore, if the subdomain mode is activated, the products and categories appear
![Captura de Pantalla 2022-08-30 a las 15 32 15](https://user-images.githubusercontent.com/80654041/187527855-9f2f98da-66b5-4d9a-9724-3bd38c54859c.png)

**Comment by Blair2004** [comment]
I'm intrigued, i would like to see that error in action. Reach out to me personnaly on WhatsApp (+237656988008)

**Comment by ahorasoyfelipe** [comment]
problem solved, uploading the modules manually via cpanel
