### ISSUE TITLE
Product Edit, New or Edit Procurement, POS Screen, Edit Catory all of thesee pages are  blank. 

### ISSUE THREAD

**Issue by UkinnovationTechs** [Blair2004/NexoPOS-4x#1021]
Product Edit, New or Edit Procurement, POS Screen, Edit Catory all of thesee pages are  blank.  And product images not shown. Our system dos not work until monday, after support team take actions for resolve "Product images Not Showing" issue by connecting our system. if you take a look to  mail traffic you will find all details and history, all actions taked by support team thanks them vey much but  i dont know what am i supposed to do. As support team told me, i am till waiting for response.  At least give me an information about last point. Acoourding to your response i will take tare oıf myself, I have to!

![EDİT PRODUCT](https://user-images.githubusercontent.com/107043880/187030584-c25492ab-9a35-4f07-9c8f-ccea86ac9176.png)
<img width="800" alt="mail" src="https://user-images.githubusercontent.com/107043880/187030585-3ede982e-a41a-4b82-b07e-b12a6b4d77cd.PNG">
![NEW PROCURMENT](https://user-images.githubusercontent.com/107043880/187030586-5cfc523e-90b0-4d62-951b-dc14849b18bd.png)
<img width="952" alt="POS" src="https://user-images.githubusercontent.com/107043880/187030588-10fa9e70-d879-4c5d-8703-1a88d05c37b4.PNG">

**Comment by Blair2004** [comment]
Hi,

The thread should be assigned to a developper from next Monday. We had many scheduled request and we'll make sure to handle most requests next week.

Kind Regards

**Comment by UkinnovationTechs** [comment]
This is not my request dude! Your support team did login our server to fix broken product image issue, since this point we do nothing even we dont try to login!!  and Our system was stop working. I told you before to check emails betwen your ssupport team and us. But it seems you did not, did you?

Now, what are yu talking about excatly? You made this, you broke down our working system my friend. 1 weeek!!!


what am i supposed to do know?  Are you making tradational spying?

**Comment by UkinnovationTechs** [comment]
?????

**Comment by Blair2004** [comment]
Hi, Any progress from the development team ?

**Comment by Blair2004** [comment]
Closed for inactivity
