### ISSUE TITLE
Setting a product's price value greater than 1000 would reset it to the first digit of entered value.

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#103]
I tried creating a product that has a sale price of 2000php and wholesale price of 2000php and after submitting the product, it would set it to the first digit of entered value which is 2. (Attached images for clarity)

1.
![image](https://user-images.githubusercontent.com/16180446/102530616-33bded80-40dc-11eb-97c1-9ea32f821b56.png)

2.
![image](https://user-images.githubusercontent.com/16180446/102530681-489a8100-40dc-11eb-864a-4ad2315468b6.png)

HeidiSQL Logs:
![image](https://user-images.githubusercontent.com/16180446/102530773-64058c00-40dc-11eb-8c80-21fc358e240e.png)

Setting the price manually throught HeidiSQL works tho.

**Comment by Blair2004** [comment]
fix https://github.com/Blair2004/NexoPOS-4x/commit/d208d97585590d02fb8db45f717ec9e3d9163b3a
