### ISSUE TITLE
[Issue] error when trying to update gastro 4.8.8

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#1032]
**Describe the bug**
error when trying to update gastro 4.8.8, this error happens with the module version 4.8.0, 4.8.7 and 4.8.8

**To Reproduce**
1. Go to Modules
2. Click on 'Upload'

**Expected behavior**
update gastro or install

**Screenshots**
![Captura de Pantalla 2022-08-31 a las 00 53 27](https://user-images.githubusercontent.com/80654041/187595827-d8ee2ab5-93fd-4acd-9582-b4e9317ac905.png)
![Captura de Pantalla 2022-08-31 a las 00 53 44](https://user-images.githubusercontent.com/80654041/187595839-dd792693-9f8d-44f4-98db-31195b49f01b.png)

**Environment:**
NexoPOS 4.x vesrion: [4.8.3]
Premium Extensions: [Nexo Print Adapter (4.7.5), Gastro (4.8.7), MultiStore (4.8.2]

**Comment by Blair2004** [comment]
Hi,
this usually occurs if your server doesn't allow uploading large file. Check your php configuration to allow uploading large files (you can set 10MB)

**Comment by ahorasoyfelipe** [comment]
yes, that was the problem, thank you very much
