### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by omkhan95** [Blair2004/NexoPOS-4x#1059]
Can you explain how I can add the searching function used in create new procurement to the create new products page?

**Comment by Blair2004** [comment]
Hi, 

Thank you for reaching out.
As this is your first issue we would like to inform you that all issue *must* be formatted the same way. Read this (#501) to understand how to create an issue.

However, we'll give a quick answer, for customizing script, well you need to know:

- Vue2
- Laravel

and you'll have to customize the crud table vue  component and recompile the script (compiling are familiar to vue developpers)

- resources/ts/components/ns-crud.vue

You'll need to create relevant route for your needs as an api route. For the rest your knowledge should be enough (familiar to Laravel developpers).

Hope this will help.

**Comment by omkhan95** [comment]
thanks a lot.
