### ISSUE TITLE
[Issue] The default customer is not selected in POS

### ISSUE THREAD

**Issue by karimQasem** [Blair2004/NexoPOS-4x#1070]
**Describe the bug**
The default customer is not selected in POS

**Screenshots**
![image](https://user-images.githubusercontent.com/44165344/191205577-33a1243c-5f60-4b01-9370-b17d1afac405.png)

**_**Default customer**_**

![image](https://user-images.githubusercontent.com/44165344/191206434-90ad6a00-6b9a-4fe4-9735-c831e6f8a87b.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.4

**Comment by Blair2004** [comment]
Hi,
Thank you for reaching out.
we'll review this.

**Comment by Blair2004** [comment]
Fix merged to branch v4.8.x.
Thank you @karimQasem
