### ISSUE TITLE
[Issue] Refund & return status not changed after refund all products

### ISSUE THREAD

**Issue by karimQasem** [Blair2004/NexoPOS-4x#1071]
**Describe the bug**
Refund & return status not changed after refund all products and the refund amount will not be deducted. 

**To Reproduce**
1. Make a order
2. Refund all products
3. See the tabs Refund & return not disappear
4. See in Dashboard Total Sales the amount will not be deducted after refund
5. See also in Sales Report 

**Screenshots**
after refund
![Refund 1](https://user-images.githubusercontent.com/44165344/191211735-de763116-da01-4e7f-9b76-8c01f605ad94.PNG)

tabs Refund & return not disappear
![Refunds 2](https://user-images.githubusercontent.com/44165344/191211326-47893121-bcb3-403d-96c0-1012de6e45ed.PNG)

 in Dashboard Total Sales the amount will not be deducted after refund
![Refunds 3](https://user-images.githubusercontent.com/44165344/191211435-eaa97918-252b-4380-8f59-d6bf807aae5f.PNG)

also in Sales Report 
![Refunds 4](https://user-images.githubusercontent.com/44165344/191211535-87d1810e-896a-42c6-b2ad-ec3ac17f9b1e.PNG)

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.4

**Comment by Blair2004** [comment]
Hi,
Thank you we'll review this.
