### ISSUE TITLE
[Issue] Cash register added the sale amount two times.

### ISSUE THREAD

**Issue by karimQasem** [Blair2004/NexoPOS-4x#1072]
**Describe the bug**
Cash register added amount of Sale twice, one for the sale amount and the other for amount payment.

**Expected behavior**
Include the sale amount only.

**Screenshots**

**_before submit payment_**
![cash 1](https://user-images.githubusercontent.com/44165344/191245401-9ac39192-b659-4b4b-9853-7664b1ff3805.PNG)

**_After submit payment_**
![cash 2](https://user-images.githubusercontent.com/44165344/191245620-6bdf55f9-4513-4820-8262-2e1a2655f9bc.PNG)

**Environment:**
 - NexoPOS 4.x vesrion: 4.8.4

**Comment by Blair2004** [comment]
Hi,
Thank you for reporting we're reviewing this.

**Comment by Blair2004** [comment]
This doesn't seems to be a but, but rather 2 payments submitted on the same order.

**Comment by karimQasem** [comment]
@Blair2004 But the customer paid **1000** I have to return **900** to him Why should I find **1100** in Cash register
And in another case i sell one product for 100 after click Full payment
![image](https://user-images.githubusercontent.com/44165344/193552060-d28b4e3d-50c1-4c68-a6f1-1d5c7a9dcbeb.png)
**I should only find 100 and not 200**
