### ISSUE TITLE
[Issue] Issue when Unit is deleted

### ISSUE THREAD

**Issue by yasirmturk** [Blair2004/NexoPOS-4x#1077]
**Describe the bug**
When Unit is deleted but it is attached to product and a procurement, then it results in an inconsistent state. 

**To Reproduce**
1. Create a product with unit and price
2. Create a procurement
3. Delete Unit
4. Now product is in deadlock and unit or price can not be updated nor the procurement could be deleted

**Expected behavior**
It should not be possible to delete the Unit 
It should be possible to delete the procurement when unit is already deleted 
It should be possible to change the unit or price on a product when previous unit is deleted and procurement is present

**Screenshots**
<img width="550" alt="procurement-error" src="https://user-images.githubusercontent.com/306691/191806437-7b0aad57-40f1-41d7-b368-41737d3291bc.png">

**Environment:**
 - NexoPOS 4.x vesrion: latest

**Comment by Blair2004** [comment]
Hi,
Thank you, we'll add a dependency mechanism to the units.

**Comment by Blair2004** [comment]
Implemented on https://github.com/Blair2004/NexoPOS-4x/commit/e18bdfa86506f815ca7c88ff2fa30b9b1123024c
