### ISSUE TITLE
[Issue] Unable to update Unit on Price

### ISSUE THREAD

**Issue by yasirmturk** [Blair2004/NexoPOS-4x#1078]
**Describe the bug**
When try to update Unit on price then it creates a duplicate instead of updating it

**To Reproduce**
1. Go to Product > Edit
2. Update Unit and save
3. Reload and there is new Unit price created with selected values

**Expected behavior**
It should be possible to change a Unit on a product

**Screenshots**
<img width="619" alt="Screenshot 2022-09-22 at 6 54 30 PM" src="https://user-images.githubusercontent.com/306691/191806829-e0731491-d97f-48c7-ba33-8158f99e4254.png">

**Environment:**
 - NexoPOS 4.x vesrion: latest

**Comment by Blair2004** [comment]
Hi,
This will checked. 

Thank you.

**Comment by Blair2004** [comment]
Hi, unfortunately this can't be reproduced. After the test we did.
Also "version: latest" is not a valid version.

Can you provide any insight that helps reproducing the issue ?

**Comment by yasirmturk** [comment]
I think this happens only when the original unit has been deleted, then you create another unit and try to set it in the product

**Comment by Blair2004** [comment]
that seems right. A unit shouldn't be deleted if it's assigned to a product. Thank you for that.

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/193540786-7f6e6096-a694-4aa3-88f3-6bd3ea81d8c0.png)
implemented
