### ISSUE TITLE
CSRF token mismatch.

### ISSUE THREAD

**Issue by iqbal1410** [Blair2004/NexoPOS-4x#108]
Hi, after installing following the documentation, i cannot login with the credential that i register. What is the step that i'm missing?
![Screen Shot 2020-12-20 at 10 43 48 PM](https://user-images.githubusercontent.com/12908469/102716197-38211b00-4315-11eb-9e9a-cf0af073b1fd.png)

My Env is : 
Laravel valet
php 7.4
mysql  Ver 8.0.22 for osx10.16 on x86_64 (Homebrew)

**Comment by Blair2004** [comment]
Hi, consider clearing the cookie and refresh the page. You might alternatively try incognito more or another browser.

**Comment by Blair2004** [comment]
A similar issue has already been solved here. That good provide further hints: https://github.com/Blair2004/NexoPOS-4x/issues/88

**Comment by iqbal1410** [comment]
> Hi, consider clearing the cookie and refresh the page. You might alternatively try incognito more or another browser.

Hi, issue resolved. i clear cookies and can login already. thank you
