### ISSUE TITLE
[Issue] Double Record Register Sales

### ISSUE THREAD

**Issue by dagracejr** [Blair2004/NexoPOS-4x#1100]
**Describe the bug**
Watch the video
**To Reproduce**
https://vimeo.com/758559059

**Expected behavior**
it should only record one sale

**Screenshots**
https://vimeo.com/758559059

**Environment:**
 - NexoPOS lastest

**Comment by Blair2004** [comment]
Hi, 
thank you for reporting.
We'll take a look.

**Comment by dagracejr** [comment]
Cool. Thanks!
