### ISSUE TITLE
disabled the discount ,, but still work in Checkout Popup 

### ISSUE THREAD

**Issue by TarekRamadan91** [Blair2004/NexoPOS-4x#1133]
when i disabled the discount by user role ,, user can make a discount from Checkout Popup !! , while the discount is disabled in pos 

![image](https://user-images.githubusercontent.com/88363088/198499564-5bec43c6-96de-4da9-a398-5e95e64d9a55.png)

**Comment by Blair2004** [comment]
Thank you, this will be checked

**Comment by Blair2004** [comment]
Thank you, we've appied the fix. It's coming on NexoPOS 4.8.7

![image](https://user-images.githubusercontent.com/5265663/198876247-a91f1c3e-83e7-421a-b59e-42df79461f9e.png)
