### ISSUE TITLE
HTTP ERROR 500 when deployed on the server

### ISSUE THREAD

**Issue by blackeaglehdc** [Blair2004/NexoPOS-4x#114]
The application works well in the local environment, after deploying it on the shared hosting platform 500 http error occurs.
1. Config, routes, caches are cleared before uploading the project.
2. .htaccess and .env files configured
3. browser cache cleared
 
how to overcome this issue and deploy on the shared hosting environment
![Screenshot 2020-12-24 18:16:32](https://user-images.githubusercontent.com/7894661/103089674-aff08d80-4614-11eb-8210-ed6654e98a9b.png)

**Comment by Blair2004** [comment]
HI,
Please consider checking "storage/logs/laravel.log and check the error returned by the server.

**Comment by Blair2004** [comment]
Hi, i'm awaiting update on this.

**Comment by Blair2004** [comment]
Closed for inactivity.
