### ISSUE TITLE
[Issue] error when updating to version 4.8.7

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#1156]
**Describe the bug**
can't upgrade to version 4.8.7

**Screenshots**
![Captura de pantalla 2022-11-02 a las 22 28 11](https://user-images.githubusercontent.com/80654041/199632317-1d162b75-9913-4aef-9e3b-6c47d540e210.png)

**Environment:**
 - NexoPOS 4.x versión: [e.g. 4.8.6]

**Comment by nexopos** [comment]
Hi,
If your have updated using MyNexoPOS or by overwriting files, some unecessary files remained and those files needs to be removed. on the databases/migrations folder, delete the highlighted folder & files.

![screenshot-nimbusweb me-2022 11 03-08_47_30](https://user-images.githubusercontent.com/40301137/199669761-bf51d871-8a3d-4e5e-bd9d-a2efc9f75cc3.png)

**Comment by Blair2004** [comment]
Closed for inactivity
