### ISSUE TITLE
[Issue] DateTime:: construct () : Argument #2 (Stimezone) must be of type ? DateTimeZone, bool given

### ISSUE THREAD

**Issue by Spyloop** [Blair2004/NexoPOS-4x#1160]
**Describe the bug**

I her this error after trying to update
![Uploading E1732B21-F159-4569-A844-60CECDC69573.jpeg…]()

**Comment by Blair2004** [comment]
Hi, 
Thank you for reporting your issue. Note that all issues *MUST* be formatted as recommeded here #501  for a better understanding by us.
