### ISSUE TITLE
CSRF token mispmatch

### ISSUE THREAD

**Issue by EricRibia** [Blair2004/NexoPOS-4x#125]
I locally installed nexopos 4 but on trying to do register or sign in it always says there is a csrf token mismatch.
What could be the problem?

**Comment by Blair2004** [comment]
Hi, this is possibily caused by the script editing the .env file which needs you to clear the cookies after the installation.

**Comment by Blair2004** [comment]
Any update ?

**Comment by EricRibia** [comment]
Hello,
Still getting an issue.
Please see below.

**Comment by Blair2004** [comment]
Hi, we've made some corrections to the app and we've updated the documentation. So there are some things that you need to check: 
- APP_URL and SESSION_DOMAIN is the same
- Check if SANCTUM_STATEFUL_DOMAINS is defined

**Comment by Blair2004** [comment]
Closed for inactivity.

**Comment by Seiteigr** [comment]
I have the same error, installed locally and checked 
APP_URL and SESSION_DOMAIN is the same
Check if SANCTUM_STATEFUL_DOMAINS is defined
all fine

**Comment by Blair2004** [comment]
APP_URL cannot be the same as SESSION_DOMAIN.. APP_URL for instance has leading "http://" while SESSION_DOMAIN + SANCTUM_STATEFUL_DOMAINS shouldn't have that leading protocol. Check that and make sure to clear your cookies.

**Comment by Ippezrobert** [comment]
I have also installed locally on windows 10 and having the same on login, the variables in .env are as below
APP_URL=http://127.0.0.1:8000
SESSION_DOMAIN=127.0.0.1:8000
SANCTUM_STATEFUL_DOMAINS=127.0.0.1:8000

Any help on how i can login?

**Comment by Blair2004** [comment]
Hi, @Ippezrobert  that's what you're looking for https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-csrf-token-mismatch-on-nexopos-4-x

**Comment by Ippezrobert** [comment]
I fixed it but now it say "Not authorized" to create anything not even settings/configuration

**Comment by Blair2004** [comment]
Please open a dedicated thread. Mention your environment details and a copy
of your .en file omiting sensitive information

**Comment by D3xter7** [comment]
@ippezshelby 
I am too late to respond, but I have fixed this error by adding a line in a migration where .env file is being updated.
database\migrations\core\2020_10_09_000928_define_sanctum_variables_oct9.php
       `$domain = Str::replaceFirst( 'http://', '', url( '/' ) );
        $domain = Str::replaceFirst( 'https://', '', $domain );
        $domain = Str::replaceFirst( ':8000', '', url( '/' ) ); // this line added.`
 Issue fixed
