### ISSUE TITLE
(again) CSFR Token Mismatch

### ISSUE THREAD

**Issue by pastitop** [Blair2004/NexoPOS-4x#128]
Trying to install nexoPOS on Windows 10 and keep throwing error: SQL42000 and CSFR Token Mismatch on 'Create Installation'. I decided to install nexoPOS on MacOS; Create Installation successfull, Database Migration; the updating button running all the time (the process shouldn\'t be stopped, however) but i have to refresh the page it since the updating proccess took hours and now i am stuck on login page with CSFR Token Mismatch; SANCTUM_STATEFUL_DOMAINS and SESSION_DOMAIN is automatically renew and same address with APP_URL

**Comment by Blair2004** [comment]
Hi, Can you share your .env file (make sure to hide sensitive information).

**Comment by pastitop** [comment]
<img width="1097" alt="Screenshot 2021-01-26 at 5 12 28 PM" src="https://user-images.githubusercontent.com/76028996/105824809-cf0a8280-5ff9-11eb-8e0f-23c0162e2155.png">
<img width="1099" alt="Screenshot 2021-01-26 at 5 12 40 PM" src="https://user-images.githubusercontent.com/76028996/105824825-d598fa00-5ff9-11eb-822b-171776fc3af5.png">

**Comment by Blair2004** [comment]
We'll try again and let you know.

**Comment by pastitop** [comment]
Thank you @Blair2004

**Comment by Blair2004** [comment]
On SANCTUM_STATEFUL_DOMAINS, remove the port 8000 
same for SESSION_DOMAIN

**Comment by pastitop** [comment]
alright DONE perfectly. Thx Dude!

**Comment by pastitop** [comment]
CSFR issue is vanished. i will close it. THX
