### ISSUE TITLE
user permission

### ISSUE THREAD

**Issue by duncanokeyo** [Blair2004/NexoPOS-4x#134]
is there an option for admin to create users and assign roles to the users, for example billers, workers etc.. and permissions can also be editted. also is there client interface where he can login and check the invoice etc?

**Comment by Blair2004** [comment]
Hi, 
yes, your administrator can create users, assign roles, and changes permissions.
No there is no login interface for customers.

**Comment by duncanokeyo** [comment]
any plan to add user login interface and ability to modify user information

**Comment by Blair2004** [comment]
That's not planned to be part of the core at the moment.
