### ISSUE TITLE
the expiry date is ignorad all the time 

### ISSUE THREAD

**Issue by compnew2006** [Blair2004/NexoPOS-4x#135]
in the demo version i have add an item and i have do buy product with expiry date but the pos always sell the expired product

**Comment by Blair2004** [comment]
Thank you for reporting We'll take a look. Please consider sharing the demo you've tested.
Regards.

**Comment by compnew2006** [comment]
here is the photo of the item with Product Expires option
![2021-02-07_LI](https://user-images.githubusercontent.com/51255434/107177372-b60db400-699f-11eb-8b66-e4c5dc754b71.jpg)


and the i have Make a new procurement
![2021-02-07 (1)](https://user-images.githubusercontent.com/51255434/107177419-cde53800-699f-11eb-89ad-8e2dad23f0cd.png)


here i have set the expiration date to 31/01/2021
![2021-02-07 (2)](https://user-images.githubusercontent.com/51255434/107177431-d8073680-699f-11eb-9c5c-80bae1424725.png)


and here the item can see in the POS module without red color 
![2021-02-07 (4)_LI](https://user-images.githubusercontent.com/51255434/107177490-f836f580-699f-11eb-9718-754fe50c7542.jpg)


and here i have sold the item without expiry date alert
![2021-02-07 (3)](https://user-images.githubusercontent.com/51255434/107177502-fd944000-699f-11eb-8331-b28a729ff056.png)

**Comment by watchdogs019** [comment]
This is still an issue in nexopos 4.8.7
