### ISSUE TITLE
duplicate Page

### ISSUE THREAD

**Issue by compnew2006** [Blair2004/NexoPOS-4x#136]
the Settings->Reports tab is showing the tab of Settings->Customers
![Opera Snapshot_2021-02-08_013725_localhost](https://user-images.githubusercontent.com/51255434/107184590-dc871b80-69ae-11eb-987c-7f7069d56dec.png)

**Comment by Blair2004** [comment]
Thanks for reporting. that will be sorted.

**Comment by Blair2004** [comment]
The issue has been fixed
