### ISSUE TITLE
Purchase Order Feature

### ISSUE THREAD

**Issue by ph4t0o0o0om** [Blair2004/NexoPOS-4x#147]
Hi sir good day, this is very awesome repo but I notice one thing, where is the Purchase Order feature? In POS I believe this one of the important feature . Thank you!

**Comment by Blair2004** [comment]
Hi, by purchase order, you mean "procurement" ?

**Comment by ph4t0o0o0om** [comment]
Yes procurement need to improve the features. and sir the ORDERING LEVEL I believe that is very good feature we are going to add a unique identifier on every product like MIN_QUANTITY  and if less than or equal , the system suggest that this item is on critical level and must replenish the maintaining quantity.

**Comment by ph4t0o0o0om** [comment]
Hi sir, @Blair2004 is it possible that we have a change currency feature? I'm looking to use this but the currency is PHILIPPINE PESO is it possible sir? thanks!!

**Comment by Blair2004** [comment]
Hi, 
the procurement is documented already : https://my.nexopos.com/en/documentation/components/procurements
Regarding the min_quantity level, we'll consider that.
For changing the currency it's possible from the general settings
![screenshot-nexopos-v4 std-2021 03 09-07_21_33](https://user-images.githubusercontent.com/5265663/110427511-29423d00-80a8-11eb-81a1-f3d262e7bc43.jpg)

**Comment by ph4t0o0o0om** [comment]
Hi sir @Blair2004  thank you for your reply. is the SETTINGS option is available on free version? I cannot see sir on your online demo. 

And last sir please see attached file of error on my installation on my local server please help me I really want this awesome software to use. 
<img width="948" alt="error nexo" src="https://user-images.githubusercontent.com/41504668/110429095-60830f00-80e5-11eb-92cc-07200d591ea6.PNG">

**Comment by ph4t0o0o0om** [comment]
Hi  I just fixed the issue. I run composer update and replace the APP_URL:localhost:800 to APP_URL:http://127.0.0.1 and the SESSION_DOMAIN=localhost:8000 to SESSION_DOMAIN=127.0.0.1 . Im going to explore the system now. many thanks!

**Comment by ph4t0o0o0om** [comment]
Hi sir @Blair2004 
<img width="960" alt="error nexo2" src="https://user-images.githubusercontent.com/41504668/110435313-d7240a80-80ed-11eb-8668-a9fd790d247a.PNG">
 I already installed the repo on my local server I successfully setup the db and I successfully login. But when I login it seems like the system is down? when I click anything on sidebar it keeps on loading the screen and says "Your not authenticated"

Please see pic for reference.

**Comment by Blair2004** [comment]
Can you past here the content of your .env file (excluding sensitive information)?

**Comment by ph4t0o0o0om** [comment]
Hi sir @Blair2004 this is the content of my .env file

APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:OJWbvDIRmE4FzHNiczh+mhq7UHTGVy4H+CpdiRnttH0=
APP_DEBUG=true
APP_URL=http://127.0.0.1

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos_v4
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=localhost:8000
DB_PREFIX=ns_
NS_VERSION=4.0

**Comment by ph4t0o0o0om** [comment]
Hi, sir @Blair2004 what is the possible fix on this issue? Please help

**Comment by Blair2004** [comment]
assuming your domain is = http://example.com
adjust your value as follows : 

SANCTUM_STATEFUL_DOMAINS=example.com
SESSION_DOMAIN=example.com
APP_URL=example.com

these values must be the same. Let me know how it goes.

**Comment by ph4t0o0o0om** [comment]
I reinstall the system . I follow your suggestion sir to change this

**Comment by ph4t0o0o0om** [comment]
Is this v4 sir a stable version? please help thank you.

**Comment by Blair2004** [comment]
Are you running php artisan serve ?

**Comment by Blair2004** [comment]
Additionnally, if you're one Windows, this can be helpful : https://www.youtube.com/watch?v=-eXapKZrcBc

**Comment by ph4t0o0o0om** [comment]
Yes sir Im running php artisan serve. i use xampp for my server I already
setup the database. Please help me

**Comment by Blair2004** [comment]
Can you share the .env file you've modified ?

**Comment by ph4t0o0o0om** [comment]
Ok sir see text below.

APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:NbevzPj0Jgov0Dvy9pfv00nRZqC0J+o9OFi/142cgeE=
APP_DEBUG=true
APP_URL=http://127.0.0.1:8000/

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos_v4
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=http://127.0.0.1:8000/
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=
http://127.0.0.1:8000/,http://localhost/,http://127.0.0.1/,http://localhost:8888/
DB_PREFIX=ns_
NS_VERSION=4.0

**Comment by Blair2004** [comment]
try this.

SESSION_DOMAIN=127.0.0.1:8000
SANCTUM_STATEFUL_DOMAINS=127.0.0.1:8000

**Comment by ph4t0o0o0om** [comment]
I try sir but "CSRF TOKEN MISMATCH"

I already clear all history of my browser I already allow cookies for
127.0.0.1:8000 . Still no luck

**Comment by ph4t0o0o0om** [comment]
this is my cmd sir


[image: ss.PNG]

**Comment by ph4t0o0o0om** [comment]
![unnamed](https://user-images.githubusercontent.com/41504668/111239874-10e89a00-8635-11eb-966c-c80028b122be.png)

**Comment by ph4t0o0o0om** [comment]
Issue is already fix. I just check the CLOSED issues and I have same situation I just remove the port :8000 on SESSION_DOMAIN and all works fine. thanks!
