### ISSUE TITLE
You're not authenticated.

### ISSUE THREAD

**Issue by Seiteigr** [Blair2004/NexoPOS-4x#157]
Having trouble with this error, i made everything on the youtube right, the server goes online well but i cant do anything beacause of this error, "You're not authenticated."
my .env
APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:qurF0v7X+rWlXnOVtgrUnwxtfqrvdfnpNpvyR7PnUlo=
APP_DEBUG=true
APP_URL=http://127.0.0.1

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos_v4
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
DB_PREFIX=ns_
NS_VERSION=4.0
NS_AUTHORIZATION=TVw9VF8ZIu60PAzZNJFW
NS_SOCKET_PORT=6001
NS_SOCKET_ENABLED=
SANCTUM_STATEFUL_DOMAINS=127.0.0.1

![image](https://user-images.githubusercontent.com/38665612/114223687-7e42ce80-9946-11eb-9201-7b01380a215a.png)

**Comment by Blair2004** [comment]
Hi, 
APP_URL should end with the PORT.
try that and let us know.

**Comment by Seiteigr** [comment]
I try both ways no lucky

**Comment by Seiteigr** [comment]
i can login but cant use any feature, you're not authenticated all time

**Comment by Seiteigr** [comment]
rebuild from scratch same error 
APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:X/Nk+sCxt8JOr4Lyj35pTWQD+9Mt28rrQFEBoTfBpwA=
APP_DEBUG=true
APP_URL=http://127.0.0.1:8000

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos_v4
DB_USERNAME=root
DB_PASSWORD=123

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=127.0.0.1
DB_PREFIX=ns_
NS_VERSION=4.0
NS_AUTHORIZATION=RztizVHvPUpY3zULNTzH
NS_SOCKET_PORT=6001
NS_SOCKET_ENABLED=

**Comment by Blair2004** [comment]
Try to clear your cookies and try again, please. You might consider testing another browser.

**Comment by Seiteigr** [comment]
I had fix the issue after hours trying differents config in .env and .htacess, 


![image](https://user-images.githubusercontent.com/38665612/114279175-b6f7ac00-9a09-11eb-9910-cf3067d47299.png)

**Comment by Seiteigr** [comment]
https://github.com/Blair2004/NexoPOS-4x/issues/151 i have found this 
and run this on cli " node cron.js" now testing

**Comment by Seiteigr** [comment]
There's  a specif format for images ? all my uploads are broken. but aparrently all run well, workers misconfiguration error message still in there but the system work fine.

**Comment by Blair2004** [comment]
You need to run php artisan storage:link

**Comment by Seiteigr** [comment]
The [C:\laragon\Nexo\nexopos-4x\public\storage] link already exists.

**Comment by Seiteigr** [comment]
already use this

**Comment by Jesusfrojas** [comment]
Could you please share the .env and htaccess values that you found. I have the same problem.

**Comment by Blair2004** [comment]
Consider deleting the storage link that is available on the public/storage.

**Comment by Blair2004** [comment]
After having deleted, give another try to `php artisan storage:link`

**Comment by Seiteigr** [comment]
> After having deleted, give another try to `php artisan storage:link`

Done and same D: 
![image](https://user-images.githubusercontent.com/38665612/114282490-a26fdf80-9a1a-11eb-955d-fe40c096d168.png)

**Comment by Seiteigr** [comment]
> Could you please share the .env and htaccess values that you found. I have the same problem.
htaccess values i realize that i do not change anything :D 

APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:KuZd9mN5kc+EuosGHgkjc99gqyjZ1bNotMZsEvenXw8=
APP_DEBUG=true
APP_URL=localhost:8080

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos_v4
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=localhost
SESSION_COOKIE=nexopos_session

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379


MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=localhost:8000
DB_PREFIX=ns_
NS_VERSION=4.0
NS_AUTHORIZATION=dMrn7thSLv6kJUde7z9F
NS_SOCKET_PORT=6001
NS_SOCKET_ENABLED=

**Comment by Seiteigr** [comment]
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME in the console 
More prints if it help 

![image](https://user-images.githubusercontent.com/38665612/114282625-6721e080-9a1b-11eb-818b-87e490568630.png)

**Comment by Seiteigr** [comment]
i believe there is something deeply wrong, can't add new itens whitout bugs too D: 

![image](https://user-images.githubusercontent.com/38665612/114282812-984ee080-9a1c-11eb-8e45-09d41efc4ba4.png)

**Comment by Jesusfrojas** [comment]
> localhost:8080

Thanks but it didn't work for me!

**Comment by Blair2004** [comment]
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME in the console
> More prints if it help
> 
> ![image](https://user-images.githubusercontent.com/38665612/114282625-6721e080-9a1b-11eb-818b-87e490568630.png)

Apparently, the storage is symlink is not created. As I've suggested, make sure to delete the storage file that is available on the "public" directory.

**Comment by Blair2004** [comment]
> > localhost:8080
> 
> Thanks but it didn't work for me!

Open a new issue where you share your configuration file.

**Comment by Seiteigr** [comment]
> > Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME in the console
> > More prints if it help
> > ![image](https://user-images.githubusercontent.com/38665612/114282625-6721e080-9a1b-11eb-818b-87e490568630.png)
> 
> Apparently, the storage is symlink is not created. As I've suggested, make sure to delete the storage file that is available on the "public" directory.

i used "rm public/storage" and php artisan storage:link 
the result is the same

**Comment by Blair2004** [comment]
Why on the image address the port is 8080 and on the browser address bar the port is 8000... it cannot work!

**Comment by Seiteigr** [comment]
> p

already fix that ://

**Comment by Blair2004** [comment]
Hi, I believe your issue is solved. If you have any other issues please feel free to open a new thread.

**Comment by yasirmturk** [comment]
Reason for this error message is that all api calls failed!!
👎 API calls fail due to sanctum auth failure..
👍 To fix make sure that the domain is correct in `.env` file for `SANCTUM_STATEFUL_DOMAINS=`
