### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Quique9** [Blair2004/NexoPOS-4x#16]
Hi Blair2004. 
I was using the NexoPOS-3 version, but at the moment I am trying to see the new features of this version.
I have followed the prompts to do it but I run into some errors when doing it
After doing all the installation steps and running the wizard, when trying to save the database it shows me "symlink (): No such file or directory". The solution I found to this to advance to the next step was:
1- public cd
2 - rm storage
3- cd ..
4- php artisan storage: link
Then show me the confirmation message with the path
"The [/ home / x_mydomain_x / public_html / NexoPOS-4x-master / public / storage] link has been connected to [/ home / x_mydomain_x / public_html / NexoPOS-4x-master / storage / app / public]."
"The links have been created."

Reloading the page and loading the data I get the confirmation message: "The connection with the database was successful."
And move on to the next step "configuration"

After completing the form and pressing the "Create installation" button, it shows the animation as it performs a process but does not advance, it stops after a few seconds.

Controlling the database, i realize that was created two tables, ns_migrations and ns_nexpos_medias, but without content in any of them.

Since already very grateful for any help.
Regards.
Quique9

**Comment by Blair2004** [comment]
Hi Does your systeme is available online ?

**Comment by Quique9** [comment]
Yes. Do you need the login details?

**Comment by Blair2004** [comment]
email us that at contact@nexopos.com

**Comment by Blair2004** [comment]
closed for inactivity
