### ISSUE TITLE
Several units of a product in the kitchen

### ISSUE THREAD

**Issue by Miguelin96** [Blair2004/NexoPOS-4x#191]
-  When you order more than one unit in a product, the kitchen screen does not show the number.  In the ready food if it comes out correctly

-  And the translation of "in progress" is cut off when the product name is too long:
 <img width="334" alt="Capturacocina" src="https://user-images.githubusercontent.com/54648539/118454736-fbf1bb00-b6f8-11eb-9ad1-8e1f6d298ae7.PNG">

**Comment by Blair2004** [comment]
Fixed
