### ISSUE TITLE
Problem with the translation and being able to modify the payment methods

### ISSUE THREAD

**Issue by Miguelin96** [Blair2004/NexoPOS-4x#192]
In the sales ticket using NPS I see that the word "Tendered" appears, this should say "Delivered", also, did it open the possibility of changing the payment methods?

**Comment by Blair2004** [comment]
Please consider sharing an image

**Comment by Miguelin96** [comment]
![16212577653201776912390467089903](https://user-images.githubusercontent.com/54648539/118495718-c1514800-b723-11eb-8b75-ee084e4f47dc.jpg)
![Uploading 16212577791682306642038067010938.jpg…]()

**Comment by Miguelin96** [comment]
![IMG-20210517-WA0019](https://user-images.githubusercontent.com/54648539/118495941-f9f12180-b723-11eb-9419-9fd1a1773703.jpeg)
![16212578741568513148753291335534](https://user-images.githubusercontent.com/54648539/118495991-02e1f300-b724-11eb-93d4-92512145c4db.jpg)

**Comment by Blair2004** [comment]
If you would like to change the language file you can proceed here : https://github.com/Blair2004/NexoPOS-4x/edit/master/resources/lang/es.json

**Comment by Blair2004** [comment]
Fixed
