### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by Miguelin96** [Blair2004/NexoPOS-4x#193]
I have a "waiter" role where the restaurant view is deactivated and the kitchen is disabled, but when I log in with that role, the kitchen and table modification appear.

<img width="673" alt="Capturaroles01" src="https://user-images.githubusercontent.com/54648539/118614071-aa603380-b7bf-11eb-9dde-bdcd5462dc6c.PNG">
<img width="356" alt="Capturarol02" src="https://user-images.githubusercontent.com/54648539/118614299-e09db300-b7bf-11eb-83c8-4e926eb05f81.PNG">

**Comment by Blair2004** [comment]
Should already be fixed.
