### ISSUE TITLE
Error creating and modifying product categories

### ISSUE THREAD

**Issue by Miguelin96** [Blair2004/NexoPOS-4x#196]
When I try to create or modify a category of products it gives these errors

<img width="1024" alt="Captura000002" src="https://user-images.githubusercontent.com/54648539/118813224-38ffae00-b8af-11eb-9f40-c79032261344.PNG">
<img width="945" alt="Captura00003" src="https://user-images.githubusercontent.com/54648539/118813228-39984480-b8af-11eb-8089-6ae624622edd.PNG">

**Comment by Blair2004** [comment]
Fixed with https://github.com/Blair2004/NexoPOS-4x/commit/8a65729354e808af3ac78ee7271591a5e592f903
Will be deployed shortly.
