### ISSUE TITLE
Nexopos install issue

### ISSUE THREAD

**Issue by SzaZo-Halycomp** [Blair2004/NexoPOS-4x#201]
Hi,
We want to try nexopos, but stuck with the installation. I followed the documentation, everything looks perfect, but when i log in cant do anything. In some cases a red popup shows, and sais "You're not authenticated.". Could you help me where we made the mistake?

best regards
Zoltan

**Comment by Blair2004** [comment]
Hi, 
try to do a new installation with the latest dev build.

**Comment by SzaZo-Halycomp** [comment]
i tried the latest version and 4.2.2 and 4.0.0. neither of them is working. the same issue. the latest nodejs latest composer. Something related with the xcsr cookie auth, i think.

**Comment by Blair2004** [comment]
Please send your .env file at contact@nexopos.com we'll send you back the updated version with the fix.
If you would like to know how to fix it yourself, Your need to make sure that : 
SESSION_DOMAIN, SANCTUM_STATEFUL_DOMAINS are pointing to the same domain as APP_URL, but without leading http:// or https://.

**Comment by SzaZo-Halycomp** [comment]
ok. thank you. looks like it is ok now. in the example the SANCTUM_STATEFUL_DOMAINS is coming with http and i wrote it with http. the solution was to delete it. thank you:)
