### ISSUE TITLE
Stock Adjustment

### ISSUE THREAD

**Issue by SzaZo-Halycomp** [Blair2004/NexoPOS-4x#202]
In stock adjustment if i try to add quantity, it sais "The specified quantity exceed the available quantity.". I tried on the demo page too, but it is the same. Maybe you dont check whether it is adding, or loss.
best regards
Zoltan

**Comment by Blair2004** [comment]
I'll take a look. Thanks.

**Comment by Blair2004** [comment]
Fixed with : https://github.com/Blair2004/NexoPOS-4x/commit/e8c0c3b887eae6d333e73f756cc4e22e1c7fc48d
