### ISSUE TITLE
After login in my NexoPOS dashboard when i click any click then give error "Unauthenticated."

### ISSUE THREAD

**Issue by kapasia24** [Blair2004/NexoPOS-4x#2106]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'any link'
3. Scroll down to 'not open the link page'
4. See error "Unauthenticated"

**Expected behavior**
Login in my dashboard and then click any link of dashboard then didn't open the page and given error "Unauthenticated"

**Screenshots**

**Environment:**
 - NexoPOS vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Hi, have you received any external help regarding this ?
