### ISSUE TITLE
"You're not Authenticated."

### ISSUE THREAD

**Issue by Vishal-Mayal** [Blair2004/NexoPOS-4x#214]
Hello, the update from version 3.x to 4.x seems awesome from the demo! So, i gave it a try, installed it on localhost using xampp, i made sure all the requirements were met such as composer/node js and such. Had an error in the database page of do-setup, but i fixed it by manually migrating the database. I can login in successfully in the dashboard, but i'm now left with the 2 errors, 1. "You're not authenticated" when trying to access anything. (see the screenshot provided) 2. the images aren't loading. I've tried everything i came across in the closed issues but i can't find a fix for this.
![not authenticated error](https://user-images.githubusercontent.com/86639458/123757085-3dba7780-d8db-11eb-93d3-8624e43797f1.PNG)

**Comment by Vishal-Mayal** [comment]
my env file : 
```
APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:EVuo1/T4J/ClJiW+PEJM9x8C4S7uhCEDr6D5CgZrYq8=
APP_DEBUG=true
APP_URL=http://127.0.0.1

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=pos
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=127.0.0.1,localhost
DB_PREFIX=ns_
NS_VERSION=4.3.1
NS_AUTHORIZATION=Q90GhXWlhhyAiMQXAjOm
NS_SOCKET_PORT=6001
NS_SOCKET_DOMAIN=127.0.0.1:8000
NS_SOCKET_ENABLED=false
```

**Comment by Vishal-Mayal** [comment]
so apparently, when i removed the localhost from ` SANCTUM_STATEFUL_DOMAINS=127.0.0.1,localhost`, it seemed to authorize my user, to anyone whos facing the same problem, try keeping only 1 sanctum stateful domain, and then php artisan serve again and try if that works.

**Comment by Blair2004** [comment]
The address used before the installation should be the same used after the installation.
