### ISSUE TITLE
fast ordering flow

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#227]
if we have walk in customer willing to order i have to do the following process
select customers>>> customer account >> select customer >> search using his mobile number >> if not found (new customer), i will exit the screen (there is no back option) and again select customers>>> customer account >> new customer
so can we replace with the following flow
select customers>>> customer account >> select customer >> search using his mobile number >> if not found (new customer), there should be an option on the same select customer screen to save as a new customer with the searched mobile number. (high priority) beacuse it is too long flow

**Comment by Blair2004** [comment]
We'll add a button to create a customer from the search popup with the form populated (customer name).
