### ISSUE TITLE
cant open the system from another pc on the same network

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#237]
the system is working fine on the installed pc(pc1 ip 192.168.0.111) 127.0.0.0:8000 but while opening another pc on the same network using the following url (192.168.0.111:8000) even on the installed pc (pc1), i cant open using 192.168.0.111:8000 so how can i open the system from another pc on the same network. i tried to change the session domain from the .env to 192.168.0.111 but still the same. high priority

**Comment by Blair2004** [comment]
The system cannot be accessible from multiple different domains. This is one of the known limitations of using Sanctum. But you can then using the network URL(ip) for accessing  the system everywhere on the network.
