### ISSUE TITLE
installing supervisor on windows 10

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#239]
I had searched how to install the supervisor on windows 10 and make the configuration same as the provided one in the documentation guide but it seems supervisor is only for ubuntu so is there solution for this. Also it is not shown how to install and configure on Mr. Blair video on YouTube (for supervisor on windows 10)
https://prnt.sc/1e0kati

**Comment by Blair2004** [comment]
Solution can be found online. https://alternativeto.net/software/supervisor/
However, as Windows has now WSL2, you're invited to use Ubuntu within windows to benefit from Supervisor
