### ISSUE TITLE
CSRF token mismatch On Login

### ISSUE THREAD

**Issue by dchiputura** [Blair2004/NexoPOS-4x#265]
On trying to Login to NexoPos 4.x 4.4.2 am getting this error message CSRF token mismatch. 
How can i fix it

**Comment by Blair2004** [comment]
Hi, the fix is available here : https://my.nexopos.com/en/documentation/how-tos/how-to-fix-csrf-token-mismatch-on-nexopos-4-x

**Comment by Blair2004** [comment]
Closed for inactivity
