### ISSUE TITLE
Inclusive Tax calculation issue

### ISSUE THREAD

**Issue by umair975** [Blair2004/NexoPOS-4x#274]
product with inclusive tax is getting tax added on top of the total product price resulting in wrong total

Example:
Tax rate 15%
product selling price = 100 (inclusive of tax)

adding this product to invoice will do the following
tax value 13.04 (Correct)
unit rate should be 100-13.04 = 86.96 so when tax is added it becomes 100
but now it is adding 13.04 to 100 (that is already having tax included) resulting in 100 + 13.04 = 113.04 as total instead of 100 with 13.04 tax included in that.

**Comment by Blair2004** [comment]
Hi, 
can you provide a sample receipt (screenshot) ?
And how you've configured the tax on the settings ?

**Comment by Blair2004** [comment]
After further verification you're right.

**Comment by Blair2004** [comment]
Fixed for 4.5.x
