### ISSUE TITLE
Media Images Preview Not Available

### ISSUE THREAD

**Issue by apddequina** [Blair2004/NexoPOS-4x#279]
I am running my project on my local server (Laragon), but I am encountering problems with image displays URL redirection(?) or source whenever I upload or incorporate it with a product or just an uploading process itself. The image shows a broken icon and when I search for the image source an error appears. I would appreciate it if you can fix this problem for me. Thank you.

**Comment by Blair2004** [comment]
Hi, consider sharing a sample of your .env file.

**Comment by apddequina** [comment]
This is my ".env" file. I also sent an email via google. https://github.com/apddequina/pos/blob/c5bb15e81659651d8a6e49915992f316bcf2f57b/.env

**Comment by Blair2004** [comment]
There is a mismatch between your APP_URL and your SESSION_DOMAIN and SANCTUM_STATEFUL_DOMAINS.
If session domain is "pos.test" the APP_URL should be "http://pos.test" as well.

**Comment by apddequina** [comment]
Hello,

This is my updated .env file, I changed the APP_URL and SESSION_DOMAIN to match with each other as per instructed but still there's a 404 error. It might be the URL that's been generated is incomplete. Here's a screenshot for reference.

https://prnt.sc/1r1lae3

**Comment by Blair2004** [comment]
On the public folder there might be a "storage" symbolic link. If that link has been generated before the URL is changed, it will point to the previous URL and therefore cause 404. 

Make sure to delete that symbolic link and from the CLI type the following command :

php artisan storage:link

**Comment by Blair2004** [comment]
Closed for inactivity
