### ISSUE TITLE
Reports Not Filtering According to Date and Time

### ISSUE THREAD

**Issue by apddequina** [Blair2004/NexoPOS-4x#280]
I am having problems with generating reports. Whenever I filter or sort it by the exact time and date, it is not previewing the reports that are just due on that specific date and time. Can you please look forward on this? Thank you.

**Comment by Blair2004** [comment]
Hi, which report are concerned. Have you set the date as well ?

**Comment by apddequina** [comment]
I had set the time but for instance, when I had an order placed, then I generate a report for a specific time frame, it shows ALL the order reports of THAT WHOLE DAY, instead of just those ordered at that exact time.

**Comment by Blair2004** [comment]
Thank you we'll be checking using those details.
