### ISSUE TITLE
Product added but not showing on pos 

### ISSUE THREAD

**Issue by Tex1000** [Blair2004/NexoPOS-4x#281]
After adding the multi store addon I noticed that when I add a product it doesn’t show in the pos but item when I search for it In the pos search, it can be found.

**Comment by Blair2004** [comment]
Thank you for reporting, We'll be taking a look.

**Comment by Blair2004** [comment]
This can possibly help : https://my.nexopos.com/en/documentation/troubleshooting/products-not-showing-on-the-pos
