### ISSUE TITLE
Sales Commissions

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#283]
Sales commissions it does not support multistore, when enabling the extension it throws this error

<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 22 21 50" src="https://user-images.githubusercontent.com/80654041/131771316-33489354-6d2b-4bb1-bb06-7951061cb4f5.png">

**Comment by Blair2004** [comment]
Thank you for reporting. We'll take a look

**Comment by Blair2004** [comment]
This should be fixed with the commission module 4.5
https://my.nexopos.com/en/marketplace/item/sales-commissions
