### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#284]
in the pos page The language if updated the page does not load the language to 100%

Spanish Language:
<img width="1366" alt="Spanish" src="https://user-images.githubusercontent.com/80654041/131771654-b5c83014-996f-432c-99e6-cc602d34773a.png">

if I update the page it looks like this

<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 22 01 42" src="https://user-images.githubusercontent.com/80654041/131771719-9c839b44-399f-41f0-a7a7-06b76b0b533a.png">

**Comment by Blair2004** [comment]
We haven't been able to reproduce this issue. From our end, the languages load successfully. Might be a caching issue and in that case, you're invited to try with another browser.

Let us know.
