### ISSUE TITLE
NPS Adaper is not compatible with MULTISTORE

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#285]
This page does not work if the multistore module is activated
<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 22 33 13" src="https://user-images.githubusercontent.com/80654041/131772130-f867b851-6fe9-41de-9e9a-fcccc1f1e285.png">

With multistore module activated
<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 21 59 52" src="https://user-images.githubusercontent.com/80654041/131772182-29b24ac8-e0ae-4ce0-8915-e695b3a3bb08.png">

**Comment by Blair2004** [comment]
This should be fixed with update 4.5.x
