### ISSUE TITLE
Gastro Multistore table creation error

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#286]
When creating a table and putting save, it throws this error:
<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 21 59 52" src="https://user-images.githubusercontent.com/80654041/131772455-34113ae7-208c-42c0-8663-35f2b5ad64bb.png">

If I go back, the table is created, it happens with each creation of a table:
<img width="1366" alt="Captura de pantalla 2021-09-01 a la(s) 22 33 13" src="https://user-images.githubusercontent.com/80654041/131772563-4530aa6a-a9e8-4fb4-838f-9e2591ed710d.png">

**Comment by Blair2004** [comment]
Hi, 
Are you still facing that issue ?

**Comment by ahorasoyfelipe** [comment]
now works without problems
