### ISSUE TITLE
Not Authenticated

### ISSUE THREAD

**Issue by auliaharvy** [Blair2004/NexoPOS-4x#287]
i install nexo POS locally, i'm done installing and i can login. but when i login there is a message "You're not authenticated"

**Comment by tungnt-vn** [comment]
I still get this error when deploy to CentOS server. How is solution for it?

**Comment by kevinhdw** [comment]
Hello @tungnt-vn , I encountered this issue and solved it by opening ".env" file and setting "SANCTUM_STATEFUL_DOMAINS" to the correct ip and port.

For example, 
 APP_URL=http://127.0.0.1:8000
...
SANCTUM_STATEFUL_DOMAINS=127.0.0.1:8000
