### ISSUE TITLE
4.5 Bugs

### ISSUE THREAD

**Issue by apddequina** [Blair2004/NexoPOS-4x#293]
- Search in Stock Adjustment still broken
- Products are not adding to their categories (Possible issue caused in Stock Adjustment)

https://prnt.sc/1rjyymj
https://prnt.sc/1rjzigw

Really??

**Comment by apddequina** [comment]
Products not showing in POS Window. Just categories.

SC 1 - https://prnt.sc/1rk03c4
SC 2 - https://prnt.sc/1rk07oz

**Comment by Blair2004** [comment]
Consider creating separated issues so that we can handle your issue separately. This might be applicable to your case https://my.nexopos.com/en/documentation/troubleshooting/products-not-showing-on-the-pos

regarding the first 2 screenshots i'm not sure to understand. Note that after updating you might need to rebuild the app assets or to clear your cache : 

`rm -rf node_modules/ `
`npm i`
`npm run prod`

**Comment by apddequina** [comment]
Hello,

The stock adjustment module is still not working for me after the new version installation. Any chance you can help us? We are really in a tight situation here. The store started operating 2 weeks ago and still we had not used the NexoPOS V4 because of this issue.

**Comment by apddequina** [comment]
https://prnt.sc/1rl1ck7

**Comment by Blair2004** [comment]
What is the issue faced with the stock adjustment module ? Note that the barcode, sku, and name of the product are used as a search argument.

**Comment by apddequina** [comment]
The issue is still not fixed.

As you can see I have 5 products encoded into the system...
https://prnt.sc/1rl1nwu

But when I try to search in the stock adjustment module, it does not appear.
https://prnt.sc/1rl1njl

**Comment by Blair2004** [comment]
I see you have dematerialized products... such products can't have their inventory changed... normally. They are uncountable products.

**Comment by apddequina** [comment]
Hi. I changed all to materialized products, still no changes.

https://prnt.sc/1rl3hjy

https://prnt.sc/1rl3htn

**Comment by Blair2004** [comment]
You can check on the updated demo : http://v4.nexopos.com/dashboard/products/stock-adjustment And see if that works as on your installation.

**Comment by apddequina** [comment]
Yes, I saw the updated demo and that works perfectly, but when I installed it, it does not do the things the demo does. Please if you could help me with this.

**Comment by Blair2004** [comment]
Have you tried to build the frontend asset as suggested?
We'll only be available from tomorrow 9am - 6pm GMT+1

**Comment by apddequina** [comment]
I already did this

rm -rf node_modules/ 
npm i
npm run prod

in the terminal. Still no luck.

**Comment by Blair2004** [comment]
Reach us privately (email) during our working time. We'll take a look at your installation.

**Comment by apddequina** [comment]
Okay, then. Will email you at contact@nexopos.com, right? Thanks!

**Comment by apddequina** [comment]
Hello, just to let you know I already sent an email. Thanks.

**Comment by Blair2004** [comment]
We believe the issue has been fixed so far. In case it's not, please feel free to open another issue.
