### ISSUE TITLE
Tax Type defined as Inclusive its not Including the Tax Charge in the Final Price Of the Product

### ISSUE THREAD

**Issue by dchiputura** [Blair2004/NexoPOS-4x#311]
**Describe the bug**

If you define Tax Type as Inclusive is not Including the Tax Charge in the Final Price Of the Product. For example i define the price of a product as 18 inclusive of Tax. When i am doing the Sale on the POS for an item that i sale of the product its not coming out as 18 but 15.72USD and the Tax Charge of 1.99USD is not included in te final price. Further if the tax Charge is included  the total will be 17.71USD instead of 18USD as sown below

![image](https://user-images.githubusercontent.com/47517932/134138908-0a001347-0611-4046-9c7e-326e2c343975.png)

 

**Environment:**
 - NexoPOS 4.5.3

**Comment by Blair2004** [comment]
Hi, consider sharing the image of the tax settings : 
- How you set up the tax groups
- How you assigned the tax on the POS settings (Vat tab)
- Whether you set up the tax on the item itself (yes/no).

**Comment by dchiputura** [comment]
![image](https://user-images.githubusercontent.com/47517932/134144878-d02ba7bd-a727-4c25-9244-27059dc20700.png)
![image](https://user-images.githubusercontent.com/47517932/134145267-091bab4b-2f44-4346-aa01-722dd21c5e05.png)
![image](https://user-images.githubusercontent.com/47517932/134145530-2143b785-bef4-4b03-95f5-7da9f4e86814.png)

**Comment by Blair2004** [comment]
We haven't been able to reproduce the issue. Can you provide further details? Or maybe you can contact us privately so that we can take a look at your setup (only for premium users).
