### ISSUE TITLE
Vat is miscalculated when you cancel items from an order.

### ISSUE THREAD

**Issue by emanderson2k8** [Blair2004/NexoPOS-4x#319]
So when I cancel an item in an existing order sent to kitchen, The receipt generated after payment miscalculates the VAT component.

![WhatsApp Image 2021-09-23 at 00 14 04 (1)](https://user-images.githubusercontent.com/39991915/134468237-5e5819d4-a0a8-4abc-95ee-fffd2c8c7f0f.jpeg)

![WhatsApp Image 2021-09-23 at 00 14 03 (1)](https://user-images.githubusercontent.com/39991915/134468251-7e82eb4e-d320-4761-8de2-29cc24b03118.jpeg)

NexoPOS 4.5.0

**Comment by Blair2004** [comment]
Thank you for the details.
