### ISSUE TITLE
Multi Currency System

### ISSUE THREAD

**Issue by dchiputura** [Blair2004/NexoPOS-4x#321]
Is there a possibility of coming up with a Multi Currency system that will have a base currency and has parameters for currency rates from the base currency. This will allow the POS to select the currency you want to receipt with and sales for the day are then grouped according to the currency. In some countries they use the USD as the base currrency but they also accept the local currency and other major currenciea in their transactions.

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.4]

**Comment by Blair2004** [comment]
Sorry, we don't have any plan for that at the moment.
