### ISSUE TITLE
"npm run dev" command throughout an error

### ISSUE THREAD

**Issue by pkkulhari** [Blair2004/NexoPOS-4x#322]
I cloned NexoPOS-4x's repo and tried to set up a development environment. But when I run `npm run dev`, wepack-cli throughs an error that `Error: Unknown option '--hide-modules'`

**Error:**
```
➜ npm run dev  

> dev
> npm run development


> development
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] Error: Unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options

```

**Environment:**
-  OS - Ubuntu 
 - Node - v16.10.0
 - wepback - v5.50.0

**Comment by Blair2004** [comment]
Hi, at the meantime NexoPOS 4.x is compatible with Node 14 and 15. We haven't yet tested Node 16.

**Comment by pkkulhari** [comment]
> Hi, at the meantime NexoPOS 4.x is compatible with Node 14 and 15. We haven't yet tested Node 16.

I also tried with node 14 and 15 but still, the same error occured.

Webpack is compiling assets for production successfully with `npm run prod`

But it shows errors for `npm run dev` and `npm run hot`.

**Error for `npm run dev`**
```
[webpack-cli] Error: Unknown option '--hide-modules'
```

**Error for `npm run hot`**
```
[webpack-cli] Error: Unknown option '--inline'
```

It compiles the assets successfully when I remove `--hide-modules` or `--inline` flags from scripts. But after compilation when I tried to config database by clicking on `Dashboard` button on homepage, It took me to `http://127.0.0.1:8000/do-setup` page. But just shows the logo (maybe loading symbol), nothing else.

**Comment by Blair2004** [comment]
You probably still have an invalid laravel mix on your environment. So
delete node_modules and package-lock.json and run npm i; npm run prod

**Comment by Blair2004** [comment]
Hi, after further check. Yes those script where for the previous version of laravel-mix. You're invited to use either "npm run prod" or "npm run watch" instead

**Comment by nazrul121** [comment]
Remember, contributions to this repository should follow its [code of conduct](https://github.com/Blair2004/NexoPOS-4x/blob/f760551fab4aaaae3bf2b9abf2f1ffa0b2a1d897/CODE_OF_CONDUCT.md).
