### ISSUE TITLE
[Issue] After update products dont Show

### ISSUE THREAD

**Issue by loomitz** [Blair2004/NexoPOS-4x#323]
**Describe the bug**
when I click on a product with several units in the pos, the screen simply blurs and does not teach anything.

**To Reproduce**
I just update like this
Copy new files, and run composer update

**Expected behavior**
The unit of the products should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/20279105/134571647-1d31229f-5b39-4456-9ee9-2c043806a3df.png)

If i click on Luster IN ( have multiple units inside)
![image](https://user-images.githubusercontent.com/20279105/134571680-c7ff394f-dc5f-4750-a406-ad3b931b60b4.png)

Works just fine with no multiple units products
![image](https://user-images.githubusercontent.com/20279105/134571775-b6667f9e-dcba-4bee-bf5f-306eafe9fc48.png)

**Environment:**
 - Nexopos 4.5.4
 - npm 7.24.0
 - php 7.4.16
 - ubuntu 21.04
 - nginx

**Comment by Blair2004** [comment]
Thank you for reporting. We'll be checking based on those details.
