### ISSUE TITLE
Applying Filters On Orders SQL Error

### ISSUE THREAD

**Issue by dchiputura** [Blair2004/NexoPOS-4x#326]
On trying to Apply Filters to orders am getting the following sql error message

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous (SQL: select count(*) as aggregate from `ns_nexopos_orders` inner join `ns_nexopos_users` on `ns_nexopos_orders`.`author` = `ns_nexopos_users`.`id` inner join `ns_nexopos_customers` on `ns_nexopos_customers`.`id` = `ns_nexopos_orders`.`customer_id` where `created_at` = 2021-09-24 and `payment_status` = paid and `ns_nexopos_orders`.`author` = 40)

**Environment:**
 - NexoPOS 4.5.6

**Comment by Blair2004** [comment]
Nice raised point.
