### ISSUE TITLE
Cancelled item in order doesn't show full payment on orders list

### ISSUE THREAD

**Issue by emanderson2k8** [Blair2004/NexoPOS-4x#327]
**Describe the bug**
1. Select items in an order and send to Kitchen
2. Cancel one of the items sent to the kitchen
3. Make a payment for that order
4. System will show order as partially paid

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.6]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.1), Gastro (4.5.3)]

**Comment by Blair2004** [comment]
Hi Does that order has received payment ?

**Comment by emanderson2k8** [comment]
> Hi Does that order has received payment ?

Yes it has received payment.

**Comment by Blair2004** [comment]
Unable to reproduce following those steps : 
1 - Create an order with 2 items and send it to the kitchen
2 - Cancel one of those items
3 - Make the payment of the order
4 - See the order as partially paid.
