### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [Blair2004/NexoPOS-4x#330]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Blair2004** [comment]
Hi, thank you for sharign those concern with us. Yes we'll consider adding a `SECURITY.md` file. Meanwhile, you can disclose the vulnerability here `contact@nexopos.com`. Your contribution is more than welcome.

**Comment by Blair2004** [comment]
thank you for your contributions.
