### ISSUE TITLE
[Issue] Media uploading not working correctly

### ISSUE THREAD

**Issue by loomitz** [Blair2004/NexoPOS-4x#337]
**Describe the bug**
When i upload a picture, did upload correctly to /storage/(date)/ but appears broken on the web and the link didnt work

**To Reproduce**
1. this start when i update the version of nexopos

**Expected behavior**
Upload are expected to appear on filebrowser

**Screenshots**
![image](https://user-images.githubusercontent.com/20279105/136116713-07882a1c-7618-41d6-9dba-4f7956469290.png)
![image](https://user-images.githubusercontent.com/20279105/136116738-56a409bd-f584-4542-80f9-97c36791cf02.png)
![image](https://user-images.githubusercontent.com/20279105/136116753-9a626485-a845-4163-8230-6de74c42024c.png)
![image](https://user-images.githubusercontent.com/20279105/136116792-c320bb03-e885-42ca-aa4c-a9c0df3c9116.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Hi, thank you for reaching out.
Check if this helps : https://my.nexopos.com/en/documentation/troubleshooting/broken-media-images
