### ISSUE TITLE
Can't Build on Digitalocean

### ISSUE THREAD

**Issue by ExodazTH** [Blair2004/NexoPOS-4x#352]
`[nexopos] [2021-11-07 10:10:38]    PHP: https://do.co/apps-buildpack-php
[nexopos] [2021-11-07 10:10:38] 
[nexopos] [2021-11-07 10:10:38] => Building app
[nexopos] [2021-11-07 10:10:38] 
[nexopos] [2021-11-07 10:10:38] ---> Node.js Buildpack
[nexopos] [2021-11-07 10:10:38] ---> Installing toolbox
[nexopos] [2021-11-07 10:10:38] ---> - jq
[nexopos] [2021-11-07 10:10:43] ---> - yj
[nexopos] [2021-11-07 10:10:44] ---> Getting Node version
[nexopos] [2021-11-07 10:10:44] ---> Resolving Node version
[nexopos] [2021-11-07 10:10:48] ---> Downloading and extracting Node v14.18.1
[nexopos] [2021-11-07 10:11:04] ---> Parsing package.json
[nexopos] [2021-11-07 10:11:06] ---> No file to start server
[nexopos] [2021-11-07 10:11:06] ---> either use 'docker run' to start container or add index.js or server.js
[nexopos] [2021-11-07 10:11:06] Error: package-lock.json does not exist. Please commit either a package-lock.json or yarn.lock file to your repository and try again.
[nexopos] [2021-11-07 10:11:06] project does not contain a package manager lockfile
[nexopos] [2021-11-07 10:11:06] ERROR: failed to build: exit status 1
[nexopos] [2021-11-07 10:11:08] 
[nexopos] [2021-11-07 10:11:08] For documentation on the buildpacks used to build your app, please see:
[nexopos] [2021-11-07 10:11:08]    Node.js: https://do.co/apps-buildpack-node
[nexopos] [2021-11-07 10:11:08]    PHP: https://do.co/apps-buildpack-php
[nexopos] [2021-11-07 10:11:08] 
[nexopos] [2021-11-07 10:11:08]  ! Build failed (145)`

**Comment by Blair2004** [comment]
Hi, 
Thank you for reporting that build issue with Digital Ocean. We're expecting all issues to be clear and well-detailed. 
We believe this issue is related to using the "Deploy On Digita Ocial", so we'll reply to that. 

We've noticed that DO (Digital Ocean) will force install and build NodeJs dependencies despite it's not necessary. We're looking forward to making those steps completely optional to ease the installation on such a platform.

Kind Regards.

**Comment by ExodazTH** [comment]
how to fix it? 

sorry i'm english so bad

**Comment by Blair2004** [comment]
For now you're invited to follow the regular installation steps. https://my.nexopos.com/en/documentation/getting-started/0-requirements

**Comment by ExodazTH** [comment]
> 
> 
> For now you're invited to follow the regular installation steps. https://my.nexopos.com/en/documentation/getting-started/0-requirements

I command php artisan serve and npm run prod but can't access in port 8000.
