### ISSUE TITLE
[Issue] My NexoPOS in V4 is not working at all

### ISSUE THREAD

**Issue by alsaihati** [Blair2004/NexoPOS-4x#357]
My pos is NexoPOS 4.5.6 
I install the module My NexoPOS try to activate but not succeed. and it is not shown in settings.

![image](https://user-images.githubusercontent.com/40363522/140984923-87fb14d1-7d73-4eae-bfc6-d186a4c46e60.png)
 
see the screenshot attached

**Comment by Blair2004** [comment]
Hi, 
We've released an update of My NexoPOS. You'll probably need to  : 
- Deactivate the license
- Disconnect From My NexoPOS
- Create a new client
- And Authenticate with My NexoPOS

If the problem persist, let us know.
