### ISSUE TITLE
Error while accessing POS module for the first time 

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#359]
**Describe the bug**
After installation when i click POS tab on the dashboard i am getting this error
in_array() expects parameter 2 to be array, null given

**Screenshots**

**Environment:**
 - NexoPOS 4.x version: [e.g. 4.6.] on Windows 10
 - 
![An error has occured](https://user-images.githubusercontent.com/13999977/142235593-48f7d1a0-e200-4e5c-8810-8e2714e3104f.png)

**Comment by Blair2004** [comment]
Hi, 
Thank you for reporting. Does any change has been applied to the source code?
Let us know.

Kind Regards.

**Comment by kabugi** [comment]
No, I have just installed a few minutes ago

**Comment by Blair2004** [comment]
Alright,
At the moment we're not working, but tomorrow, we'll send an agent to your computer to see what's going on.
Thank you for your patience.

**Comment by kabugi** [comment]
Thank you for your response, I appreciate it, I have been trying to get it
working since 13th November 2021 when I bought the modules, today one of
your staff managed to install it on windows 10 on my desktop, as I was
trying out the tabs I realized that POS tab was having a problem.

I am way behind schedule.

My username on nexo is ***@***.***


Kindly assist.

Regards
Kabugi K

**Comment by Blair2004** [comment]
Sorry for the inconvenience. As i pointed a few minutes ago, tomorrow an agent will be available for that. 
Thanks.

**Comment by kabugi** [comment]
Good Morning,
Is there staff/agent available now or what time do we connect for the
remote access via anydesk.


Regards,
Kabugi K

**Comment by Blair2004** [comment]
Hi, 
We're available, share your anydesk id to contact@nexopos.com
Also, note that we've released an update yesterday that is supposed to fix the issue you faced on the pos.

Kind Regards.

**Comment by kabugi** [comment]
Thank you,
I will try the update and let you know. I have shared my anydesk ID.

Regards,
Kabugi K

**Comment by kabugi** [comment]
Working now. Thank you
