### ISSUE TITLE
Waiter Permission to pay and alter or change an order

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#363]
1) Waiter is able to clear or pay an order despite not being given the right or permission to accept payment
2) Waiter is able to change and order that has been placed despite not having the right to update orders

**Comment by Blair2004** [comment]
HI,
Consider providing screenshot of the area affected.
Thanks.

**Comment by kabugi** [comment]
Good Evening, I am currently out of the office I will screen shot asap
however, you can create a user give the user one permission only to create
an order, login as the user, create an order using the POS module, after
order is saved or sent to the kitchen, go back to the POS module click
orders you will find it there open it from there you can pay it, or delete
the items, pick new items and send it to the kitchen, remember the only
permission is for creating an order not editing, updating or
paying/receiving payment.

Kindly check.

Regards,
Kabugi K

**Comment by kabugi** [comment]
> HI, Consider providing screenshot of the area affected. Thanks.

![Permissions1](https://user-images.githubusercontent.com/13999977/143763051-37a92392-0177-4c17-a0d2-a9a142e25a1d.png)
![orders](https://user-images.githubusercontent.com/13999977/143763052-99c83e51-dcac-4ce7-9887-3805c87e4a38.png)
![open the held order](https://user-images.githubusercontent.com/13999977/143763053-bad1a1ad-d327-4773-bc18-7e46dc74aafd.png)
![edit the order](https://user-images.githubusercontent.com/13999977/143763061-bc450a8f-de72-433d-be17-b526e3655703.png)
![order edited](https://user-images.githubusercontent.com/13999977/143763062-4835bda1-2aa6-49f6-84d5-62ace3c4f635.png)
![order saved completely different frm the 1st](https://user-images.githubusercontent.com/13999977/143763065-2c0ff419-ddf7-4fe1-a648-6bc7d18fab16.png)
![new edited or updated order](https://user-images.githubusercontent.com/13999977/143763071-135bd837-41c2-45f7-a1ae-6aa07039c7f9.png)

**Comment by Blair2004** [comment]
Thank you.
This is useful. We'll investigate using those details.

Kind Regards.

**Comment by kabugi** [comment]
Good Morning,
Do we have an update on this issue?

Regards,
Kabugi

**Comment by Blair2004** [comment]
Hi, we're working on this. Some point has already been fixed an update will be released asap.

![image](https://user-images.githubusercontent.com/5265663/145048075-61f19f9a-f03a-4271-8938-f223a5dbf2be.png)

**Comment by Blair2004** [comment]
Here is what will happen when no permission is available for editing an order : 
![image](https://user-images.githubusercontent.com/5265663/145048449-befe4aa1-b147-4a2d-86f3-244c587f5524.png)

What do you mean by clear an order.

**Comment by kabugi** [comment]
Thank you for the update
Clear an order is the same as paying or receiving payment against the order

**Comment by kabugi** [comment]
When could we expect an update to fix this issue?
