### ISSUE TITLE
Array to string conversion when creating new store

### ISSUE THREAD

**Issue by mohamed4shopicore** [Blair2004/NexoPOS-4x#364]
when we trying to create new store we have the following bug "Array to string conversion" i only enter the name of store

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.2]
 - Premium Extensions: [Gastro (4.6.2),multistore 4.6.2]

**Comment by Blair2004** [comment]
Consider providing a screenshot of the form before submitting so that we can reproduce it easilly.

**Comment by mohamed4shopicore** [comment]
![store](https://user-images.githubusercontent.com/90953474/143688470-075d3269-afbf-4fea-b446-4b6c4896d10a.png)

**Comment by Blair2004** [comment]
For now try to assign a role while creating a store. While we're
investigating.

**Comment by mohamed4shopicore** [comment]
i already assign role for the logged in user having permission "create store" and still having this issue

**Comment by mohamed4shopicore** [comment]
any update ? still not work with me

**Comment by Blair2004** [comment]
Have you downloaded the update ?
