### ISSUE TITLE
Order Details

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#366]
**Describe the bug**
Is it possible to add the waiter name and date to the kitchen order?

**Environment:**
 - NexoPOS 4.6.3
 - Premium Extensions: Nexo Print Adapter
![WhatsApp Image 2021-11-29 at 14 16 12](https://user-images.githubusercontent.com/13999977/143982608-741debb5-9558-4254-ac58-9aff40e28e36.jpeg)
, Gastro

**Comment by Blair2004** [comment]
Commit : https://github.com/Blair2004/NsGastro/commit/5debc7a6566ca20fa6dfe1c86d3602d4dcfb46e1

**Comment by kabugi** [comment]
What is the status of this issue? I see you have closed it.
