### ISSUE TITLE
Order name Feature request

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#367]
**Describe the bug**
Is it possible to add the name of the waiter to untitled order automatically when no name is typed instead of having "N/A"
This will assist the person clearing the bills identify them faster when you have different waiters

**To Reproduce**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.3, Gastro
![order name feature request](https://user-images.githubusercontent.com/13999977/143984066-1724a0b2-9002-4099-921e-0a830627244f.png)

 - Premium Extensions: Nexo Print Adapter,Gastro

**Comment by Blair2004** [comment]
Unfortunately, that's not a feature we want to implement at the moment.

**Comment by kabugi** [comment]
Sad, unfortunate but we will revisit it later
