### ISSUE TITLE
Error create store in muktistore

### ISSUE THREAD

**Issue by GilangMaulana2018** [Blair2004/NexoPOS-4x#374]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
1. Error migration
2. Cant create store in `multistore`

**Expected behavior**

**Screenshots**
![IMG-20211208-WA0002](https://user-images.githubusercontent.com/52595287/145172143-51398f81-19b1-4550-a7c7-b85e3efed463.jpeg)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.4]
 - Premium Extensions: [e.g Nexo multistore (4.6.3)]

**Comment by Blair2004** [comment]
Hi, consider trying with the multistore module 4.6.5 available on https://my.nexopos.com/en/marketplace/item/nexo-multistore-module
