### ISSUE TITLE
order history filters are not working

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#379]
**Describe the bug**
Under order history filters are not working, for example I want to see only today orders it shows me all since the POS began posting orders, How can I remove the paid orders from here? Is it possible to add more filter options? for example filter by payment status, date, author,customer, etc

**Screenshots**
![order history](https://user-images.githubusercontent.com/13999977/145777286-f94c2d27-9e29-4279-a6b9-37370c5cc446.jpeg)

**Environment:**
 - NexoPOS 4.6.5
 - Premium Extensions: Gastro (4.6.0)

**Comment by Blair2004** [comment]
The issue about the filter not working seems proven. We're working on this before dispatching update 4.6.2.
For adding more filters, you'll need to customize the source code. If you would like to suggest, open a new thread.
