### ISSUE TITLE
Order History adding more filters

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#384]
**Describe the bug**
When working with gastro orders the waiter brings the unpaid orders/bill and money/cash to the cashier, the cashier is required to add/receive payment to clear the bill and issue a receipt, to assist the cashier get/search for the correct order and add/receive payment, more filters would be required where the cashier can search for orders according to the author, payment status 

**Expected behavior**
more filters would be required where the cashier can search for orders according to the author, payment status 

**Screenshots**
![order history filters](https://user-images.githubusercontent.com/13999977/145945111-b8738217-9474-4658-a329-713c8114fe43.jpeg)

**Environment:**
 - NexoPOS 4.6.5
 - Premium Extensions: Gastro (4.6.0)

**Comment by Blair2004** [comment]
queued for NexoPOS 4.7.x
