### ISSUE TITLE
Creating default customer

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#385]
Hi Team,

There are two issues

1) I am trying to create a default customer with email Id as no-reply@xxxxx.cafe and it throws the error as 

![image](https://user-images.githubusercontent.com/16856248/146065160-784265e3-361b-4e84-be99-80db1be3813e.png)

2) And then I tried to change the email and then tried to create and now I am getting this error

![image](https://user-images.githubusercontent.com/16856248/146065270-a1de3f85-5d12-4d75-bc65-8eae531fc15a.png)

**Comment by Blair2004** [comment]
When creating an issue, do not delete the default template that is provided as that ship information we need to handle this issue. You have deleted the information about the NexoPOS version you're using.

**Comment by Blair2004** [comment]
no-reply@xxxxx.cafe
We'll improve the rule that checks the email addresses.

**Comment by Blair2004** [comment]
How have you made to submit a "no" field for customer group ?

**Comment by Blair2004** [comment]
Make sure to screenshot date settings.
![image](https://user-images.githubusercontent.com/5265663/146137204-92cfeb18-da77-4c5c-b517-01a1c77ec76d.png)

**Comment by rsidhaarth** [comment]
> 

I have created a group called "regular customer" and then tried to assign the customer to that group. And there is no such "no" field in customer group when creating customer.

**Comment by Blair2004** [comment]
Please consider creating a video that explains the steps to reproduce the
second issue.

**Comment by rsidhaarth** [comment]
Please see the snap. I just entered this field and tried to create but it did not work.

![image](https://user-images.githubusercontent.com/16856248/146177236-f7071706-f650-4dc5-843c-bdddae4b7aa3.png)

**Comment by Blair2004** [comment]
Great. We'll try to reproduce using the steps you provided. We believe this
has been made on NexoPOS 4.6.6 right ?

**Comment by rsidhaarth** [comment]
Yes, and this issue got solved when I choose some birthdate. So not sure why it happens.

I am also making a idea to improve the birthdate.

**Comment by Blair2004** [comment]
We've improved the email validation. One of the points of this issue is resolved. For upcoming issues, please create a separate thread for each issue. This issue will be closed automatically, but we'll be working on the other point.

**Comment by rsidhaarth** [comment]
Thanks a lot, keep us posted once the other also fixed.
