### ISSUE TITLE
[Issue] Cant able to Create a New Table

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#391]
**Describe the bug**

When trying to create a new table, we are getting the following error.

**To Reproduce**
Steps to reproduce the behaviour:

Goto Restaurant > Create Table, try to save it.

**Expected behaviour**

It should be able to create a new table

**Screenshots**

![image](https://user-images.githubusercontent.com/16856248/146199380-d20e6903-7dec-4058-ad0e-e0e0be0cc622.png)

**Environment:**
 - NexoPOS 4.6.6 vesrion
 - Gastro 4.6.2 version

**Comment by GilangMaulana2018** [comment]
And cant add modifier group if you turn of multiselect 
And session table not working if you turn off multi select

**Comment by Blair2004** [comment]
> And cant add modifier group if you turn of multiselect 
> And session table not working if you turn off multi select

Open a separated issue with clear details. Thanks.

**Comment by Blair2004** [comment]
Fixed with 4.6.7
