### ISSUE TITLE
emailSMS and Email Providers

### ISSUE THREAD

**Issue by nihinihi01** [Blair2004/NexoPOS-4x#392]
### Discussed in https://github.com/Blair2004/NexoPOS-4x/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **rsidhaarth** December 15, 2021</sup>
Hi Team,

Email Provider: For transactional email, I notice that you have allowed us to use only one service which is Mailgun. But Mailgun never delivers the email to Inbox. So it will be better if you provide these options and make it configurable in the admin panel.

1) SMTP 

If you give option to enter SMTP details, people can use any provider of their choice

2) SendInBlue

One of the best transactional email service provider who delivers the email to inbox 95% and more

SMS Provider: For transactional SMS, It will be better you integrate MSG91 as they are also one of the best providers and used by millions.

Thanks</div>

**Comment by Blair2004** [comment]
For SMS? we'll provide a guide on how to integrate your own SMS provider same for SMTP.

**Comment by Blair2004** [comment]
Queued for NexoPOS 4.7.x
