### ISSUE TITLE
Unable to assign printer for cash register

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#393]
**Describe the bug**

Cant able to assign printer for Cash Register. It keeps giving error even after we give the proper URL.

**To Reproduce**
Steps to reproduce the behaviour:
1. Goto POS > Cash Register
2. Enter NPS URL, choose printer and save it
3. It got saved
4. Try to edit the same cash register and it throws an error saying it cannot able to connect

**Expected behaviour**
It should save the printer and then the printing receipt needs to work

**Screenshots**
When trying to Save

![image](https://user-images.githubusercontent.com/16856248/146236635-a4b237ba-cb92-4ec8-81c9-b830031c1a65.png)

After Saving

![image](https://user-images.githubusercontent.com/16856248/146236713-9c6402e7-5013-4215-8298-18bc086e7a4c.png)

When I try to see it got saved

![image](https://user-images.githubusercontent.com/16856248/146236837-cc6a4a77-56a9-45c0-877a-26ee1a6b0b4e.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.6

**Comment by Blair2004** [comment]
Nice issue format. Thank you for easing our work. We'll be processing asap.

**Comment by Blair2004** [comment]
Hi, we have fixed this issue with a recent version. Which version are you using ?

**Comment by rsidhaarth** [comment]
I am using 4.6.8

**Comment by Blair2004** [comment]
So If I get it well. When you save the printer url address it's not saved when you edit the register again right ?

**Comment by rsidhaarth** [comment]
It is not saving at all

1) when entering the URL alone
2) when entering both URL and choosing printer

in any situation, it doesn't save. Because we are getting an error in POS saying no printer has been assigned to the register.

**Comment by Blair2004** [comment]
Fixed with Nexo Print Adapter 4.6.1
