### ISSUE TITLE
wrong reports

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#394]
**Describe the bug**
I have deleted the orders, cash register history, deleted cash register. Still, the dashboard shows sales and expenses.

**Expected behaviour**
It should not show any value when there is no order, cash register history or no cash register.

**Screenshots**
![image](https://user-images.githubusercontent.com/16856248/146240369-537ee5d7-329d-4dd0-a96a-7bdc1a475645.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.6

**Comment by Blair2004** [comment]
Does the service workers are configured on your system ? Have you installed supervisor ?

**Comment by Blair2004** [comment]
On your .en file, check the value of the QUEUE_CONNEXION and let us know.

**Comment by rsidhaarth** [comment]
The value of QUEUE_CONNECTION=sync

And I have not installed supervisor.

**Comment by Blair2004** [comment]
If you have an active support, consider contacting us privately so that we can take a look at your system (contact@nexopos.com).

**Comment by rsidhaarth** [comment]
I have sent an email, also I have now installed supervisor on centos and the script is still reporting it is not running. 

![image](https://user-images.githubusercontent.com/16856248/146506754-757522e7-b006-4817-8291-4a4caf2461dc.png)

**Comment by Blair2004** [comment]
We've made some changes to the report on NexoPOS 4.6.8 check those and reopen the issue if it persists.
