### ISSUE TITLE
Wrong Values

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#401]
**Describe the bug**

System is showing the 100s value as 1000s

**To Reproduce**

Goto dashboard and see the values

**Expected behavior**

It should show the proper value

**Screenshots**

![image](https://user-images.githubusercontent.com/16856248/146351114-ef5130d7-2ca0-453f-933c-cb7eab9c7c83.png)

I am sure 380 USD or any currency is not equal to 3.8K USD

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.6]

**Comment by Blair2004** [comment]
Consider providing your currency settings screenshot.

**Comment by Blair2004** [comment]
How can you have sales without orders on recent orders. The steps to reproduce this issue aren't clear.

**Comment by rsidhaarth** [comment]
Please dont close the issue as I reported with screenshot. There is no way once can reproduce it as I discovered only after doing these steps.

1) Created register
2) Made a test sales
3) Now want to goto production, so delete the sales, cash register history and anything related to sales

Problem

1) reports still show the sales which should not as the data got deleted
2) dashboard still shows the sales

also

1) the net income and week expense is reporting wrong values than what it actually shows on the dashboard

how 470rs is equal to 4.7K and the weird part is

it got changed again today

![image](https://user-images.githubusercontent.com/16856248/146504892-bd39ef40-8c50-498f-a208-4b22fc981fdf.png)


Issue needs to be solved are

1) If the order related transaction got deleted, then reports or dash board should not show those values
2) Net Sales and Weekly Expense should reflect proper data
