### ISSUE TITLE
auto update issue

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#405]
**Describe the bug**

Trying to update from 4.6.6 to 4.6.7 and it got failed

**To Reproduce**

Just trying to do auto update and got the issue

**Expected behavior**

Update needs to happen

**Screenshots**

![image](https://user-images.githubusercontent.com/16856248/146423053-abf4fc07-b6bf-46f1-a12a-157cad8fb414.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.6

**Comment by Blair2004** [comment]
What database software are you using and which version ?

**Comment by Blair2004** [comment]
closed for inactivity.
