### ISSUE TITLE
Session table not working

### ISSUE THREAD

**Issue by GilangMaulana2018** [Blair2004/NexoPOS-4x#408]
Session table no multi sellect not working

Please fix this issue 

And this dosent like nexopos 3 
Nothing time countdown for session table

https://user-images.githubusercontent.com/52595287/146534989-d8289c85-1b7b-4d4b-a889-adff757996ad.mp4

Double transaction in 1 table

**Comment by Blair2004** [comment]
This issue is unclear and doesn't disclose proper steps to reproduce it.
