### ISSUE TITLE
unable to create a category

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#410]
**Describe the bug**
unable to create a new category

**To Reproduce**
Go to inventory, create category

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.6
![error while creating new category](https://user-images.githubusercontent.com/13999977/146676485-71f3654c-b389-409c-a67d-8571ba6da1ec.png)

**Comment by Blair2004** [comment]
This is fixed from 4.6.7.
