### ISSUE TITLE
Table Creation error

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#418]
While creating a new table I am getting the following error if I choose the table availability >> Available

https://user-images.githubusercontent.com/87772530/147056644-990d374c-70e2-45d7-a431-d2f851ffaf3d.PNG

Nexopos V4.6.7
Gastro V4.6.2
Installing Platform: Windows10>>Laragon
PC Specs: Core2 Due 4GB RAM

**Comment by Blair2004** [comment]
Consider testing with NexoPOS 4.6.8. if the issue persist, reopen the issue.
