### ISSUE TITLE
Price changing in sales and quantity changing issue

### ISSUE THREAD

**Issue by KKBastian** [Blair2004/NexoPOS-4x#419]
**Describe the bug**
I changed the selling price of a product in POS. But the price didn't changed. Then I change the selling quantity of that product. Then the price of that product became zero. So there are two issues.

**To Reproduce**
1. Go to 'POS'
2. Click on 'a product'
3. Click on 'the price of the selected product and change the price'
4. Click on 'Quantity button and change the quantity'
5. See error

**Expected behavior**
When I change the price, it should update the selling price there. 
When I change the quantity, it should not affect to the price.

**Screenshots**

![1c80258d-084f-4219-b23d-a895e39cd96a](https://user-images.githubusercontent.com/95493311/147145128-6f884d87-2ef2-449e-8677-8ba3118b0194.jpg)
![7f5b2d9f-db3f-4072-9e71-fafc2340cb6f](https://user-images.githubusercontent.com/95493311/147145154-302577a3-4051-4b7e-b1ad-09eb4aca5c97.jpg)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.5
 - Premium Extensions: -

**Comment by Blair2004** [comment]
Consider using NexoPOS 4.6.8 if the issue persist reopen the issue.
