### ISSUE TITLE
Invoice logo preview issue

### ISSUE THREAD

**Issue by KKBastian** [Blair2004/NexoPOS-4x#424]
**Describe the bug**
I inserted a invoice log at Invoice settings, but it doesn't preview in the invoice.

**To Reproduce**
1. Go to 'settings'
2. Go to 'Invoice settings'
2. Click on 'receipt logo'
3. Select a logo
4. Click on 'save settings'
3. Go to 'POS'
4. Select a product
5. Click on 'Pay'
6. Select customer
7. Select order type
8. Click on 'Full Payment'

**Expected behavior**
The inserted logo should be preview in the invoice

**Screenshots**
![e24198fe-b3b3-4dd5-b031-33908aaaa084](https://user-images.githubusercontent.com/95493311/147269054-4a3b3ec9-e954-4d60-bfc7-448168594f0b.jpg)
![91ede0dc-741e-4ef2-bc64-e9f50c3250a9](https://user-images.githubusercontent.com/95493311/147269121-18a06f90-79c4-4e39-b5e2-4670743c9834.jpg)
![e2ea08ec-9a10-46bf-bd31-1277e8871a07](https://user-images.githubusercontent.com/95493311/147269134-2bc6f651-ce39-409a-81d5-d5cf03c3ebb2.jpg)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.5
 - Premium Extensions: -

**Comment by Blair2004** [comment]
Solved with NexoPOS 4.6.8 : https://github.com/Blair2004/NexoPOS-4x/releases/tag/v4.6.8

**Comment by thisirasandawath** [comment]
I try to install it and add the invoice logo but not displaying yet.
