### ISSUE TITLE
No Wizard Installation preview!!!

### ISSUE THREAD

**Issue by NorAfguriye** [Blair2004/NexoPOS-4x#426]
**Describe the bug**
I am currently trying to install nexoPOS and have followed the following steps

- installed laragon to my PC 
- created database and matched with the .env file 
- install composer - done
- php artisan key:generate  - done
-php artisan storage:link  - done
**Expected behavior**
i was expecting to get the installation wizard but nothing is happening a blank page with Nexo logo. 

**Screenshots**
![image](https://user-images.githubusercontent.com/89262228/147380052-4299c02a-2bd4-468b-b77b-5d1515d8a3d2.png)

![image](https://user-images.githubusercontent.com/89262228/147380047-4cc3ff18-1064-4944-a170-6c2d4d93ec3a.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 -

**Comment by NorAfguriye** [comment]
Any updates on this issue, i'm stuck please. mention: blair2004

**Comment by Blair2004** [comment]
Thanks for reporting. You must be using NexoPOS 4.6.7 at least...

**Comment by NorAfguriye** [comment]
Yes I am using the latest Sir.

**Comment by Blair2004** [comment]
The version you've mentioned on the issue is not accurate. You've mentioned be using 4.5.2.
Contact us privately at contact@nexopos.com if you have a license of NexoPOS 4.x we'll be helping out.

**Comment by NorAfguriye** [comment]
I'm using 4.6.8 version.  please support

**Comment by Blair2004** [comment]
Hi, 
For having dedicated support, contact us privately mentioning your account on my.nexopos.com.
Thanks

**Comment by magedfathi** [comment]
I would like to share my previous experience with this issue:
1- unzip the nexopos module in the following directory C:\laragon\www   dont create new folder inside www folder, it will not 
     work
2- run the command line as administrator
3- run the following command   cd C:\laragon\www 

   1- composer install                         // if not running install composer from internet then run the commadn again
   2- composer dump-autoload
   3- npm install                                  // this is the reason for your case
   4- npm run prod 	                          // this is the reason for your case
   5- npm install -g npm
   6- php artisan key.generate
   7- php artisan storage:link

4- the most important point is to change the root directory of Laragon as mention in the following photo

![laragon](https://user-images.githubusercontent.com/87772530/147557455-29220f85-486b-48de-b60d-910a7a91af75.png)

Kindly Update if it is working fine with you

**Comment by NorAfguriye** [comment]
Thanks megedfathi for the guidance this really worked.
