### ISSUE TITLE
Media Upload Scroller bar is not working (Very Low Priority)

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#428]
After Uploading Bulk Photos, the Scroller bar is not scrolling down

![scroll down is not working](https://user-images.githubusercontent.com/87772530/147557913-3d709b14-39f2-4961-8f0c-a7dfdf50066e.PNG)

NexoPos V4.6.8
Platform Windows 10 64bit

**Comment by Blair2004** [comment]
Ongonig for NexoPOS 4.7.x

**Comment by Blair2004** [comment]
Fixed with https://github.com/Blair2004/NexoPOS-4x/commit/ff344b9c369026f281f64faba5cb8a611ae18b25
