### ISSUE TITLE
Products not loading after enabling Gastro 4.6.2

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#432]
after enabling the Gastro 4.6.2, i cant load the previous creadted products and getting the following error but can create new product normally

![error2](https://user-images.githubusercontent.com/87772530/147579938-5e5d0f5f-f941-4bba-8e8b-e341d81fde44.png)

Also, while finalizing the paymnet i am getting the following error

![issu3](https://user-images.githubusercontent.com/87772530/147580366-55db81b2-6d5c-4bea-ab84-4a73da5485f5.png)

See the following Video:

https://www.youtube.com/watch?v=mmloyjlIp9s

NexoPOS 4.6.8
Gastro 4.6.2

**Comment by Blair2004** [comment]
Looks like migration hasn't successfully run on your system. Try to run those commands : 
First of all, let's clear the cache just to see if the migration will be executed.

`php artisan cache:clear`.

In case it doesn't work, let us know privately contact@nexopos.com.

**Comment by magedfathi** [comment]
I sent to you through Whatsapp

**Comment by Blair2004** [comment]
Please reach the express support privately on WhatsApp, since we need to check your system. +1 (628) 800 - 7750

**Comment by Blair2004** [comment]
I believe this is fixed for now.
