### ISSUE TITLE
Nexo Print Server Issue With Register List

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#433]
When i assign the Printer to Register and save, it is shown the following error

![printer issue](https://user-images.githubusercontent.com/87772530/147736045-f68d4380-fb18-4f56-9f70-f79f23d009e8.png)

NexoPos 4.6.8
My NexoPOS 4.6.1
NPS Adapter  4.6.0
Nexo Print Server Setup 2.6.2
printing gateway is Nexo Print Server (2X)
NPX Address is http://localhost:3236
From nexo print server setting is choose HTTP not HTTPS

Platform Windows 10 64 bit

**Comment by Blair2004** [comment]
Hi, You need to set the address on NPS Address and save it then you'll be able to see the printers.
Try that and let me know.

**Comment by magedfathi** [comment]
i sent to you on whatsapp

**Comment by rsidhaarth** [comment]
@Blair2004 I reported this issue already.

https://github.com/Blair2004/NexoPOS-4x/issues/393

And still it is not fixed

![image](https://user-images.githubusercontent.com/16856248/147848135-9013c173-fc5f-4c98-a610-dd1f9fa92194.png)

![image](https://user-images.githubusercontent.com/16856248/147848140-e871ded5-962b-4a75-8cf1-868fef8e7839.png)

Now I tried via other way also, still not working

![image](https://user-images.githubusercontent.com/16856248/147848145-3264c4d5-4a3f-486e-b45a-dddf868001d6.png)

![image](https://user-images.githubusercontent.com/16856248/147848149-74304ce3-e8a9-470b-927e-9a3899636331.png)

So this issue still not fixed and make the POS not usable, so need a hotfix immediately.

**Comment by Blair2004** [comment]
This issue is fixed with [Nexo Print Adapter 4.6.2](https://my.nexopos.com/en/marketplace/item/nps-adapter-for-nexopos-4x)
