### ISSUE TITLE
Tailwindcss SCSS error @apply class does not exist issue

### ISSUE THREAD

**Issue by NorAfguriye** [Blair2004/NexoPOS-4x#444]
when I try to save a changes in the project i got the below error say that @apply class does not exist issue. 

could any one support this issue

![image](https://user-images.githubusercontent.com/89262228/147818143-c490f8e9-0951-48f8-9376-be4d87e7f50e.png)

Environment:

NexoPOS 4.6.8

**Comment by Blair2004** [comment]
Can you share a copy of the file package.json at the root of your project ?

**Comment by Blair2004** [comment]
Consider providing more information about your environment as well including nodejs version

**Comment by NorAfguriye** [comment]
Tailwind version

"version": "3.0.8"

build tool
"version": "5.3.0",

Nodejs

v14.16.1

What browser are you using?

Chrome

What operating system are you using?

Windows

Description
I want to apply global styles to the most frequent components that i use, (inputs, btns etc)
have used @apply class but when i try to build it throws error saying @apply class does not exist. check below image.
image

also take a look at my app.scss file
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "./animations.scss";
@import "./fonts.scss";
@import "./line-awesome/1.3.0/scss/line-awesome.scss";

html,
body {
height: 100%;
font-family: 'Jost';
width: 100%;
}

html,
body {
height: 100%;
font-family: 'Jost';
width: 100%;
}

.bg-overlay {
background:rgb(51 51 51 / 26%);
}

[v-cloak] > * { display:none }

.loader {
border-top-color: #3498db !important;
&.slow {
-webkit-animation: spinner 1.5s linear infinite;
animation: spinner 1.5s linear infinite;
}
&.fast {
-webkit-animation: spinner 0.7s linear infinite;
animation: spinner 0.7s linear infinite;
}
}

@-webkit-keyframes spinner {
0% { -webkit-transform: rotate(0deg); }
100% { -webkit-transform: rotate(360deg); }
}

@Keyframes spinner {
0% { transform: rotate(0deg); }
100% { transform: rotate(360deg); }
}

/**

Forms
**/
.form-input {

label {
@apply text-gray-800 py-2 font-semibold;
}
input {
@apply border-2 border-blue-200 bg-blue-100 rounded p-2 w-full;
&[disabled] {
@apply bg-gray-300;
}
}
p {
@apply text-xs text-gray-600 py-1;
}
}

.form-input-invalid {
label {
@apply text-red-500 py-2 font-semibold;
}
input {
@apply border-2 border-red-400 bg-red-100 rounded p-2 w-full;
}
p {
@apply text-xs text-red-500 py-1;
}
}
.btn {
@apply text-center rounded shadow border py-2 px-3;
}
.btn-blue {
@apply border-blue-600 bg-blue-600 text-white;
}
.btn-red {
@apply border-red-600 bg-red-600 text-white;
}

.pos-button-clicked {
box-shadow: inset 0px 0px 5px 0px #a4a5a7;
}

.ns-table {
@apply w-full;
thead th {
@apply border border-gray-300 bg-gray-200 p-2 text-gray-700;
}
tbody td {
@apply border border-gray-200 p-2 text-gray-700;
}
tfoot td {
@apply border border-gray-200 p-2 text-gray-700;
}

tbody > tr.info {
@apply bg-blue-200;
}

tbody > tr.danger {
@apply bg-red-200;
}

tbody > tr.success {
@apply bg-green-200;
}

tbody > tr.green {
@apply bg-yellow-200;
}
}

#editor {
h1 {
@apply text-5xl font-bold;
}

h2 {
@apply text-4xl font-bold;
}

h3 {
@apply text-3xl font-bold;
}

h4 {
@apply text-2xl font-bold;
}

h5 {
@apply text-xl font-bold;
}
}

#grid-items {
.vue-recycle-scroller__item-wrapper {
@apply grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-0 overflow-y-auto;
}
.vue-recycle-scroller__item-view {
@apply cursor-pointer border h-32 lg:h-40 border-gray-200 flex flex-col items-center justify-center overflow-hidden;
&:hover {
@apply bg-gray-200;
}
}
}

/**

Components
**/
// Popup
.popup-heading {
@apply p-2 flex justify-between items-center;
h3 {
@apply font-semibold;
}
}

**Comment by Blair2004** [comment]
On the packages.json
Change the value of the dependencies "tailwindcss" from "^3.0.0" to "^2.0.4" and try again.

**Comment by NorAfguriye** [comment]
still same error Blair 
![image](https://user-images.githubusercontent.com/89262228/147828247-04fc1abe-f4b9-499a-868c-e5660c699363.png)

**Comment by Blair2004** [comment]
I forgot to tell, when you change the version of tailwindcss on package.json, you need to the packages. Ideally, you'll just need to do this `npm i tailwindcss@2` and then retry to rebuild the project.

But tell me, why did you needed to build the project as it already come built ?

**Comment by NorAfguriye** [comment]
a good question, I wanted add few colors to the dashboard and for the tailwind to effect i run; npm run watch so that whenever i save it builds automatically.

**Comment by Blair2004** [comment]
Okay so downgrading the tailwind as version is a perfect fit.

**Comment by NorAfguriye** [comment]
I'm still getting the error

**Comment by NorAfguriye** [comment]
I have re installed the project and seems has improved. but whenever i run _npm run watch_
i'm getting below error
![image](https://user-images.githubusercontent.com/89262228/147835710-af6707e9-543f-4c42-9787-19d27f0ed9b4.png)
![image](https://user-images.githubusercontent.com/89262228/147835735-aa90ceda-c699-4b5c-bbd7-2effbfebbf75.png)

please support.

**Comment by Blair2004** [comment]
If you're editing the script. Make sure to define this key on .env file

`NS_ENV=dev`

NexoPOS will load your dev asset instead.

**Comment by NorAfguriye** [comment]
Have edited the env file and changed the _ns_env=production_ to _ns_env=dev_ 
but the screen is hanging the dashboard is empty and also if refresh it and click on dashboad or sign in it's stuck loading....
![image](https://user-images.githubusercontent.com/89262228/147845878-6c235478-c973-4ddc-9fad-42505fd2dfed.png)

**Comment by NorAfguriye** [comment]
Issue is resolved, after this blank and stuck loading. i stop using the laragon and straight forward used php artisan serve and it worked. thanks so much.
