### ISSUE TITLE
Cannot Install Nexopos

### ISSUE THREAD

**Issue by ardhy-w** [Blair2004/NexoPOS-4x#449]
I had problem on install nexopos...
I used nginx as webserver to running nexopos..
below the step i'm using for installing nexopos
1. Install PHP
2. Install composer
3. Install NVM
4. Rename .env.example to .env
5. Run composer install
6. Run composer dump-autoload
7. Create MYSQL database
8. Run php artisan key:generate
9. Run php artisan storage:link
10. Run npm install
11. Run npm run prod
12. access Apps
13. Perform application setup
14. Modify set SESSION_DOMAIN=127.0.0.1 in .env file

On step 11 I've got error code like this
<img width="936" alt="Screen Shot 2022-01-01 at 11 49 56" src="https://user-images.githubusercontent.com/10648963/147844405-12ef9b51-7438-45cd-9b9c-a8413678bef7.png">
When Access apps for the first time it show like this :
<img width="615" alt="Screen Shot 2022-01-01 at 12 13 43" src="https://user-images.githubusercontent.com/10648963/147844441-8f71b1b0-44c0-4018-bb17-f52689660907.png">
but when i click. dashboard it just show logo like this
<img width="682" alt="Screen Shot 2022-01-01 at 12 13 52" src="https://user-images.githubusercontent.com/10648963/147844448-a16ffb01-1467-462d-92a4-17e2a0589a79.png">

**Comment by herybrts** [comment]
How to fix this problem?

**Comment by Blair2004** [comment]
> How to fix this problem? 

Hi please make sure to open a new thread for a better support.

Kind regards.
