### ISSUE TITLE
[Issue] Columns are not sortable

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#450]
Hi Team,

I am on the product page and I am trying to sort the item by SKU, by clicking on the column name. It just shows the effect but the columns are not sortable. 

Also please make all the columns sortable by ascending and descending as it helps a lot.

also change Sku to SKU.

![image](https://user-images.githubusercontent.com/16856248/147846085-677f1ca7-f871-4e45-ba51-70882af475d7.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.8
 - Premium Extensions: Gastro: 4.6.2

**Comment by Blair2004** [comment]
Hi, not all columns are sortable. We might rather add a Query Filter on the product table.

**Comment by Blair2004** [comment]
![sorting](https://user-images.githubusercontent.com/5265663/148922036-4994e6ba-cb4c-4c2f-9dbc-a7c337b8fd63.gif)

Columns looks sortable on 4.6.9.

Unable to reproduce.
