### ISSUE TITLE
[Issue] closing cash and register values

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#454]
Hi Team,

I entered a sale of 180rs and then closed the register by entering the value as 180rs

and I found that it is getting added to the expense

![image](https://user-images.githubusercontent.com/16856248/147848625-92ee0a08-a492-4da7-81bc-c9086df9e8b6.png)

Also, I believe closing cash should not get entered into expenses as because

closing cash is the total of all the money we generated today from all orders. so only the difference should be entered in the expense.

example: 

order : 180rs
closing cash: 180rs

it got 180 - 180 = 0, so nothing

but if the order is 180rs and the closing cash is 100rs then 80rs should get added to expense

so the bug is 

1) closing cash have issue
2) there is no way on can edit the closing cash if there is a mistake as it throws 404 error.
![image](https://user-images.githubusercontent.com/16856248/147848684-255d9ee0-8741-4ccb-ba28-23ccba97f671.png)
3) also there is no way to delete the registers entry

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.8

**Comment by Blair2004** [comment]
Cash Register transaction has been removed from the Cash Flow. Fixed with 4.9.6
