### ISSUE TITLE
[Issue] create customer without email

### ISSUE THREAD

**Issue by rsidhaarth** [Blair2004/NexoPOS-4x#455]
Hi Team,

Can't able to create a customer account without email. Please do note that we cannot enter fake emails, because we also want to add customer emails if required (15 to 10%).

So email field cannot be mandatory.

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.8

**Comment by magedfathi** [comment]
@Blair2004 Finally i found someone support my request but i can undestand your future plan which is self service or QR from the customer himself/herself so i suggest to make sign up by phone and reset as well and it will be mandatory to fill his email address to complete the profile info
Pls. do it 👯

**Comment by Blair2004** [comment]
Okay, approved!
