### ISSUE TITLE
CSRF token mismatch under  cpanel domain 

### ISSUE THREAD

**Issue by abedfatafta** [Blair2004/NexoPOS-4x#461]
we tried to upgrade 4.6.0 to 4.6.8 and after copying all files and make database update 
we face problem when we try to login : 
CSRF token mismatch.
- .env  domain and url and SANCTUM_STATEFUL_DOMAINS are the same domain name . 
- previous version working without any problem 

we tries 4.6.7 and 4.6.8  the same problem also on fresh installation same problem appear

**Comment by boudo2017** [comment]
https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-csrf-token-mismatch-on-nexopos-4-x

**Comment by abedfatafta** [comment]
thats not work on the case i mentioned .! 
the problem is the sign in request not send X-XSRF-TOKEN: undefined

**Comment by abedfatafta** [comment]
shared hosting under cpanel with subdomain

**Comment by Blair2004** [comment]
Hi can you tell what URL you use to access your system ?

**Comment by m2fik** [comment]
Hi,
I had the same problem and I think the problem is with php extension.
See if all extension are installed 
BCMath PHP Extension
Ctype PHP Extension
Fileinfo PHP Extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension
in your Hosting
[https://laravel.com/docs/8.x/deployment#server-requirements](url)

**Comment by Blair2004** [comment]
What's the status of the issue ?

**Comment by abedfatafta** [comment]
Still their .
Just resolve it as i mentioned


-- 
Regards


Abed Almonem Fatafta

**Comment by Blair2004** [comment]
What url you use to access NexoPOS online ?

**Comment by abedfatafta** [comment]
Currently no but if you like i can create one for you for testing send me
ur email and i will send it to you privatly


-- 
Regards


Abed Almonem Fatafta
Ttawor IT
Ramallah- Palestine
Skype: abed.fatafta
Tel-Fax:+970-2-2950842
Mobile: +970-59-9666221
http://www.ttawor.com

**Comment by Blair2004** [comment]
The issue might be caused but an unexpected space on some file (4.6.7) which caused cookies not able to be defined. We've fixed that issue with 4.6.8 and we do confirm it's fixed on 4.6.9. If the issue persist, feel free to reopen the issue.
