### ISSUE TITLE
custom price not working on these cases 

### ISSUE THREAD

**Issue by abedfatafta** [Blair2004/NexoPOS-4x#462]
on point of sale when you click on price to change , the price not changed , 
thats happen when the product not setted to be taxable and if the taxes is not defined , 
so  if there is no taxes , product custom pricing not work

**Comment by Blair2004** [comment]
Please make sure not to delete the default template while creating an issue. Your issue format is not valid. It's lacking information about your environment and a screenshot forwhat you're talking about.
