### ISSUE TITLE
[Issue] Multistore and subdomain 404 NOT FOUND

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#466]
Hi,
I set NS_WILDCARD_ENABLED to true in .env 
remove https:// from APP_URL
add subdomain to SANCTUM_STATEFUL_DOMAINS
and WildCard Domains is working.
I can login to the subdomain store and I show Store Selection and I select one after that it redirect to 
http://example.com/dashboard/multistore//pos1.example.com with 404 NOT FOUND.

**Environment:**
 - NexoPOS 4.6.8
 - Premium Extensions: [NexoPOS MultiStore v4.6.5]

**Comment by m2fik** [comment]
Hi,
there is no logout in select store page
![pos1](https://user-images.githubusercontent.com/36846249/148394874-ab57645a-c06d-4a54-b581-374be714ea54.jpg)
and after I select a store here
![pos2](https://user-images.githubusercontent.com/36846249/148394969-0d2c36b1-6df3-48c7-b4b2-1ea22135078f.jpg)

**Comment by Blair2004** [comment]
Hi,
Thank you for this. We'll be reviewing this.

**Comment by Blair2004** [comment]
This issue might be cause by an invalid APP_URL. can you share the URL that cause a 404 error ?
Kind Regards.

**Comment by m2fik** [comment]
Yes, It's true it cause by an invalid APP_URL and now is this [https://github.com/Blair2004/NexoPOS-4x/issues/470](url).
The URL that cause a 404 error was shared yesterday with contact@nexopos.com.

**Comment by Blair2004** [comment]
This issue will thefore be closed in favor of that one.
