### ISSUE TITLE
cannot login with pin

### ISSUE THREAD

**Issue by jagokasir** [Blair2004/NexoPOS-4x#469]
can't login using pin, even though it's already set pin to login.

the pin is hidden when the enter button is clicked, I have to delete it first before I can input the pin

**Comment by jagokasir** [comment]
https://user-images.githubusercontent.com/68942105/148521672-46bda097-7bb9-4ce5-be49-c80698e2b6cc.mov

**Comment by Blair2004** [comment]
Thank you for reporting this.

**Comment by Blair2004** [comment]
Fix added to 4.6.9
