### ISSUE TITLE
[Issue] Isolated Login for MultiStore

### ISSUE THREAD

**Issue by Blair2004** [Blair2004/NexoPOS-4x#470]
**Describe the bug**
With the wildcard feature enabled, while trying to login to a sub store, we're redirected to the main login page.

**To Reproduce**
1. Create a store
2. Enable wildcard option
3. Try to login to the dashboard by using https://pos1.example.com/dashboard
4. You're redirected to example.com/sign-in

**Expected behavior**
We should be able only to access the login page for the sub-store. This to avoid exposing other stores or the main store.

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.9
 - Premium Extensions: Nexo MultiStore

**Comment by m2fik** [comment]
Hi,
now it works but there are permissions issues look this [https://github.com/Blair2004/NexoPOS-4x/issues/487](url)

**Comment by Blair2004** [comment]
Thank you, this issue will be closed in favor of the new one.
