### ISSUE TITLE
Error when reset data [MultipleStore]

### ISSUE THREAD

**Issue by jagokasir** [Blair2004/NexoPOS-4x#474]
<img width="1425" alt="Screen Shot 2022-01-11 at 21 54 29" src="https://user-images.githubusercontent.com/68942105/148966872-bc49a4ec-1bdc-43eb-970e-6623b2c41c78.png">

**Comment by Blair2004** [comment]
The issue is not clear and well described to be handled. Please while creating an issue use the available template and do not clear it just to upload an image without proper description.
