### ISSUE TITLE
[Issue] on hold orders showing products issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#483]
Hi,
when I tried to open on hold order ,no products are shown, only total prices
How to fix that ?
regards

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 NexoPOS 4.6.9
Premium Extensions: Gastro (4.6.2)
![WhatsApp Image 2022-01-12 at 12 58 15 AM](https://user-images.githubusercontent.com/22215705/149038566-e23316cc-7652-48e3-b3fe-49273fcef731.jpeg)

**Comment by Blair2004** [comment]
We need to check your system for that. Let us know at contact@nexopos.com

**Comment by Blair2004** [comment]
What's the status so far ?

**Comment by boudo2017** [comment]
Still not fixed
