### ISSUE TITLE
[Issue] sub store permissions & StoreAdministrator Role

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#487]
**Describe the bug**
Store Administrator has not permissions to change, delete users from main store and there is no substore users in DB or field in Users Table . 

**To Reproduce**
1. Go to g https://pos1.example.com/dashboard
2. Click on Users/List
3. Display all user and can edit , delete, change password as Store Administrator Role

**Expected behavior**
Store Administrator Role has not permissions to edit, delete Users only substore users.

**Screenshots**
![per1](https://user-images.githubusercontent.com/36846249/149062353-86bf6160-cddd-4478-a035-8bbf8a4ef4ec.jpg)
![per2](https://user-images.githubusercontent.com/36846249/149062367-ee51b5af-92f6-487e-b186-caf455462b75.jpg)

**Environment:**
 - NexoPOS 4.6.8
 - Premium Extensions: Nexo MultiStore 4.6.6

**Comment by Blair2004** [comment]
Fixed with : https://github.com/Blair2004/NsMultiStore/commit/33c314d356ab04823fa5c6f071a9b59f171e0a00

**Comment by m2fik** [comment]
Hi,
I can't see the solution?

**Comment by Blair2004** [comment]
Hi,
Have you tried the last update ? Alternatively, you can still enable the permission you want for the role of your choice.
