### ISSUE TITLE
can not update to 4.6.9 using MyNexo

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#493]
While updating the NexoPos to version 4.6.9 it is shown the following error:

![update issue](https://user-images.githubusercontent.com/87772530/149288433-f24220d3-c448-4888-9525-e95d28f872be.PNG)

NexoPos Version: 4.6.8
Platform: Laragon on Windows 10
Note: Authentication and Validation is done
My NexoPOS Version : 4.6.2
Gastro 4x - Restaurant Extension Version: 4.6.2
NPS Adapter Version: 4.6.2

**Comment by Blair2004** [comment]
Hi,
Which database version are you using ?

**Comment by Blair2004** [comment]
I just realized you're using Laragon. Unfortunately, Laragon doesn't work well for that module (My NexoPOS) some of the required configuration aren't available like mysqldump, which is used for backing up your database. We'll suggest [updating manually for now](https://my.nexopos.com/en/documentation/how-tos/updating-nexopos-4-x).

**Comment by Blair2004** [comment]
Have you been able to update your system ?

**Comment by magedfathi** [comment]
i will close the issue since i got your answer for the main reason
