### ISSUE TITLE
[Issue] update to 4.6.9 problem 

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#495]
**Describe the bug**
Trying to get property 'created_at' of non-object. 

**To Reproduce**
1. update to 4.6.9

**Environment:**
 - NexoPOS 4.6.8
 - Premium Extensions: Nexo MultiStore 4.6.6

**Comment by m2fik** [comment]
resolved with:
add if condition to 2022_01_02_200145_wipe_cash_flow_transaction_2janv22.php in 
database/migrations/schema-updates folder because there are no orders.

       ` if($order != null){
        .........
        }
`

**Comment by Blair2004** [comment]
Thanks this was already added to the fix.
https://github.com/Blair2004/NexoPOS-4x/pull/502/files#diff-411357ecea78d476d5e0741f802c9902f762d8051917c0814f8d6dc9844cc44d
