### ISSUE TITLE
[Issue] Too few arguments to StoreRefreshExpenseJob::__construct()....

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#496]
**Describe the bug**
Too few arguments to function Modules\NsMultiStore\Jobs\StoreRefreshExpenseJob::__construct(), 2 passed in vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 17 and exactly 3 expected

**To Reproduce**
1. disable cash register
2. Click on pos
3. add item with qty and price
4. paid a full amount
5.  get error

**Screenshots**

![LINE_P2022113_204445](https://user-images.githubusercontent.com/36846249/149381941-0424d027-bc80-4bb1-8e84-ec872f61d5b4.jpg)

**Environment:**
 - NexoPOS 4.6.9
 - Premium Extensions: Nexo MultiStore 4.6.6

**Comment by Blair2004** [comment]
We'll re reviewing this.

**Comment by m2fik** [comment]
missing an event in MultiStoreCoreEventSubscriber listener

` /**
     * Dispathc a report update
     * @param $event
     * @return void
     */
    public function dispatchMonthReportUpdate( $event )
    {
        StoreComputeDashboardMonthReportJob::dispatch( Store::current() )
            ->delay( now()->addSeconds(10) );
    }`
correct is 
`/**
     * Dispathc a report update
     * @param $event
     * @return void
     */
    public function dispatchMonthReportUpdate( $event )
    {
        StoreComputeDashboardMonthReportJob::dispatch( Store::current(), $event )
            ->delay( now()->addSeconds(10) );
    }`

**Comment by m2fik** [comment]
missing an $range_ends in MultiStoreExpensesEventSubscriber listener
`/**
         * Will dispatch event for refreshing expenses
         * for a specific date
         */
        $event->listen(
            ExpenseBeforeRefreshEvent::class,
            fn( $event ) => StoreRefreshExpenseJob::dispatch( Store::current(), $event->dashboardDay )->delay( $event->date )
        );`
is this $event->date->endOfDay()->toDateTimeString() an $range_ends???

**Comment by Blair2004** [comment]
Thank you for this... i'm not able to completely understand your code snippet as it's not well formatted.
[Take a look here](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to understand how to format your code.

**Comment by m2fik** [comment]
here file StoreComputeDashboardMonthReportJob Jobs has construct with 2 params
```
class StoreComputeDashboardMonthReportJob extends ComputeDashboardMonthReportJob implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels, Dispatchable, Queueable;

    public $store;
    public $event;

    public function __construct( Store $store, $event )
    {
        $this->store    =   $store;
        $this->event    =   $event;
    }

    public function handle()
    {
        ns()->store->setStore( $this->store );
        parent::handle();
    }
}
```
called from file MultiStoreCoreEventSubscriber with 1 params 

```
    /**
     * Dispathc a report update
     * @param $event
     * @return void
     */
    public function dispatchMonthReportUpdate( $event )
    {
        StoreComputeDashboardMonthReportJob::dispatch( Store::current() )
            ->delay( now()->addSeconds(10) );
    }
```
correct 
```
   /**
     * Dispathc a report update
     * @param $event
     * @return void
     */
    public function dispatchMonthReportUpdate( $event )
    {
        StoreComputeDashboardMonthReportJob::dispatch( Store::current(), $event )
            ->delay( now()->addSeconds(10) );
    }
```

**Comment by m2fik** [comment]
here file StoreRefreshExpenseJob has construct with 3 params

```
class StoreRefreshExpenseJob extends RefreshExpenseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithSockets, SerializesModels;
    
    public $range_starts;
    public $range_ends;
    public $store;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct( Store $store, $range_starts, $range_ends )
    {
        $this->range_starts     =   $range_starts;
        $this->range_ends       =   $range_ends;
        $this->store            =   $store;
    }

    public function handle()
    {
        ns()->store->setStore( $this->store );
        parent::handle();
    }
}
```
called from file MultiStoreExpensesEventSubscriber with 2 params

```
        /**
         * Will dispatch event for refreshing expenses
         * for a specific date
         */
        $event->listen(
            ExpenseBeforeRefreshEvent::class,
            fn( $event ) => StoreRefreshExpenseJob::dispatch( Store::current(), $event->dashboardDay )->delay( $event->date )
        );
```
perhaps a solution is
```
        /**
         * Will dispatch event for refreshing expenses
         * for a specific date
         */
        $event->listen(
            ExpenseBeforeRefreshEvent::class,
            fn( $event ) => StoreRefreshExpenseJob::dispatch( Store::current(), $event->dashboardDay, $event->date->endOfDay()->toDateTimeString() )->delay( $event->date )
        );
```

**Comment by Blair2004** [comment]
Thanks, i'll be checking this.

**Comment by Blair2004** [comment]
Fixed with MultiStore 4.6.9

**Comment by m2fik** [comment]
I see  only Last Version : v4.6.7 in Download fro your site "my.nexopos.com" where is the last version?

**Comment by Blair2004** [comment]
You can download the last version here on GitHub. Check the releases section.
