### ISSUE TITLE
[Issue] Unable to add the product

### ISSUE THREAD

**Issue by m2fik** [Blair2004/NexoPOS-4x#497]
**Describe the bug**
Unable to add the product, there is not enough stock. Remaining 0

**To Reproduce**
1. fresh install NexoPOS 4.6.9
2. add unit group, unit, product-category, product with Dematerialized type
3. go to POS
4. add product with price from type Dematerialized
5. get error  Unable to add the product, there is not enough stock. Remaining 0

**Screenshots**
![err1_1](https://user-images.githubusercontent.com/36846249/149398883-ce17b9c1-d0a0-48ca-b3bc-4283f3dac4c3.jpg)

**Environment:**
 - NexoPOS 4.6.9
 - Premium Extensions: no

**Comment by Blair2004** [comment]
If the stock management is enabled for the product, you'll need to provide an stock before making a sale.
- [How To create a product](https://my.nexopos.com/en/documentation/components/products)
- [How to create a procurement](https://my.nexopos.com/en/documentation/components/procurements)

**Comment by m2fik** [comment]
What is Dematerialized type and Materialized type ? 
Before I enabled NS_WILDCARD_ENABLED I can add Dematerialized type without quantity like services or?

**Comment by m2fik** [comment]
sorry for that I make a mistake that I didn't disable Stock Management.
and Thanks.
