### ISSUE TITLE
[Issue] Can't upload Gastro 

### ISSUE THREAD

**Issue by muhammedsefer** [Blair2004/NexoPOS-4x#499]
can't upload gastro I'm getting this again and again 
<img width="1295" alt="Screen Shot 2022-01-14 at 2 52 00 AM" src="https://user-images.githubusercontent.com/38529967/149427428-4e75bf9e-6ead-4810-ac0c-ac3e216219d7.png">

**Comment by Blair2004** [comment]
While creating this issue you have not used the default template provided. This issue is therefore invalid. Make sure to create a new one by using the default template provided.
