### ISSUE TITLE
[Issue] can't add products 

### ISSUE THREAD

**Issue by muhammedsefer** [Blair2004/NexoPOS-4x#500]
I'm getting this error while trying to add new product 

The stream or file "/var/www/html/*********/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

**Comment by Blair2004** [comment]
Make sure the user executing php can write on that file. You can execute the following command from NexoPOS root : 

`
sudo chown www-data . -R
`

Assuming "www-data" is the use who runs php (you can quickly whoami on the public/index.php if you're not sure).

**Comment by Blair2004** [comment]
What's the status so far ?

**Comment by muhammedsefer** [comment]
its not getting access to root

**Comment by Blair2004** [comment]
The issue is caused by the lack of permissions on installation. This should be considered as a fix : https://github.com/Blair2004/NexoPOS-4x/issues/500#issuecomment-1012795387
