### ISSUE TITLE
[Issue] I can't see the kitchens created

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#504]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
1. create a kitchen
2. Enter kitchens to choose one
3. See error, no kitchen created appears

**Expected behavior**
Select the available kitchens to see the orders sent

**Screenshots**
![Captura de Pantalla 2022-01-14 a la(s) 23 47 40](https://user-images.githubusercontent.com/80654041/149606180-b2ec591f-ab7f-4bee-9a08-e2cbcf0e58d5.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.10]
 - Premium Extensions: [e.g Multistore (4.6.7), Gastro (4.6.2)]

**Comment by Blair2004** [comment]
Share your system credentials privately at contact@nexopos.com we'll connect.
Also mention your my.nexopos.com username.

**Comment by Blair2004** [comment]
Are you using the sub domains as the way  for accessing sub stores ?

**Comment by ahorasoyfelipe** [comment]
Yes, subdomain

**Comment by Blair2004** [comment]
Fixed with Gastro 4.6.3
Fixed with MultiStore 4.6.9
