### ISSUE TITLE
[Issue] You cannot pay or send products to the kitchen

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#505]
**Describe the bug**
You cannot pay or send products to the kitchen

**To Reproduce**
1. Select product
2. Click on Send to kitchen
3. See error: Too few arguments to function Modules\NsMultiStore\Jobs\StoreRefreshExpenseJob::__construct(), 2 passed in /home/openone2/pos.openone.cl/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 17 and exactly 3 expected

**Expected behavior**
Send the products to the kitchen

**Screenshots**
![Captura de Pantalla 2022-01-14 a la(s) 23 51 31](https://user-images.githubusercontent.com/80654041/149606305-ac84aa84-d1b2-47a1-ae59-a02a867c8f6e.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.10]
 - Premium Extensions: [e.g multistore (4.6.7), Gastro (4.6.2)]

**Comment by Blair2004** [comment]
Please get in touch privately so that we can check what's going on. We're not able to reproduce from our end.

**Comment by ahorasoyfelipe** [comment]
E-mail send

**Comment by Blair2004** [comment]
After further verification, the issue can be reproduced. We're working on a fix.

**Comment by Blair2004** [comment]
Fixed with Multistore 4.6.9
Fixed with NexoPOS 4.6.11
