### ISSUE TITLE
[Issue] Ready meals didn't show any ready meals, no sound notifications too

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#507]
After pressing ready button on kitchen screen "Ready meals" didn't show any ready meals
there is no sound notifications too
**To Reproduce**
1. Go to 'ready meals icon'

![Screenshot 9](https://user-images.githubusercontent.com/22215705/149623212-e7df1495-d82b-4b20-8159-116b374e122c.png)
![Screenshot 10](https://user-images.githubusercontent.com/22215705/149623239-197329b3-d58b-4e59-b8fb-2271569f8552.png)
![ready](https://user-images.githubusercontent.com/22215705/149623207-259bbdb5-f194-4635-8fd3-82785608d533.png)

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.10
 - Premium Extensions: Gastro (4.6.2)]

**Comment by Blair2004** [comment]
There might be an asynchrounous issue. Let us know your system credentials at contact@nexopos.com (or via WhatsApp) along with your username on my.nexopos.com.

Kind regards.

**Comment by boudo2017** [comment]
Hi, is it fixed?
I can't see any modifications

**Comment by Blair2004** [comment]
The fix deployed will make sure ready meals appear while using the multi store module. Regarding the sound notification that will be added also for the upcoming Gastro release.

**Comment by boudo2017** [comment]
"The fix deployed will make sure ready meals appear while using the multi store module"
not clear , why I have to use multi-store module?

**Comment by boudo2017** [comment]
It should be work for a single store ,single restaurant with 1 or more kitchens, there is no relations between meals and stores

**Comment by boudo2017** [comment]
How it works ,please?
cashier /admin->ready meals status -show status
chef-> notify
waiter-->notified
what means "Ready meals"?

**Comment by boudo2017** [comment]
Hi, any update about this bug.
I should work with the single store and multiple kitchens
