### ISSUE TITLE
[Issue] unable to make payment

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#509]
I tried to pay for orders but I got this errors:

**To Reproduce**
1. Go to 'open any order'
2. Click on 'pay'
3. See error

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.10
 - Premium Extensions: Gastro (4.6
![error](https://user-images.githubusercontent.com/22215705/149624065-21523949-ef51-4387-a371-230a6e6df183.png)
![payment](https://user-images.githubusercontent.com/22215705/149624067-f89b061e-aaa4-4360-acfc-f2a36b6dbb58.png)
![try to pay](https://user-images.githubusercontent.com/22215705/149624068-d84f6357-4a06-4ed5-a2b0-6e31037e1522.png)
.2)

**Comment by Blair2004** [comment]
We might need to rebuild your project. Please send the credentials to contact@nexopos.com

**Comment by boudo2017** [comment]
Documentation , please
How can I rebuilt it

**Comment by Blair2004** [comment]
Are you still experiencing this issue ?

**Comment by boudo2017** [comment]
No
