### ISSUE TITLE
[Issue] Error when reset data [MultipleStore]

### ISSUE THREAD

**Issue by jagokasir** [Blair2004/NexoPOS-4x#510]
**PLEASE CHECK THIS VIDEO**

POS 4.6.10
https://user-images.githubusercontent.com/68942105/149628142-c8e5397b-9f64-4da0-babb-df86b988a63f.mp4

**PLEASE CHECK THIS ISSUE**

POS 4.6.8
https://github.com/Blair2004/NexoPOS-4x/issues/474

**Comment by Blair2004** [comment]
Hi, please note that your issue should be formatted as here #501. We believe subsequent issue report will be well formatted.
Thank you for your understanding.

We'll be proeceding the issue based on the video.

Kind Regards.

**Comment by Blair2004** [comment]
Make sure all your modules are updated. It seems like there is a mismatch.

**Comment by jagokasir** [comment]
> Hi, please note that your issue should be formatted as here #501. We believe subsequent issue report will be well formatted. Thank you for your understanding.
> 
> We'll be proeceding the issue based on the video.
> 
> Kind Regards.

Noted

**Comment by Blair2004** [comment]
We believe the issue is caused by a mismatch with some modules. The issue doesn't include all premium module and their issue, as it's lacking those details, we cannot reproduce.
