### ISSUE TITLE
[Issue] I can't see products on pos screen

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#511]
I created a category called : chicken as parent  and subcategory called BBq
I added a product called : half chicken bbq under bbq subcategory (even I make it with sub-category)
when I tried to sell it , I can't find it on pos screen but when using search method by name I can add it to sell

**To Reproduce**
1. Go to 'pos screen'
2. Click on 'chicken category then bbq subcategory'

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.10
 - Premium Extensions: Gastro (4.6.2
![bbq1](https://user-images.githubusercontent.com/22215705/149633631-9cb24075-4932-4627-8a5f-95f2d51172e1.png)
![Screenshot 41](https://user-images.githubusercontent.com/22215705/149633675-0cdc8d1c-5909-471e-9f78-bff14ac16e4a.png)

![bbq](https://user-images.githubusercontent.com/22215705/149633632-8bae3c14-100b-4930-9ea6-d3634c6956a4.png)
)
![searcvh](https://user-images.githubusercontent.com/22215705/149633979-dee905aa-d8e4-471e-a1e9-6800eab41aff.png)

**Comment by Blair2004** [comment]
There are various reason a product cannot appear. [This help you to find out what can be the reason](https://my.nexopos.com/en/documentation/how-tos/how-to-fix-the-products-not-appearing-for-sale-on-nexopos-4-x)
