### ISSUE TITLE
Add feature : sort payement gateway

### ISSUE THREAD

**Issue by hogsim** [Blair2004/NexoPOS-4x#526]
Hi, 

Can you add the possibility to sort the payments gateway? 
 As we will mainly use customer account. It would be best if we could choose that one as default. 
<img width="1886" alt="Screenshot 2022-01-21 at 15 48 47" src="https://user-images.githubusercontent.com/5645306/150547690-5472cb81-7462-45d1-9f9a-77038c26b3c9.png">

Thanks

**Comment by Blair2004** [comment]
Hi,
Approved.
Thank you.
