### ISSUE TITLE
Add feature : Remove order type screen if there is only 1 choice

### ISSUE THREAD

**Issue by hogsim** [Blair2004/NexoPOS-4x#527]
Hi, 

Would it be possible to remove that screen if there is only 1 choice available: 

![image](https://user-images.githubusercontent.com/5645306/150548456-69c279f9-9116-4276-a881-9722b96c38b4.png)

**Comment by Blair2004** [comment]
Hi,
Totally approved. This was yet scheduled for 4.7.x

Thank you.
