### ISSUE TITLE
Add feature : Select customer screen choose which amount to show

### ISSUE THREAD

**Issue by hogsim** [Blair2004/NexoPOS-4x#529]
Hi, 

Can you add an option to change the amount shown on the customer list on the POS from total purchases to account amount available. 

<img width="478" alt="Screenshot 2022-01-21 at 16 32 08" src="https://user-images.githubusercontent.com/5645306/150554616-22737089-fd4d-45e0-bfcb-fed8781fc829.png">

<img width="1158" alt="Screenshot 2022-01-21 at 16 33 44" src="https://user-images.githubusercontent.com/5645306/150554796-2fb2501d-40ba-4598-8180-75ba49bc0474.png">

**Comment by Blair2004** [comment]
Hi,

Thank you for sharing your ideas with us. Unfortunately, what you're asking is society to your only needs and doesn't apply globally. 

We are likely to merge changes that are useful for all the users. Ar the moment we don't believe this is a general need. We therefore suggest you creating a fork of the current repo for bringing the change you want.

Kind Regards.
