### ISSUE TITLE
Ajout de nouvelles fonctionnalités

### ISSUE THREAD

**Issue by ismaeladarka** [Blair2004/NexoPOS-4x#532]
Salut l'équipe
merci pour ce bon travail que vous faites.

j'ai deux suggestions par-rapport à la nouvelle version:
1. afficher la quantité du produits restants directement sur le POS (comme sur la version NexoPos 3X)
2. afficher la quantité du produits restants directement sur la liste de produits (comme sur la version NexoPos 3X)

Prière de vérifier les pièces jointe pour plus de détails : 

![produits et quantité 2_Plan de travail 1](https://user-images.githubusercontent.com/44901185/150645456-83ebf02e-0413-40e2-af9f-5c6cec1624bc.png)
![produits et quantité_Plan de travail 1](https://user-images.githubusercontent.com/44901185/150645459-725c6c1e-582a-4287-a536-9cc4e7b04f35.png)

Merci.

**Comment by Blair2004** [comment]
Bonsoir,
Merci de prendre la peine de partager vos avis. Bien que ce soit une bonne idée il faut qu'on rappelle les difficultés que nous pouvons rencontrer avec cette amélioration. 

Dans un premier temps, il faut savoir qu'un produit peut avoir plus d'une unité de mesure et donc plusieurs. Quantité différentes. Il faudrai donc qu'on soit en quelque sorte en mesure de définir des unité principal afin de voir comment utiliser cela dans les différentes interfaces. Mais cette intégration est delication quoi que bonne. Je vais soumettre à appréciation. Afin que d'autre membre de la communauté valide votre idée, vous devez rédiger la suggestion en anglais.

Cordialement.

**Comment by ismaeladarka** [comment]
Bonsoir,
Merci pour la réponse rapide, nous apprécions effectivement les efforts que vous faites pour faire de ce produit un des meilleurs et stable sur la marché, 

Je ne sais pas comment vous faites pour afficher la quantité dans **INVENTAIRE -> PRODUITS -> OPTIONS ->VOIR LES QUQANTITES** (pièce jointe ci-dessous)

![Capture](https://user-images.githubusercontent.com/44901185/150650059-eb8c582a-96bd-4d6d-9681-2c5686fb8e19.PNG)

si vous pouvez faire que ça affiche directement sur le tableau de bord sans suivre ces étapes ça serait bien.


![produits et quantité_Plan de travail 1](https://user-images.githubusercontent.com/44901185/150650120-e1c0ee74-df2f-4270-a471-de33d9f0945d.png)


je vais réouvrir ma suggestion en anglais, et attendre la décision finale.
je vous remercie.
