### ISSUE TITLE
[Issue] Nexopos can't run workers

### ISSUE THREAD

**Issue by zedreez** [Blair2004/NexoPOS-4x#542]
**Describe the bug**
I've set up supervisor following the documentation properly, but when I test the workers I got notification from nexopos saying that workers has been enabled but nexopos can't run workers. I can confirm the workers are running on my server using the user www-data

**To Reproduce**
1. Build nexopos from github
2. Set up supervisor
3. Setup nexopos
4. test workers on nexopos admin panel

**Expected behavior**
No notification telling my supervisor not configured properly so I can use the accounting feature

**Screenshots**
![image](https://user-images.githubusercontent.com/40015425/151307683-f3f40600-3b00-4e5a-839c-7545dd9d30b5.png)
![image](https://user-images.githubusercontent.com/40015425/151340535-e7060e79-490a-4fe5-aa70-22ea40bec4fc.png)
![image](https://user-images.githubusercontent.com/40015425/151340636-f733a52f-18bc-4d06-9b01-475290c2fb23.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.10
 - Nginx
 - Debian buster

**Comment by Blair2004** [comment]
Hi, thank you for reaching out.  Can you share the output of the worker.log file ?
Have you tried to delete the notification and refreshed the page ?

**Comment by zedreez** [comment]
![image](https://user-images.githubusercontent.com/40015425/151538576-f77f050d-b91f-41a5-9d38-10a4b03a0f3a.png)
After deleting the notification the refreshing the page it didn't show up again. But the report in dashboard is still wrong. I think it becasue the worker problem. I create order on pos then click void but it recorded in dashboard.
![image](https://user-images.githubusercontent.com/40015425/151538954-f5624144-0460-4aa6-b6af-c5403ebe0ef7.png)
![image](https://user-images.githubusercontent.com/40015425/151538986-024aef26-a2fe-443e-b83a-f90b18103643.png)

**Comment by Blair2004** [comment]
You can run : `php artisan ns:report --compute --from=2022/01/30` where you replace to the day from which you want to refresh the report. Note you might run `composer update ` as it seems a package (included on laravel) cannot find a file.

Let us know how it goes.

**Comment by zedreez** [comment]
I think my worker.log I mentioned above is wrong. 
I tried to remove the content on the log file, then test the worker again the notification still apearing, but my worker.log is empty. I think the log above is because the wrong file permission I use when trying to fix my problem by myself before.

And should I run the command you mentioned everytime I get the wrong report? Like when I delete order I should run the above command to refresh my dashboard?

**Comment by Blair2004** [comment]
Consider sharing an output of your log here or if it has sensitive informations at contact@nexopos.com

**Comment by zedreez** [comment]
can you tell me which log do you need?

**Comment by Blair2004** [comment]
I was aiming the worker.log indead. Either way let us know your server details at the address mentionned above, please also by email share your username as registered on my.nexopos.com.

**Comment by Blair2004** [comment]
Any update ?

**Comment by zedreez** [comment]
sent.

**Comment by Blair2004** [comment]
Close due to inactivity via Email.
