### ISSUE TITLE
[Issue] Error on installing multistore module nexopos 4.6.11

### ISSUE THREAD

**Issue by ardhy-w** [Blair2004/NexoPOS-4x#546]
I have error on installing multistore module in nexopos 4.6.11
It makes me cannot use nexopos.
I use php 7.4 and Nginx as webserver.
It shows error : Undefined index:extension
<img width="616" alt="Screen Shot 2022-01-30 at 15 53 06" src="https://user-images.githubusercontent.com/10648963/152199402-df05e9af-86cf-4191-9567-d455c9e1b26d.png">

**Comment by Blair2004** [comment]
What version of thee Multistore are you using ?

**Comment by ardhy-w** [comment]
> What version of thee Multistore are you using ?

i use 4.6.9

**Comment by Blair2004** [comment]
Using NexoPOS 4.6.11 + Mutli Store module 4.6.9 we're not able to reproduce the issue. We need to have a look at your setup please contact us privately on WhatsApp +one (628) eight00-77five0

**Comment by ardhy-w** [comment]
> Using NexoPOS 4.6.11 + Mutli Store module 4.6.9 we're not able to reproduce the issue. We need to have a look at your setup please contact us privately on WhatsApp +one (628) eight00-77five0

i was contact on whatsapp, but seems no reply..please help

**Comment by Blair2004** [comment]
Hi, usually the team is not available during the weekend. Please expect an answer today.

**Comment by ardhy-w** [comment]
Thanks a lot this feature is now can be use
