### ISSUE TITLE
Sales by Payment type always getting zero value

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#547]
![sales by payment type always getting zero value](https://user-images.githubusercontent.com/87772530/152657823-7ea5d1db-3b3e-44b7-b70d-da1c9766790a.png)

NexoPOS 4.6.11
My NexoPOS  v4.6.2
Gastro 4x - Restaurant Extension  v4.6.2
NPS Adapter v4.6.2

**Comment by Blair2004** [comment]
Thanks for reporting this.
The review started.

**Comment by Blair2004** [comment]
We weren't able to reproduce this here (using the latest version of NexoPOS 4.6.11 https://v4.nexopos.com/dashboard/reports/payment-types).

Please contact us privately so that we can check your system (Monday - Friday from 9am to 6pm).

**Comment by magedfathi** [comment]
Dear Blair,
it seems i didn't choose the date to. it is working now. also the time filter is working with this report
