### ISSUE TITLE
Account arrangement feature request

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#550]
the default account for cash register's open balance  and sales is >>  Cash Register Cash In
so we cant identify the cash register's open balance  and sales so i had added new account >> Sales and edit the setting for Sale Cash Flow Account but in the cash flow report it is shown the last account and it should be the first one so is there option to sort the accounts.

![sort account list](https://user-images.githubusercontent.com/87772530/152658614-19697a1d-1cd5-4f6d-9b65-1e4f3f018b4a.png)

**Comment by Blair2004** [comment]
You can set a number on the "account" field and sort using that column.
