### ISSUE TITLE
[Issue] payment modal not showing and total value are wrong

### ISSUE THREAD

**Issue by zedreez** [Blair2004/NexoPOS-4x#556]
**Describe the bug**
Payment modal not showing after adding quick product then hold the order. It just blurring the page but the modal didn't show.
And when opening the hold order with quick product in it, the order list didn't show anything but the price are right, but after adding the product again the total price is calculated from 0.
I can confirm this bug exist too on your demo site.

**To Reproduce**
1. Add quick product to an order on POS
2. Hold the order
3. Open the hold order
4. Click pay
5. Reload the page
6. Open the hold order again
7. see the total value
8. add another product from list to the order
9. see the total value again

**Expected behavior**
Quick Product should calculated as expected

**Environment:**
 - NexoPOS 4.x vesrion: 4.6.11

**Comment by nexopos** [comment]
Thank you for that well-formatted issue.

**Comment by Blair2004** [comment]
Should be fixed with 4.6.12.
Reopen if it's not the case.
