### ISSUE TITLE
[Issue] Forbid resource Deletion If It's a Dependency

### ISSUE THREAD

**Issue by Blair2004** [Blair2004/NexoPOS-4x#557]
**Describe the bug**
We should implement a dependency check for resources that are shared accross the system. For example : 
- we cannot delete a product if that product is included on an order. 
- We cannot delete a customer if that customer has been assigned to an order. 
- We cannot delete a user if he has created resources (customer, order, product, etc).
- 
**Environment:**
 - NexoPOS 4.x version: 4.7.0

**Comment by boudo2017** [comment]
Delete products improvements #514
that what I am talking about

**Comment by Blair2004** [comment]
Yes after some test, we realized that we cannot delete an order which product is deleted. So from 4.7.x we'll add a restriction that prevent any deletion for resources that are in use.

**Comment by magedfathi** [comment]
we should be able to deactivate them (inactive product "will not be shown in POS with separate report inactive products or filter in the product list" + inactive user which means we can see all his previous transactions but cant login to the system anymore.

**Comment by Blair2004** [comment]
No sure to completely understand.

**Comment by magedfathi** [comment]
inactive user
inactive product
