### ISSUE TITLE
Option to enable / disable printing of receipt after accepting payment when using NPS as Printing Gateway

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#562]
**Describe the bug**
You will notice that when using Nexo Print Server as the printing gateway every time you accept payment a receipt is automatically printed in some cases we do not require a printed receipt even most customers do not ask for the printed receipt, this is because when paying the customer had a bill which should how much to pay, therefore printing every receipt is wasting a lot of paper, we would like an option to enable or disable this feature.   

**To Reproduce**
set NPS as the Printing gateway

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.11 
 - Premium Extensions:  Nexo Print Adapter (4.6.2), Gastro (4.6.2)

**Comment by kabugi** [comment]
In most cases here, a customer pays using the customer bill and doesn't
request for the receipt after payment is made
If we can get that enable/disable print receipt we will be sorted and save
on paper

Regards

**Comment by nexopos** [comment]
Hi, sorry definitely not a feature we can merge at the moment.
