### ISSUE TITLE
Gastro 4x restaurant extension

### ISSUE THREAD

**Issue by odrf** [Blair2004/NexoPOS-4x#563]
I have the gastro 4x restaurant extension, but when I activate it and send an order to a kitchen I get the error: Undefined property: App\Events\OrderProductAfterComputedEvent::$net_discount

**Comment by Blair2004** [comment]
Hi, while creating an issue, it will be more easy for us to understand your environment if you do not delete the default template. Please see #501 if you want to learn how to create an issue.

Can you meanwhile let us know : 
- What is your NexoPOS version
- What is your Gastro version
- Is that hosted online or locally

Thank you.

**Comment by Blair2004** [comment]
Closed for inactivity.
