### ISSUE TITLE
Cash Register balance not accurate

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#573]
**Describe the bug**
Cash Register balance not accurate

**To Reproduce**
create a new register
open the register
input any amount to open the register
make a sale
submit payment
check the balance of the register
it will show amount you input to open the register + the paid amount

**Expected behavior**
The balance is wrong because it does not check if the amount paid has change, the balance is wrong when there is change, the balance is wrong because it assumes there is no change.

Secondly when you check the register history for that particular register, the sale value is wrong when amount paid has change

Thirdly i cannot input any other amount when closing the register apart from the balance, the user should be able to input the amount seen physically which will not always tally with the system, the system will them report a short or excess. 

**Screenshots**

**Environment:** Demo
 - NexoPOS 4.6.12
![register1](https://user-images.githubusercontent.com/13999977/153942076-7b81da12-9785-41e7-8de0-858556d1c01a.png)
![register2](https://user-images.githubusercontent.com/13999977/153942094-741260b3-a5f5-4a6a-b298-84deaf87938c.png)
![register3](https://user-images.githubusercontent.com/13999977/153942116-5c263506-a180-4924-8f30-7c9daae05843.png)
![register4](https://user-images.githubusercontent.com/13999977/153942130-3e5c5ec5-29d6-4d79-b097-88bba0ef0c16.png)
![register5](https://user-images.githubusercontent.com/13999977/153942145-95a96f40-214c-4fc1-9d59-15ce6034af30.png)
![register6](https://user-images.githubusercontent.com/13999977/153942804-aa1dded5-a6e0-441e-8eca-bc1588278bb1.png)
![register7](https://user-images.githubusercontent.com/13999977/153942823-b95c0e84-6087-409e-a600-3dbfb07e1ef6.png)

**Comment by Blair2004** [comment]
Thank you
