### ISSUE TITLE
order list to show total sum of the rows listed for the column Total

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#574]
**Describe the bug**
We would like to show the total sum of the column Total, this is especially useful when we have filtered a particular user and we want to know the total sales of that user, we could also in future have a report showing all sales for a particular user in a given period.

**Screenshots**
![Order list sum total](https://user-images.githubusercontent.com/13999977/153946039-2af22bba-5e6f-4b69-a41c-74ca421b6069.png)

**Environment:** Demo
 - NexoPOS 4.6.12

**Comment by Blair2004** [comment]
Hi, 
Thank for this.
Unfortunately, we cannot show a total there since it's a paginated table. I rather like the idea of a report instead.
Awaiting another thread with a detailed report we can implement.

Thank you.
