### ISSUE TITLE
Nexo Print Server Support for two printers (Kitchen Printer, Cashier Printer)

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#576]
**Describe the bug**
I have faced this issue several times so i will try to be very simple.
A restaurant with a kitchen printer and a cashier printer, the order and bill gets printed to the kitchen printer correctly, when the customer pays the receipt gets printed in the kitchen printer, this is wrong. How do we separate receipts to be printed in the cashier printer? Right now we cannot use two printers  with NPS only one will work.

**To Reproduce**
1. Get two printers
2. Assign one to print the kitchen orders
3. Assign the second to print receipts (after payment). (This feature is not available in NexoPOS)

**Expected behavior**
When customer comes to pay the receipt printed should be printed in the cashier printer not kitchen printer
I have tried using the cash register but the results are the same

**Screenshots**

**Environment:**
 - NexoPOS 4.6.11
 - Premium Extensions: Nexo Print Adapter (4.6.0), Gastro (4.6.2)

**Comment by Blair2004** [comment]
We'll review this. Does the issue occurs on NexoPOS 4.6.12?

**Comment by kabugi** [comment]
The same occurs on nexoPOS 4.6.12, check from your end.

Regards
Kabugi K

**Comment by Blair2004** [comment]
Are you sure the printer you've set for the kitchen is not the same one you've set for the sales? We never faced an issue like this before. I'll make some tests though, but it's weird.

**Comment by Blair2004** [comment]
Consider sharing a screenshot of the printer set at the kitchen and for the sales.

**Comment by nexopos** [comment]
Closed for inactivity.

**Comment by kabugi** [comment]
*I must have missed your email responses because the only email I have seen
is the last one saying the issue has been closed due to inactivity however,
let me respond.*
Are you sure the printer you've set for the kitchen is not the same one
you've set for the sales? We never faced an issue like this before. I'll
make some tests though, but it's weird.
*How do you separate kitchen printer and sales printer, I know how to set
up a kitchen printer but I have not set up a sales printer, the answer will
be yes, the kitchen printer is the same as the sales printer. *
