### ISSUE TITLE
[Issue] Tax&Simmary_ Change the tax group is not working

### ISSUE THREAD

**Issue by jintsai12** [Blair2004/NexoPOS-4x#578]
**Describe the bug**
We have created two tax group. One is with tax, the other one without tax. The Summary doesn't change while we switch the tax group. You can reference it in this video: https://www.loom.com/share/382e624850504060b5d20972f303cf9a

**To Reproduce**
1. Go to 'POS'
2. Click on 'Taxes'
3. Switch "select Tax"
4. Check if summary change
5. See error

**Expected behavior**
The tax we had created has to be changed while we switch the tax group.

**Environment:**
 - NexoPOS 4.6.12
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.2), Gastro (4.5.6)]

**Comment by Blair2004** [comment]
Hi,
That's probably a concern from our end, but the video is fixed (nothing move on the video).
Is that normal ?

**Comment by jintsai12** [comment]
> **Describe the bug** We have created two tax group. One is with tax, the other one without tax. The Summary doesn't change while we switch the tax group. You can reference it in this video: https://www.loom.com/share/382e624850504060b5d20972f303cf9a
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'POS'
> 2. Click on 'Taxes'
> 3. Switch "select Tax"
> 4. Check if summary change
> 5. See error
> 
> **Expected behavior** The tax we had created has to be changed while we switch the tax group.
> 
> **Environment:**
> 
> * NexoPOS 4.6.12
> * Premium Extensions: [e.g Nexo Print Adapter (4.5.2), Gastro (4.5.6)]

**Comment by jintsai12** [comment]
I have updated a new video for your reference

**Comment by Blair2004** [comment]
Thank, we'll try to reproduce the steps.

**Comment by nexopos** [comment]
We're processing this error.
