### ISSUE TITLE
 The receipt sent to kitchen doesn't display "dine in", "pick up", and "deliver"

### ISSUE THREAD

**Issue by jintsai12** [Blair2004/NexoPOS-4x#581]
**Describe the bug**
 The receipt sent to kitchen doesn't display "dine in", "pick up", and "deliver"

**To Reproduce**
1. To kitchen (Using Nexo server printer)
2. The kitchen receipt doesn't display "dine in", "pick up", and "deliver"

**Expected behavior**
Should display on the receipt so the chef knows the meal is for take away or dine in

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.12]
 - Premium Extensions: [e.g Nexo Print Adapter (4.6.2), Gastro (4.6.6)]

**Comment by jintsai12** [comment]
HI! Any updates on this?

**Comment by Blair2004** [comment]
Hi, thank you for reminding this. We'll process this from monday.
