### ISSUE TITLE
NPS Adapter 4.7.1 not working on NexoPOS 4.6.12

### ISSUE THREAD

**Issue by kabugi** [Blair2004/NexoPOS-4x#582]
![nps adaper v4 7 1](https://user-images.githubusercontent.com/13999977/155885741-6d5ffc5b-4535-4238-b28e-8c3ad517a568.png)
**Describe the bug**
NPS Adapter 4.7.1 not working on NexoPOS 4.6.12 and when you try to go back to NPS Adapter 4.6.0 it gives the same error, looks like you cannot downgrade or go back to the previous version

**Environment:**
 - NexoPOS 4.6.12
 - Premium Extensions: [e.g Nexo Print Adapter 4.7.1

**Comment by Blair2004** [comment]
Hi you can download an old update on your download. 

![Screenshot_20220227-160048.png](https://user-images.githubusercontent.com/5265663/155887659-17204428-9b5a-4fb9-89e3-9432ee9fc1b4.png)

Now to downgrade.. make sure to change the actual version (modules/NsPrintAdapter/config.xml) of the module to let's say 1.0.0 and upload the old version.

**Comment by nexopos** [comment]
Solution posted above.
