### ISSUE TITLE
Gastro - critical option -> Add a Tips.

### ISSUE THREAD

**Issue by jintsai12** [Blair2004/NexoPOS-4x#585]
**Describe the critical option for Gastro**
If you are a restaurant, most of the country receive tips. It is very important options to run a restaurant.

**To Reproduce**
1. Add "Create Tips" in the sidemenu of "restaurant"
2. Click "Create Tips"
3. You can add the Tips percentage and indicate different tips to the order types ,such as Dine in/ Take away/ Delivery (In general only dine in receive tips)

**Expected behavior**
When the restaurant choose the order type, the Tips will be automatically applied. For example, when you choose "dine in" the tips is 10%. On the other hand when you choose "take away", the tips is 0%

**Comment by Blair2004** [comment]
Probably, you might be interested using the Commission Module ? Is that a tip for the cashier ? : https://my.nexopos.com/en/marketplace/item/sales-commissions

**Comment by Blair2004** [comment]
Closed for inactivity.
