### ISSUE TITLE
CashFlow Report Running Balance - Suggestion

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#587]
**Describe the bug**
The cashflow report is like a bank statement with money in  vs money out, we therefore need to have a running balance showing the difference between money in and money out (Credit - Debit)

**To Reproduce**
Cashflow report

**Screenshots**
![Cashflow report](https://user-images.githubusercontent.com/13999977/156617918-a4a9e83c-35cd-454b-9754-0f7771d1a7a6.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.13]

**Comment by Blair2004** [comment]
Vote needed for this one.
Thanks for the suggestion.

**Comment by Blair2004** [comment]
The column balance won't be added, but the balance as the last row, is added.
![image](https://user-images.githubusercontent.com/5265663/159886720-1ddd5db7-d32c-422e-818b-12a21270e012.png)

**Comment by mbugikp** [comment]
Thank you

Regards,
Mbugikp
