### ISSUE TITLE
[Issue] problem creating a new store

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#597]
**Describe the bug**
problem creating a new store

**To Reproduce**
1. Go to create new store

**Expected behavior**
The new store should be created

**Screenshots**
![Captura de pantalla 2022-03-11 a las 18 57 24](https://user-images.githubusercontent.com/80654041/157976122-15d1af0b-d4c3-44fa-bab8-4873a12ffdaf.png)

![Captura de pantalla 2022-03-11 a las 18 55 21](https://user-images.githubusercontent.com/80654041/157976136-85b1992b-08e5-48f2-9bd1-5976a0ae2467.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.15]
 - Premium Extensions: MultiStore 4.6.10, Gastro 4x 4.6.6

**Comment by Blair2004** [comment]
Thank you for reporting, we'll test this scenario.

**Comment by Blair2004** [comment]
Can you share a screenshot of your roles table ?

**Comment by Blair2004** [comment]
closed for inactivity
