### ISSUE TITLE
[Issue] pin login not working with multistore extension

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#598]
**Describe the bug**
pin login not working with multistore extension

**To Reproduce**
when creating a user with multistore and subdomain by store (wildcard), the entry does not work

**Expected behavior**
enter the store via pin

**Screenshots**
![Captura de pantalla 2022-03-11 a las 19 02 26](https://user-images.githubusercontent.com/80654041/157976971-2bc4465e-d227-49e1-895c-0c87e9dfaf3d.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.6.15]
 - Premium Extensions: NexoPOS MultiStore 4.6.10, Pin Login 4.6.0

**Comment by Blair2004** [comment]
Thank you for reporting.

**Comment by girijamohanty** [comment]
**CSRF token mismatch issue**
 login not working CSRF token mismatch

To Reproduce
Steps to reproduce the behavior:
at register or login getting CSRF token mismatch

![image](https://user-images.githubusercontent.com/3896976/164968826-f61404e1-c200-4a54-87f4-3d85cd179b73.png)

**Comment by Blair2004** [comment]
Hi, consider checking this https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-csrf-token-mismatch-on-nexopos-4-x @girijamohanty

**Comment by girijamohanty** [comment]
Thank you very much for quick reply and i am able to access without issue

**Comment by Blair2004** [comment]
Fixed with recent update
