### ISSUE TITLE
Demo Dashboard Sign In Not Working

### ISSUE THREAD

**Issue by moedayraki** [Blair2004/NexoPOS-4x#605]
https://v4.nexopos.com/sign-in
The username: admin 
       password: 123456

is not working

**Comment by Blair2004** [comment]
The demo provide a full access to the application. So sometimes people change the password. But twice daily the system reset to default.

**Comment by Blair2004** [comment]
I'll reset the demo.

**Comment by moedayraki** [comment]
Perfect. Thanks!

**Comment by Blair2004** [comment]
Hi, the demo has been reinitialized, have you had any chance to test it ?

**Comment by moedayraki** [comment]
Yup! I've tested it and it working! Thanks
