### ISSUE TITLE
Sales Report By 'user' - Feature Suggestion

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#606]
**Describe the bug**
We have several waiters, we would like to know each waiter how much was sold per day, week, month, etc
The sales report shows everything that was sold, we want to break it down to sales by user/waiter

**To Reproduce**
1. Go to '...' Reports.
2. Sales Report

**Expected behavior**
The sales report should have a feature where sales can be filtered by user/author/waiter

**Screenshots**

![Sales Report filter by user](https://user-images.githubusercontent.com/13999977/158834615-a2f5089e-8ee1-40ae-8721-36cbddf0f81d.png)

**Environment:**
 - NexoPOS 4.6.16

**Comment by Blair2004** [comment]
Approved

**Comment by Blair2004** [comment]
![image](https://user-images.githubusercontent.com/5265663/159478206-69478470-64f6-49ec-ade3-7b3e4fb5ddbb.png)
Added to v4.7.x

**Comment by mbugikp** [comment]
Thank you!

Regards
Mbugikp
