### ISSUE TITLE
You're not authenticated after local installation/login

### ISSUE THREAD

**Issue by Ippezrobert** [Blair2004/NexoPOS-4x#609]
I have setup NexoPOS-4x on the following environment
1. Windows 10 ~x64
2. Laragon 5
3. PHP 7.4.19 & MySQL Community Server 5.7.33

The content of .env remain the default as below:
```
APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=base64:feh9RZDs5XbhkwCtgkyRkSRGt2oS/Pts4LCvW7lVxO4=
APP_DEBUG=true
APP_URL=http://127.0.0.1

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos4
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
SANCTUM_STATEFUL_DOMAINS=127.0.0.1
NS_ENV=production
TELESCOPE_ENABLED=false
DB_PREFIX=ns_
NS_VERSION=4.6.16
NS_AUTHORIZATION=sp6vWYQJNGeJr3Tx4C3C
NS_SOCKET_PORT=6001
NS_SOCKET_DOMAIN=127.0.0.1
NS_SOCKET_ENABLED=false
```

I can log in using the default user account created during installation but i can not perform anything since am not authenticated. The right content (dashboard area) is empty whenever i click on an item, is there addition config i need to do to enable the features?

**Comment by Blair2004** [comment]
Hi, why don't you use the virtual domain with Laragon ? Can you provide the
URL you use for accessing the dashboard or login page ?

**Comment by Ippezrobert** [comment]
@Blair2004 when I serve the app from the terminal, it runs on the address http://localhost:8000 and that's what I use to access dashboard or login

**Comment by Blair2004** [comment]
If you're using Laragon, you don't need to "php artisan serve" as that will force you doing that all the time. Alternatively, you can use the built in server.

**Comment by Ippezrobert** [comment]
> If you're using Laragon, you don't need to "php artisan serve" as that will force you doing that all the time. Alternatively, you can use the built in server and virtual domains.
> 
> https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon

The above has help solved my problem (Moving nexopos into www folder of laragon.... But i was wondering if there was a way to save nexopos in a different drive say Drive D or folder other than the www folder of laragon and add a pointer to let laragon reference the source directory of nexopo?

**Comment by Blair2004** [comment]
Hi, there are two things you can do there.

1 - Change the www directory on Laragon so it point whereever you want. But that means all app should be on that directory.
![image](https://user-images.githubusercontent.com/5265663/159066448-a70dede7-5a5e-4397-8624-12dba34340d8.png)

2 - Create a symbolic link on www pointing to a different directory where NexoPOS is (more complicated).

**Comment by Ippezrobert** [comment]
@Blair2004, thanks.. i got it, the first one seems better. thanks and am closing this issue since it has been resolved
