### ISSUE TITLE
[Issue]  I am getting 403 forbidden error even i created .htaccess file and change the permission settings

### ISSUE THREAD

**Issue by vinotha9942** [Blair2004/NexoPOS-4x#612]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Your issue is not well formatted. Please make a better refer to this to learn how to proceed #501
