### ISSUE TITLE
Error on edit coupon

### ISSUE THREAD

**Issue by patian** [Blair2004/NexoPOS-4x#628]
After successfully create coupon, trying to edit coupon. 
but when i'm trying to save it, it give error call to member function input() on array.

even only after go in edit coupon then straight to save it, it would still failed.
![error-kupon-nexopos](https://user-images.githubusercontent.com/2491361/160537245-50457e77-cfc5-46ae-b956-f18f09cac169.jpg)

**Comment by nexopos** [comment]
Thank you for reporting. We'll take alook. 
For upcoming issues make sure to follow those instructions #501

**Comment by nexopos** [comment]
Fixed on https://github.com/Blair2004/NexoPOS-4x/releases/tag/v4.6.17
