### ISSUE TITLE
Caller Id Integration for Takeout

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#629]
When the customer calls, the customer's number is displayed on the screen thanks to the device below. When this number is clicked on restaurant software, it directs you to the customer registration screen. And the registration screen will detect the number automatically. The customer's address is entered and the customer is registered. When the customer calls again, as soon as he clicks on the number, he is directed to the customer panel and the customer is selected with his address. Can you integrate this system?

device link: https://www.gcallerid.com/

**Comment by nexopos** [comment]
Hi, 
Looks like this is specific to certain country and cannot be added to the core.
If you would like a customization, please contact the development team contact@nexopos.com

**Comment by lim10soft** [comment]
No sir, there is caller id device in every country, I guess you did not understand what I want to tell.
You connect this device to the restaurant phone, and when someone calls, the number appears directly on the screen.
please have a look at this link with the help of translation.

https://kb.sambapos.com/3-6-caller-id-kurulumu-ve-ayarlari-nasil-yapilir/

**Comment by nexopos** [comment]
The link you've shared on your first post point to a Turkish resource and therefore web believe only show relevant details for that country. Regardless, the Caller ID must be a module and cannot be merged to the core. With proper link to a solution that work globally, i'll move this to a feature suggestion category.

**Comment by lim10soft** [comment]
Of course, sir, it can be used as a module, this is a very necessary thing.
