### ISSUE TITLE
[Module add-on] Provide a solution for checkout receipt integration

### ISSUE THREAD

**Issue by jintsai12** [Blair2004/NexoPOS-4x#630]
**Describe the support**
Due to a different receipt/invoice requirement globally, can Nexo provide a solution for integration extensibility on checkout page.

**To Reproduce**
1. Checkout page
2. Extensibility, such as hooks
3. Third party Integration

**Expected behavior**
An extension on checkout page for third party integration.

**Comment by Blair2004** [comment]
This is an example of how to inject a button on the payment popup.

```js
nsHooks.addAction( 'ns-pos-payment-mounted', 'my-custom-hook', ( vueComponent ) => {
     const button = document.createElement( 'button' );
     document.querySelector( '.ns-payment-footer' ).appendChild( button );
     button.addEventListener( 'click', () => {
          const order = POS.order.getValue();
     });
});
```

**Comment by jintsai12** [comment]
Please kindly also provide us where can we cancel the order programmatically when we fail to call the API by module. So this order will be canceled due to API fail.

**Comment by Blair2004** [comment]
> Please kindly also provide us where can we cancel the order programmatically when we fail to call the API by module. So this order will be canceled due to API fail.

Hi, please open a dedicated thread for that.
