### ISSUE TITLE
[Issue] New Install v4.7.0 failed no role_id in nexopos_users table

### ISSUE THREAD

**Issue by patian** [Blair2004/NexoPOS-4x#632]
Trying install from clone github master
with this command
- git clone https://github.com/Blair2004/NexoPOS-4x.git
- composer install
- npm install
- npm run prod
- go to localhost
- configure database connection
- setup configuration

in do setup - configuration failed
it give error no role_id in table ns_nexopos_users

![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/2491361/160852572-e3f42c06-bbc8-4929-a026-3a7ecb48216b.gif)
the gif is not display properly, can see in this google drive link
https://drive.google.com/file/d/1wcnCDktRpvqWu5ZE9FcQRk2n8Kq4NKLc/view?usp=sharing

i tried twice, from clean slate. delete the original then clone again from git.

environment
- laragon-wamp version 5
- apache 2.4.47-win64-vs16
- php-8.1.4-win32-vs16-x64
- mysql-5.7.33-winx64

**Comment by Blair2004** [comment]
Hi, 
Thank you for this. We switched from a single role per user to a multiple role per user.
We'll definitely check what happened during the merging.

Thank you.

**Comment by Blair2004** [comment]
For subsequent issue reporting, make sure your issue follows the same format as here #501

**Comment by nexopos** [comment]
We're not able to reproduce it by downloading the master branch and performing an installation.

**Comment by munzir1996** [comment]
The issue can be found also in the demo version
 
![screencapture-v4-nexopos-database-update-2022-03-30-11_02_26](https://user-images.githubusercontent.com/22343486/160794295-548afb2c-71e6-43b2-8539-1b051f20a29d.png)

**Comment by nexopos** [comment]
Thank you, we'll proceed the review from there.

**Comment by Blair2004** [comment]
> The issue can also be found in the demo version
> 
> ![screencapture-v4-nexopos-database-update-2022-03-30-11_02_26](https://user-images.githubusercontent.com/22343486/160794295-548afb2c-71e6-43b2-8539-1b051f20a29d.png)

We've applied a hotfix over the current master branch. Consider testing.

https://github.com/Blair2004/NexoPOS-4x/commit/3385bde4eb6acaac10164e4245860dd12bf694a5

**Comment by nexopos** [comment]
I've tryed many deployment from the version v4.7.x i was able to successfully set up the app. While i was using Sqlite, i strongly believe the DB driver is not in cause here. Please consider providing a better way to reproduce the issue so we can proceed. The issue will be closed for now, but feel free to open a new one with better steps.
