### ISSUE TITLE
[Issue] provide a title for the issue you're facing here

### ISSUE THREAD

**Issue by munzir1996** [Blair2004/NexoPOS-4x#633]
**Describe the bug**
When changed the profile language i am getting a helper function error

**To Reproduce**
1. Go to 'profile'
2. Click on 'change the profile language to any other language instead of English'
3. Save Settings
5. Try to open the POS

**Expected behavior**
The system should work normally by opening the pos.

**Screenshots**
![screencapture-v4-nexopos-dashboard-2022-03-31-10_15_35](https://user-images.githubusercontent.com/22343486/161010188-dc25d0bb-1df2-43bc-8d6f-ca2915dc8d50.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7]
 - Demo app

**Comment by Blair2004** [comment]
Hi, thank yo for your issue. For upcoming issue, please make sure to follow the instructions [here](#501) so that we can understand your issue better.

We've applied a quick fix. Consider checking the demo.
