### ISSUE TITLE
Add Payment Option on the order list

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#634]
**Describe the bug**
On the order list there is an option button with invoice, receipt and delete if add payment is added we could use it to clear the unpaid bills faster, remember in a busy establishment not all orders are cleared, some or most are cleared when the customers are gone and its time to close the restaurant or early the following morning, adding payment option here will make the process faster.

**To Reproduce**
1. Go to orders
2. Click on orderlist
3. Click options
![Add payment Option](https://user-images.githubusercontent.com/13999977/161083047-fdcaaf33-a671-4257-a483-3462645f47de.png)

**Screenshots**

**Environment:**
 - NexoPOS 4.6.16

**Comment by Blair2004** [comment]
This is available on the options. 

Don't see a valid reason why we should decouple only the payment tab from the options. This means every tab must be listed on the options... forcing to close/open a popup if we have to switch from one option to another. While with the current implementation it's all available in a single popup.

Sorry we cannot merge this.

**Comment by mbugikp** [comment]
I don't understand, what do you mean it's already there in the options?
What is decouple?

**Comment by Blair2004** [comment]
Being able to make a payment is available while clicking on the options
menu. Decouple = separate. We can't separate only the payment feature (tab
on the options) but we should decouple/extract all.

**Comment by mbugikp** [comment]
Payment is available while clicking on the options menu? Let me check that?

Regards

**Comment by mbugikp** [comment]
I have seen it but it's not active, it cannot accept payment

**Comment by Blair2004** [comment]
It all depends on the order itself. is that already paid ? Unpaid ? Hold ?

**Comment by mbugikp** [comment]
The order is unpaid, I am using version 4.6.16. Kindly check.

Regards
Mbugikp

**Comment by Blair2004** [comment]
a screenshot might be more explicit about this. Thanks

**Comment by mbugikp** [comment]
I have used the nexopos demo 4.7.0

**Comment by mbugikp** [comment]
> a screenshot might be more explicit about this. Thanks

![Order list payment option 1](https://user-images.githubusercontent.com/13999977/164501821-94c60626-71d0-429d-930f-880aa55c243b.png)

Payment Option
![Order list payment option 2](https://user-images.githubusercontent.com/13999977/164501983-cf309f65-ff1e-4726-9da3-ce35cc5400c9.png)

**Comment by mbugikp** [comment]
Hope you still remember this issue.

Regards
Mbugikp
