### ISSUE TITLE
Can't Open demo pagee

### ISSUE THREAD

**Issue by munzir1996** [Blair2004/NexoPOS-4x#638]
**Describe the bug**
When trying to open the demo application i am getting 
Uncaught ErrorException: Attempt to read property "attribute" on null

**To Reproduce**
1. Go to (https://my.nexopos.com/en)
2. Click on Demo
3. See error

**Expected behavior**
The login page should appear to the user

**Screenshots**
![screencapture-v4-nexopos-sign-in-2022-04-01-07_44_04](https://user-images.githubusercontent.com/22343486/161202410-4b267f02-a1a5-4039-a82e-2f48703bb658.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.7

**Comment by Blair2004** [comment]
Thank you we're on it.

**Comment by Blair2004** [comment]
The issue has been resolved with https://github.com/Blair2004/NexoPOS-4x/commit/f87355dd2c9dea339954283178894140c6e410db
