### ISSUE TITLE
save email reporting settings issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#653]
Hi,
save email reporting settings issue
**To Reproduce**
1. Go to 'email reporting'
2. Click on 'save'

**Expected behavior**

**Screenshots**

**Environment:**
 NexoPOS 4.6.18
Premium Extensions: last updates with 4.6.x
![WhatsApp Image 2022-04-10 at 12 31 47 AM](https://user-images.githubusercontent.com/22215705/162593764-4908181e-8077-47a8-aca1-0eec809e2a86.jpeg)

**Comment by Blair2004** [comment]
This feature will be removed from the core add added to a premium module.
