### ISSUE TITLE
Bulk importer issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#654]
Hi,
bulk importer modules didn't work
**To Reproduce**
1. Go to 'bulk importer
![WhatsApp Image 2022-04-09 at 11 40 08 PM](https://user-images.githubusercontent.com/22215705/162593827-ce725936-fd51-46ce-971a-004e33c33dd6.jpeg)
![WhatsApp Image 2022-04-09 at 11 41 33 PM](https://user-images.githubusercontent.com/22215705/162593828-5227aca2-a34c-4351-848e-bdf45b1bd3fd.jpeg)
'

**Expected behavior**

**Screenshots**

**Environment:**
NexoPOS 4.6.18
Premium Extensions: last updates with 4.6.x

**Comment by Blair2004** [comment]
How are you proceeding to install the module ?

**Comment by boudo2017** [comment]
1-extract downloaded module to module folder
2-rename this module like in config.xml name  "<namespace>NsBulkImporter</namespace>"
3-enable it

**Comment by Blair2004** [comment]
When you install the module manually, you need to enable the symbolic link manyally :
```
php artisan modules:symlink [ModuleNamespace]
```

replace [ModuleNamespace] with the module namespace for example:

```
php artisan modules:symlink NsBulkImporter
```

**Comment by boudo2017** [comment]
fixed,
thank you
