### ISSUE TITLE
Dine in icon issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#655]
Hi,
Dine in icon issue

**To Reproduce**
1. Go to 'order type
![dinein](https://user-images.githubusercontent.com/22215705/162593857-d4c24b2a-8376-49b9-bd7b-4debab072d41.png)
'

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.18
 - Premium Extensions: 4.6.x

**Comment by Blair2004** [comment]
How have you installed the gastro moduel ?

**Comment by boudo2017** [comment]
yes, I did

**Comment by Blair2004** [comment]
How have you installed the module Gastro. Explains the steps you've been through.
Thanks.

**Comment by boudo2017** [comment]
thank you fixed
