### ISSUE TITLE
Products list issue

### ISSUE THREAD

**Issue by boudo2017** [Blair2004/NexoPOS-4x#656]
Hi,
No products can be shown from the first time ,I need to edit then refresh page
(I got  message error : permission issue )

**To Reproduce**
1. Go to 'product list'

**Expected behavior**

**Screenshots**

**Environment:**
 - NexoPOS 4.6.18
 - Premium Extensions: 4.6.x
![WhatsApp Image 2022-04-09 at 11 50 56 PM](https://user-images.githubusercontent.com/22215705/162593924-d8b7d3e8-b366-4e1a-a046-743c2979acfd.jpeg)

**Comment by Blair2004** [comment]
What server are you currently using ? Laragon ? a remote server ?

**Comment by boudo2017** [comment]
Laragon

**Comment by Blair2004** [comment]
Does the issue persist after restarting the server ?

**Comment by boudo2017** [comment]
fixed, thank you
