### ISSUE TITLE
i can't update nexopos

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#658]
hi i am using laragon i am getting error while updating nexopos to 4.7.0
![unnamed](https://user-images.githubusercontent.com/102427740/162615232-4cc20825-595f-4340-99da-154bf0536946.png)

**Comment by Blair2004** [comment]
Hi, for subsequent threads, please make sure to follow this #501 
Consider providing the following details : 
- NexoPOS version
- Envrionment (local computer or remote server)
- Where have you downloaded the update (link).
