### ISSUE TITLE
we have an issue once try install the system on localhost

### ISSUE THREAD

**Issue by ahmadnaser** [Blair2004/NexoPOS-4x#67]
Hello, thanks for sharing the system on Github, we do some testing and tried to install the system on local device using laragon we went to the installation wizard but we got the attached error.

[https://i.imgur.com/bqGGuqVl.jpg](https://i.imgur.com/bqGGuqVl.jpg)

waiting for your reply.

**Comment by Blair2004** [comment]
Hi, the screenshot seems broken.
![image](https://user-images.githubusercontent.com/5265663/94368435-e84b0300-00db-11eb-85b6-05886900b95d.png)

**Comment by ahmadnaser** [comment]
please here is a new link
https://anbilarabi.com/wp-content/uploads/2020/09/20200927_012429.jpg

**Comment by Blair2004** [comment]
Please make sure the script can write on the .env file. Make sure that file even exists.

**Comment by scalinux** [comment]
I fix this by: Reboot the system. Then edit the .env file using terminal "nano .env" verify you DB setup.

**Comment by ahmadnaser** [comment]
yes it writes but i still got the error as in image

**Comment by scalinux** [comment]
Try to "git pull" and try last update fix many of those problems.

**Comment by Blair2004** [comment]
Can you confirm that the database information is correct?

**Comment by ahmadnaser** [comment]
yes the database information is correct and the connection is established, i tried with 

> Try to "git pull" and try the last update fix many of those problems.

but did not solve the issue, I tried with the following commands

```
npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modulesfsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_moduleswatchpacknode_modulesfsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
 
audited 1172 packages in 28.178s
 
40 packages are looking for funding
  run `npm fund` for details
 
found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```


and also

```
$ npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
 
up to date in 22.686s
 
40 packages are looking for funding
  run `npm fund` for details
 
fixed 0 of 2 vulnerabilities in 1172 scanned packages
  2 vulnerabilities required manual review and could not be updated
```

did not save orl solve the issue, we still got the following error:
![https://anbilarabi.com/wp-content/uploads/2020/09/20200927_012429.jpg](https://anbilarabi.com/wp-content/uploads/2020/09/20200927_012429.jpg)

**Comment by Blair2004** [comment]
Alright, gonna give a try on Windows to this. I'm currently on Linux. I'll let you know.

**Comment by Blair2004** [comment]
Question, have you ever tried to access the app using "php artisan serve" instead of using Laragon ?

**Comment by Blair2004** [comment]
Base on the final test i had, i was able to setup this on Windows correctly. As pointed out above, the issue you're facing should be caused by a permission issue. While NexoPOS 4.x validated the database informations, it's redirect to the next step but if there is no database information on the .env file, it will redirect you back to the previous step.
