### ISSUE TITLE
[Issue] Can't Create Customer

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#682]
Does Not Accept Phone Number When Creating Customer After Updating To New Version.
![2022-04-12_14-33-07](https://user-images.githubusercontent.com/102427740/162951110-297221ef-912e-4af7-9720-d08fcba111be.png)

**Comment by Blair2004** [comment]
While creating a customer, make sure to assign them to a group.

**Comment by lim10soft** [comment]
I already know that much. I create a group and throw the customer, it does not accept the phone number.

**Comment by Blair2004** [comment]
Hi, consider downloading NexoPOS 4.7.2 as it has solved a customer validation rules.

**Comment by Blair2004** [comment]
Closed for inactivity
