### ISSUE TITLE
[Issue] Multi Store Module Error after Install

### ISSUE THREAD

**Issue by ardhy-w** [Blair2004/NexoPOS-4x#697]
**Describe the bug**
My nexopos error after installing new multistore module and enable it.

**To Reproduce**
1. Installing Multistore module 4.7.0
2. Enable module
3. Move to another page

**Expected behavior**

**Screenshots**
![error new multistore](https://user-images.githubusercontent.com/10648963/163717956-4a54b3c9-4b4a-4e01-af8d-d8e5de2410fd.png)

**Environment:**
 - NexoPOS 4.7.2
 - Premium Extensions: [e.g Nexo Multistore Module (4.7.0)]

**Comment by Blair2004** [comment]
Hi,
We have this issue reported. We're working on that.

Thank you for your patience.

**Comment by Blair2004** [comment]
Fixed with multistore v4.7.3
