### ISSUE TITLE
[Issue] barcode field is required in create product while the documentation says it can be empty

### ISSUE THREAD

**Issue by bamonadir** [Blair2004/NexoPOS-4x#699]
**Describe the bug**
barcode field is required in create product while the documentation says it can be empty.

**To Reproduce**
1. Go to Inventory->create product
2. Fill in the form field excluding barcode and click save.

**Expected behavior**
The form should be submitted and the barcode should be auto generated based on the barcode type.

**Environment:**
 - NexoPOS 4.x

**Comment by bamonadir** [comment]
Looking at the source code, I found the form configuration is fetch dynamically.
app->Crud->ProductCrud.php and comment out 'validation'    =>  'required',

**Comment by bamonadir** [comment]
Another issue raises when leaving the barcode field empty and that is that the barcode generation throws exception sometimes. I guess the issue is with using faker>randomNumber method to generate barcode value.

**Comment by Blair2004** [comment]
Hi, Thank you for your update.
We'll be checking this.
Kind Regards.
