### ISSUE TITLE
[Issue]User Problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#702]
After creating a user, it gives an error when entering the account.
![2022-04-10_20-06-03](https://user-images.githubusercontent.com/102427740/163875838-ba7f205d-d805-45a0-b451-79d4da57ce89.png)

**Comment by Blair2004** [comment]
Make sure on your .env file the value NS_ENV is set to "production".
If the issue persist run this command : 
`npm install && npm run prod`

**Comment by lim10soft** [comment]
I did what you said, but my problem still continues. I use laragon.

**Comment by Blair2004** [comment]
It seems like the source code has been changed. Consider providing a copy of this file :
resources/ts/interfaces/order-type.ts

**Comment by lim10soft** [comment]
No sir we haven't made any changes
https://drive.google.com/file/d/18fhe8ilgnOyvHkm8Cu-VwxV6WW_9xIfZ/view?usp=sharing
