### ISSUE TITLE
[Issue] mass product deletion problem printer problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#713]
it gives an error when uploading a batch product gives an error when clicking on the printers
![2022-04-21_20-31-10](https://user-images.githubusercontent.com/102427740/164517878-9f334076-9701-4391-99fb-9b2e518afe77.png)
![2022-04-21_20-31-32](https://user-images.githubusercontent.com/102427740/164517886-f8c6ab8e-1b51-488e-91b1-009166c02379.png)

**Comment by Blair2004** [comment]
Hi, please make sure to follow this post that explains how to create an issue #501.
Subsequent issue posted with a wrong format will be closed.

**Comment by Blair2004** [comment]
Also, please provide screenshot in "English" so that we can identify where you're reporting the issue.

**Comment by lim10soft** [comment]
The gentleman gives the following error in English when deleting the products in bulk.
