### ISSUE TITLE
Can't setup database with installation wizard

### ISSUE THREAD

**Issue by munzir1996** [Blair2004/NexoPOS-4x#715]
**Describe the bug**
Can't setup database.
When trying to setup the Database through the installation wizard i am getting network error

Env:
APP_NAME="NexoPOS 4.x"
APP_ENV=local
APP_KEY=*********
APP_DEBUG=true
APP_URL=http://localhost:8000

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=nexopos
DB_USERNAME=****
DB_PASSWORD=****

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_DOMAIN=127.0.0.1
SESSION_COOKIE=nexopos_session

**To Reproduce**
1. Go to localhost:8000
2. Click on Dashboard
3. fill the save database form
4. click on save database
5. Error network error 

**Expected behavior**
to continue to the next step of the installation wizard.

**Screenshots**
![Screenshot (12)](https://user-images.githubusercontent.com/22343486/164703435-1f89ca2f-d16f-47ad-9c63-fe5bff7f2d11.png)

**Environment:**
 - NexoPOS 4.x vesrion: [Download From Packagist]
 - Localhost development

**Comment by Blair2004** [comment]
Hi, We recommend you either using Laragon with the virtual domain or WSL (Windows Subsystem for Linux) in order to install NexoPOS 4.x on Windows 10. Also make sure you're using php 8.1.

**Comment by Blair2004** [comment]
This issue occurs because the buil-in server (php artisan serve) reset whenever there is a change on the .env file causing the process not to continue. Installing using the built-in server is therefore not advised.

If you still have that issue with Laragon, let us know or open a new thread.

**Comment by loryam** [comment]
I have installed  NexoPOS using Laragon, but I still get the network Error 
![network Error](https://github.com/Blair2004/NexoPOS/assets/57753484/021ae9d4-59c9-46a3-aab6-d46cf01a19ad)
Please help me get over this. Thank you
