### ISSUE TITLE
[Issue]  I'm having a problem with printing can you help me?

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#720]
HELLO WE ARE USING TURKISH LANGUAGE AFTER CONNECTING TO NEXO PRINT SERVER, THE PRINTS ARE NOT READ AND IT IS WRITTEN IN THIS WAY.
I am using the latest version of nexopos
MODULES I USE AND THEIR VERSIONS
![2022-04-24_15-33-51](https://user-images.githubusercontent.com/102427740/164977401-7475e6ba-0088-459a-b268-fe7c5992193f.png)

PRINT THE PLUG FROM THE WEB, IT WAS OUT WITHOUT PROBLEMS. NEXO PRINT SERVER PRINTS FROM NPS ADAPTOR, THE TEXTS ARE NOT READ AND THEIR CHARACTERS CHANGE.
![2cefbdf8-55b5-46a9-9f12-4fad9727c3a4](https://user-images.githubusercontent.com/102427740/164977276-d6750f75-e31f-4662-af30-59421b1aedaa.jpg)
![6d310cbd-21cc-45cb-bedd-d3c2a634d2a0](https://user-images.githubusercontent.com/102427740/164977287-ccb66fcf-fa57-4b6b-ab71-5a8a7681cc2d.jpg)
PRINTER I USE
![54518bea-3943-4ddb-8751-83db05ab9889](https://user-images.githubusercontent.com/102427740/164977321-2892db00-0c46-49de-a747-1670e7ab91bb.jpg)
![d52a6bf2-9f82-4822-b506-1ff7fba525bf](https://user-images.githubusercontent.com/102427740/164977326-c0c7cefc-5f23-4c18-9240-cb3e9a736a1b.jpg)

2.PROBLEM: AFTER SENDING THE PRODUCT TO THE KITCHEN, THE PRINTER I DEFINED ON THE KITCHEN SCREEN DOESN'T EXIT AUTOMATICALLY.

**Comment by Blair2004** [comment]
Hi, 
Thank you for this. We're about to contact you today for that.

**Comment by Blair2004** [comment]
Hi, seems the issue is related to the turkish? We'll try printing in turkish.

**Comment by lim10soft** [comment]
> Merhaba, sorun türkçe ile ilgili gibi görünüyor? Türkçe yazdırmayı deneyeceğiz.

We need the nexo print server right now and I can't use it because of this problem, I hope it will be solved, thank you, good work

**Comment by parvs08** [comment]
@lim10soft  how did you able to install it :( 
im still having a hard time to install the pos and if im able to install it i experience bugs hoping you can help me too :(

**Comment by lim10soft** [comment]
Give a remote link to ***@***.*** and I'll help.



parvs08 ***@***.***>, 29 May 2022 Paz, 04:15 tarihinde şunu
yazdı:

**Comment by lim10soft** [comment]
lim10soft@gmail.com  Give me a remote link to your address, I'll help

**Comment by lim10soft** [comment]
The problem still persists and I pay money even though I don't use it.

**Comment by Blair2004** [comment]
The issue is flagged as not supported for now. We can't guarantee turkish support for NexoPOS. Using the web printing remain a better solution.

**Comment by lim10soft** [comment]
Other software works with this logic. this problem is very important for me i can't use nexo print server please help.


![Adsız](https://user-images.githubusercontent.com/102427740/210259372-84f2c2ae-9c3c-469b-9ac8-71cd3b924456.png)

**Comment by lim10soft** [comment]
@Blair2004
