### ISSUE TITLE
[Issue] Installment Problem And Product Problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#727]
No Product Added.
![problem 1](https://user-images.githubusercontent.com/102427740/165190975-0c1f53db-c4a3-4df3-bd84-4813d1fb362e.png)

Customer installment does not work.
![PROBLEM2TAKSİT](https://user-images.githubusercontent.com/102427740/165191004-487116d7-507a-47ec-b215-884c09b470d5.png)
![PROBLEM TAKSİT](https://user-images.githubusercontent.com/102427740/165191009-7a974c45-b3b3-43e5-99ce-d9e68a3b61dd.png)
Delete button does not work when installment is selected
![2022-04-26_02-41-18](https://user-images.githubusercontent.com/102427740/165191946-ebe6f8d3-6197-462e-afaf-9eeaa4b6bc98.png)

**Comment by Blair2004** [comment]
We were only able to replicate the last screenshot. Note that every issue should have an individual thread. By working on a issue it's usually closed automatically when we've fixed that. if an thread has many issues, if one is solved it will be closed automatically.

Remember, use #501 to learn how to format your issue.
