### ISSUE TITLE
[Issue] Problem With My Hetzner Plesk Server

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#744]
Hello, I need help.

![2022-04-30_22-29-33](https://user-images.githubusercontent.com/102427740/166120003-205b56b3-d020-4634-889e-c8ff677595e9.png)
Hello, I'm buying a server from hetzner, I'm using a plesk panel, and I get this error when I connect the gastropos module.
php artisan modules:symlink NsGastro

**Comment by Blair2004** [comment]
Hi,
It seems like you have. Apermission issue. The user you're logged with on the terminal cannot edit the files on the project directory. 

You might consider changing the owner with chown:

sudo chown youruser:youruser . -R 


Within the root of the project.

**Comment by lim10soft** [comment]
yes, when you give permission, it gets fixed, but the tables and gastro add-ons on sale are not visible.

**Comment by lim10soft** [comment]
My Problem Is Solved Thank You
