### ISSUE TITLE
[Issue] Hello, when I enter the user list, I get the following error. I have role permission

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#746]
Hello, when I enter the user list, I get the following error. I have role permission
![2022-05-02_03-01-13](https://user-images.githubusercontent.com/102427740/166170144-1681bf14-8075-490d-8cc8-fc6103f0967e.png)

**Comment by Blair2004** [comment]
Hi, What role do you use ?

**Comment by lim10soft** [comment]
While installing, I use the admin role that she created, I tried other roles, but my problem did not improve.

**Comment by Blair2004** [comment]
Fixed with #4.7.6
