### ISSUE TITLE
[Issue] Adding Product Problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#761]
When adding the first product, it freezes in this way and the product is not added. When I close this place and add another product, the problem is fixed when I manually type the barcode and sku number. after that, its automatic barcode sku makes it seamless to add products. It is necessary to manually enter the barcode and sku when adding it for the first time.

![2022-05-06_16-31-43](https://user-images.githubusercontent.com/102427740/167142082-8baf060f-71a7-4f60-8a28-3a78dce3ffee.png)

2. I HAVE A SMALL REQUEST FROM YOU

FIRST, THANKS FOR THE EASE OF ADDING PRODUCTS. MOST RESTAURANTS AND MARKETS DO NOT MAKE STOCK MANAGEMENT. IT IS EASIER IF THIS AUTOMATIC IS MARKED NO WHEN ADDING PRODUCTS.
![2022-05-06_16-36-57](https://user-images.githubusercontent.com/102427740/167144440-8bb8ac2f-8b2a-41db-8a3b-7b530b1a02bb.png)

**Comment by Blair2004** [comment]
With information about the version of NexoPOS you're using, we're not able to reproduce the issue. Make sue to use #501 to see how your issue *MUST* be formatted. That will ease our work.
