### ISSUE TITLE
[Issue] AUTOMATIC RENEWAL IN TABLE MANAGEMENT

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#762]
![2022-05-06_16-49-01](https://user-images.githubusercontent.com/102427740/167146226-69d1c0dd-6905-40d2-9155-4ab6facd51e8.png)
HELLO CAN YOU BRING THIS FEATURE?
When the waiter enters the order, the tables are opened automatically, so there is no need to enter the table or refresh the page.

  ---  IF YOU LIKE MY TABLE SHAPE, YOU CAN BRING IT TO THE GASTRO, IT'S EASIER THAT I FIXED IT :) ...

**Comment by Blair2004** [comment]
Please, make sure your screenshot are in english... we can't undestand your image.

**Comment by lim10soft** [comment]
hello I don't want feature I want automatic refresh of tables section. For example, a waiter entered the order, the page needs to be refreshed in order to open that table in the cash register section. I want it to do this automatically.

**Comment by Blair2004** [comment]
It's a new feature that requires something to be added so = new feature (or improvement if you want). It's therefore not an "issue".

> hello I don't want feature I want automatic refresh of tables section. For example, a waiter entered the order, the page needs to be refreshed in order to open that table in the cash register section. I want it to do this automatically.

**Comment by lim10soft** [comment]
I understand, I'm writing to the request section, then I'm sorry, have a good work
