### ISSUE TITLE
[Issue] Error after enable multistore module

### ISSUE THREAD

**Issue by ardhy-w** [Blair2004/NexoPOS-4x#764]
I'm having an error after enable multistore module after installing it.

**To Reproduce**
1. Install Module Multistore
2. Enable Multi Store module
3. See error

**Expected behavior**
It sould be success enable multistore module

**Screenshots**
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/10648963/167545024-d4873787-3eea-409d-8efe-8c997fd3772b.png">

**Environment:**
 - NexoPOS 4.x version: 4.7.6
 - Multistore Module version: 4.7.3

**Comment by tungnt-vn** [comment]
Update to NexoPOS v.7.4.7 and Multistore v7.4.4 to resolve that problem.

**Comment by Blair2004** [comment]
> Update to NexoPOS v.7.4.7 and Multistore v7.4.4 to resolve that problem.

NexoPOS v7.4.7 is not yet released. However, this issue is fixed with NexoPOS 4.7.7 and Multistore v4.7.4
