### ISSUE TITLE
[Issue] Cannot assign role for user when enable Mutistore module v7.4.4

### ISSUE THREAD

**Issue by tungnt-vn** [Blair2004/NexoPOS-4x#770]
**Describe the bug**
I apply the module Multistore version 7.4.4 and enable successfully but cannot assign role for application user after. It also removed my administrator account

**To Reproduce**
1. Install NexoPOS
2. Upload module Multistore
3. Enable Multistore module
4. Create user and assign role for user
5. See error

![image](https://user-images.githubusercontent.com/38593321/167880913-ba039040-b266-4ae7-bf85-0a4cb7defc43.png)

**Environment:**
 - NexoPOS 4.7.7
 - Multistore module 4.7.4

**Comment by tungnt-vn** [comment]
As I noted the Multistore enabling removed my administrator account. I also added the account again by accessing directly to DB and insert manually.

**Comment by Blair2004** [comment]
Fixed with https://github.com/Blair2004/NexoPOS-4x/commit/ebb11ea4d678b7cae788914591b2c27d5d90bc04
Will be added on NexoPOS 4.7.8

**Comment by Blair2004** [comment]
Meanwhile, you can copy that file and replace it on your installation https://github.com/Blair2004/NexoPOS-4x/blob/ebb11ea4d678b7cae788914591b2c27d5d90bc04/app/Crud/UserCrud.php
