### ISSUE TITLE
[Issue] Can't Set Role for New User

### ISSUE THREAD

**Issue by osama1998H** [Blair2004/NexoPOS-4x#773]
**Describe the bug**
when I created a new user I couldn't set a role for it.

**To Reproduce**
1. Go to 'Users'
2. Click on 'List'
3. add a role to any user without roles
4. see the error

**Expected behavior**
add a new role for the user

**Screenshots**

![Screenshot 2022-05-12 151352](https://user-images.githubusercontent.com/42488643/168073081-aac40298-c266-4710-9525-23df5c2fbaaf.png)

@nexopos 
@HarukaMa 
@Blair2004 

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7.7]

**Comment by Blair2004** [comment]
Hi, 
We had that issue reported and yet we've added a fix for the upcoming version. See #770
duplicate of #770

**Comment by Blair2004** [comment]
Hi, 
We had that issue reported and yet we've added a fix for the upcoming version. See #770
duplicate of #770

**Comment by osama1998H** [comment]
@Blair2004 When will version 4.7.8 be released?
