### ISSUE TITLE
[Issue] CSS Style lost in development mode

### ISSUE THREAD

**Issue by tungnt-vn** [Blair2004/NexoPOS-4x#776]
**Describe the bug**
The CSS style is lost as screen shot.

**To Reproduce**
1. Set 'NS_ENV=dev'
2. Run server by command: php artisan serve
3. Run dev mode by command: npm run watch
4. Launch to POS screen 
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/38593321/168417008-2301709f-bb85-4317-a622-1740528e4a5a.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.7.7
 - Mutistore Plugin version: 4.7.4

**Comment by Blair2004** [comment]
Hi, can you check the asset has been created on the "public" directory ?

**Comment by tungnt-vn** [comment]
> Hi, can you check the asset has been created on the "public" directory ?

Seem as the asset wasn't created in the public folder, only one asset folder was created at nsmultistore module but just is image (See the screen capture)
![image](https://user-images.githubusercontent.com/38593321/168418878-729e7d13-e9cd-4a1a-90cc-08ccc7b4a951.png)

**Comment by Blair2004** [comment]
Check the public/css folder.

**Comment by tungnt-vn** [comment]
> Check the public/css folder.
This is public folder:
![image](https://user-images.githubusercontent.com/38593321/168439502-011673d5-e823-4c01-9376-91b5aa67ca60.png)

**Comment by Blair2004** [comment]
This is the minimized version for some reason, the compiled script doesn't get saved on that directory.
Can you show the output when you run:

`npm run watch` ?

Note that additionally to that command you also need to run `npm run css-watch`.

**Comment by tungnt-vn** [comment]
> This is the minimized version for some reason, the compiled script doesn't get saved on that directory. Can you show the output when you run:
> 
> `npm run watch` ?
> 
> Note that additionally to that command you also need to run `npm run css-watch`.

Thank you so much! I did that and succeeded. That mean I need to run 3 consoles:
1. for php laravel by ` php artisan serve`
2. for js watch by ` npm run watch`
3. for css watch by  `npm run css-watch`
