### ISSUE TITLE
The latest release v4.7.8 shows error "Unable to locate Mix file_ _js_bootstrap.min_bootstrap.js" after install

### ISSUE THREAD

**Issue by NureGha** [Blair2004/NexoPOS-4x#779]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
4. See error The latest release v4.7.8 shows error "Unable to locate Mix file_ _js_bootstrap.min_bootstrap.js" after install

**Expected behavior**
Welcome page NexoPOS installed successfully should appear.  

**Screenshots**
![Web capture_15-5-2022_19430_127 0 0 1](https://user-images.githubusercontent.com/105599312/168482382-fe745748-045e-4278-aa07-ac77320a4a0b.jpeg)

**Environment:**
 - NexoPOS 4.7.8 vesrion: 
 -

**Comment by Blair2004** [comment]
Hi,
Every error should correctly be filled. Read this #501 to understand how to create an issue.
For the few details you shared, make sure on the .env NS_ENV is set to "prod" or "productions". If you what to try the development mode, run the following commands (2 terminals needed): 

`npm run prod`
`npm run css-watch`

Let us know how that goes.

**Comment by Blair2004** [comment]
Closed for inactivity.
