### ISSUE TITLE
[Issue] App crash after setting up multistore subdomain

### ISSUE THREAD

**Issue by tungnt-vn** [Blair2004/NexoPOS-4x#780]
**Describe the bug**
When I setting the Sub Domain Routing is enable the app is crashed with error: 'include(/var/www/html/.../routes/api/transfer.php): Failed to open stream: No such file or directory

**To Reproduce**
1. Go to dashboard screen
2. Click on **setting** menu under **Stores** menu.
3. Set Sub Domain Routing to enable and Save Setting.
![image](https://user-images.githubusercontent.com/38593321/168485410-d2ea0ac4-d410-4d42-9225-4bcb74ec525f.png)

Please check and fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38593321/168485464-3def0b7d-85f7-473a-8060-08c2fb64429f.png)

**Environment:**
 - NexoPOS 4.x vesrion: 4.7.7
 - Multistore module: v4.7.4

**Comment by Blair2004** [comment]
Hi, 
Update to NexoPOS 4.7.8
Thanks

**Comment by Blair2004** [comment]
Closed for inactivity.
