### ISSUE TITLE
help

### ISSUE THREAD

**Issue by namthai1422001** [Blair2004/NexoPOS-4x#782]
![image](https://user-images.githubusercontent.com/104348724/168504905-69f0e319-2c7b-4953-be35-ccbe0a71b47c.png)
Please help me, after I database configuration, I enter the database, then show that you need to define database settings, I tried to fix it but not

**Comment by Blair2004** [comment]
Hi, as a quick help regarding this, don't use the built-in server (php artisan serve) as after settings up the database, the server restart and cause this. Instead consider using a valid virtual server like Laragon (https://laragon.org/) that has virtual domain. The tutorial on how to install is here https://my.nexopos.com/en/documentation/how-tos/installing-nexopos-4-x-on-laragon

For upcoming issue, make sure to see this #501 to know how to format your issue.

Thanks.

**Comment by Blair2004** [comment]
Clsoed for inactivity.
