### ISSUE TITLE
[Issue] cant integrate raw material module with nexoPos v4.x

### ISSUE THREAD

**Issue by osama1998H** [Blair2004/NexoPOS-4x#784]
**Describe the bug**
I cant integrate the raw material module with nexoPos v4.x

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7.8]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.7.2)]

**Comment by Blair2004** [comment]
Hi, we don't have any raw material module for NexoPOS 4.x for now.
