### ISSUE TITLE
[Issue] Bugfix 4.7.8 cannot create products.

### ISSUE THREAD

**Issue by apdev95** [Blair2004/NexoPOS-4x#790]
**Describe the bug**

When I add a new product on the last 4.7.8 I still encounter problems "Unable to proceed the form is not valid." even if I just selected the price, unit group etc...

If you go to 

`resources/ts/pages/dashboard/procurements/manage-products.vue
`
and remove 

```
const validity = this.form.variations
        .map((variation) => {
          return this.formValidation.validateForm(variation);
        })
        .filter((v) => v.length > 0);

      if (
        validity.length > 0 ||
        Object.values(this.form.main.errors).length > 0
      ) {
        return nsSnackBar
          .error(
            this.$slots["error-form-invalid"]
              ? this.$slots["error-form-invalid"][0].text
              : __("Unable to proceed the form is not valid.")
          )
          .subscribe();
      }
```
The product is added.

Maybe because in the HTML the field is called sale_price_edited and pass in the validation sale_price, maybe...

However If I remove this block the price goes right  and the product is created.

**Environment:**
 - NexoPOS 4.x version: 4.7.8
 - Premium Extensions: Gastro, Ns Print Adapter, Ns Woocommerce

**Comment by apdev95** [comment]
I can confirm, Downgraded to 4.7.7, no problems at all!

**Comment by Blair2004** [comment]
Hi, thank you for reporting that. As you've already downgraded, we cannot ask you to provide a screenshot of the server response. However, to ease the debugging, can you share a screenshot of how you're creating the product ? The value you're fililng?

From monday, we'll investigate.

Kind regards.

**Comment by apdev95** [comment]
Hi, thanks Blair! 

You can console.log(this.formValidation.validateForm(variation)) and you will see 2 errors in the array, sale_price and wholesale_price, but in html input they are called sale_price_edited wholesale_price_edited.

I don't have any screenshot bro, but If you debug as I told you, you will find the gap, maybe due to input name

**Comment by Blair2004** [comment]
This likely seems to be a validation issue. A field not correctly filled. We've tried but not been able to fix this. Probably a video can help us understand the issue better.
