### ISSUE TITLE
[Issue] nexo print server won't accept license my nexopos won't connect

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#791]
I am using the latest versions of nexopos and plugins. I have a problem connecting my nexopos to my nexopos and the nexoprint server gives license error.
I'm sure I did everything right.
![23432423432](https://user-images.githubusercontent.com/102427740/169713929-11e90003-2574-40f8-b144-1d9b63de2ca3.png)
![Adsız](https://user-images.githubusercontent.com/102427740/169713930-d13bcf16-1ccb-427e-bcb7-e54c6abcf86a.png)

**Comment by Blair2004** [comment]
Hi, 
Once you define the APP ID and the Secret Key, make sure to save the settings.

**Comment by Blair2004** [comment]
For Nexo Print Server, have you previously used the license on another computer?
Let me know.

**Comment by lim10soft** [comment]
yes, when I used it, I paid 1 software money for it. Do I have to pay the
same money for each computer all the time?

24 May 2022 Sal 11:11 tarihinde Blair Jersyer ***@***.***>
şunu yazdı:

**Comment by lim10soft** [comment]
I'm doing everything right, but there is a problem, none of them accept.

**Comment by lim10soft** [comment]
My license has been reset but the nexo print server is still giving an error
![2132132](https://user-images.githubusercontent.com/102427740/170038444-1cd4df60-ebb6-4d94-9280-3387e19d73f4.png)

**Comment by Blair2004** [comment]
Fixed
