### ISSUE TITLE
[Issue] Can't Select Customer Account in POS

### ISSUE THREAD

**Issue by bonisaputra** [Blair2004/NexoPOS-4x#795]
**Describe the bug**
Can't Select Customer Account in POS after Set in Default Customer Account in Setting>Customer Page

**To Reproduce**
1. Go to Setting > Customer
2. Set one Default Customer Account
3. Go to POS page,
4. Click Customer popup
5. H2 tag font color is white
6. Can't Select another customer, only default customer has been set before

**Expected behavior**
H2 tag font color should be change
can select another customer except default customer

**Screenshots**
shown
![1](https://user-images.githubusercontent.com/11271494/169971976-08b03a87-9646-4764-bb96-11a1ac6a1a61.PNG)

expected

![1](https://user-images.githubusercontent.com/11271494/169972701-e908e3f2-0bb3-4ff1-b572-25040992938b.PNG)

**Environment:**
 - NexoPOS 4.x version: 4.7.8

**Comment by Blair2004** [comment]
Do you mean when you assign a default customer. His details aren't opened when you open the popup ?
Can you explain how to proceed to open that popup ?

**Comment by Blair2004** [comment]
closed for inactivity.
