### ISSUE TITLE
[Issue] multiple fixes.

### ISSUE THREAD

**Issue by apdev95** [Blair2004/NexoPOS-4x#796]
**Describe the bug**
- Fix missing sprintf %s parameter for cooking_note for single product ->  in /modules/NsGastro/Resources/Views/kitchens/receipt.blade.php:81  NsGastro v4.7.2
- FIx NpsAdapter calling always CloudPrintJob even if disabled. so the call /kitchen-receipts is made 2 times and products aren't printed. -> /modules/NsPrintAdapter/Jobs/CloudPrintJob.php:34, to work i put a return; and receipt are going to print.

**Environment:**
 - NexoPOS 4.x version: 4.7.7
 - Premium Extensions: NsGastro 4.7.2

**Comment by Blair2004** [comment]
The NPS adapter issue is fixed with the version v4.7.5

> **Describe the bug**
> 
> * Fix missing sprintf %s parameter for cooking_note for single product ->  in /modules/NsGastro/Resources/Views/kitchens/receipt.blade.php:81  NsGastro v4.7.2

![image](https://user-images.githubusercontent.com/5265663/170829541-984bba5c-3d25-4ec5-aec1-46b9c3800256.png)
Cooking note is not missing.
