### ISSUE TITLE
[Issue] HELLO Blair2004 I WANTED TO SHARE WITH YOU THE MAIN PROBLEMS AND SHORTCOMINGS THAT I HAVE SEEN AS ALWAYS.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#804]
1. PROBLEMS:  INSTALLMENT PROBLEM . WHEN A CUSTOMER IS INSTALED, IF THE CUSTOMER WANTS TO PAY EARLY, IT GIVES A DATE ERROR. AND THERE IS NO PLACE TO CHANGE HISTORY. IN ADDITION, THE CASHIER MUST BE KEPT AWAY FROM THE WORK THAT TAKES HIS TIME AND THE CUSTOMER MUST BE ABLE TO MAKE HIS PAYMENT WHEN HE WANTS. 

2. PROBLEMS: Daily expenses should be determined. And when Creating This Expense, there should be room for clarification as to why the expense was created.  When creating the expense, there should be an option to see if this expense is covered by cash payment or credit card payment.  The expense must be deducted from the daily money in the safe.  and all these events should be reported in the admin panel. expenses should be looked at in date ranges. An end-of-day report should be created in this report, the daily sales report should be poured into a complete report such as the definitions of the expenses incurred, cancellations, the gain without expenses, the gain after the expenses happen.

3. PROBLEMS:  
![Adsız](https://user-images.githubusercontent.com/102427740/170903066-7729f7f5-ea68-4111-9978-f40d7728fceb.png)

**Comment by Blair2004** [comment]
Hi, Please, report each issue separately. 

1 - For example for the error that occurs with the instalment. This doesn't have further context we're not able to understand.
2 - This is quite broad can you specify ? If this should be applicable to some interface, please consider sharing those interface with your suggestions. From what i understand you mean there should always be a reason for an expense and that should be clarified, there should also be a mention for the payment type used for an expense right ? If you have  better report suggestion we're open for that.
3 - What is the issue with having to select a date ?

**Comment by lim10soft** [comment]
**1-**
![2022-06-01_03-03-45](https://user-images.githubusercontent.com/102427740/171303443-ecf3208b-863c-4858-869e-3bd4b7ba9766.png)
![2022-06-01_03-06-57](https://user-images.githubusercontent.com/102427740/171303452-598d4d3b-bee2-4710-b822-4cccba12a9b9.png)
**2**
The customer can not pay before the date comes, which is very wrong. tires the cashier . nor is there a place to change the customer's payment date.

**3**
THERE IS NO PROBLEM WITH THE DATE RANGES, BUT FOR CONVENIENCE, IF THERE ARE SUCH BUTTONS, IT IS BETTER TO POUR THE RAPÉS AS THEY ARE CLICKED. THAT'S WHY IT HAS TO BE IN A CORNER OF THESE AS AN EXTRA.


THANK YOU FOR YOUR INTEREST

**Comment by BienBrian** [comment]
Hello @lim10soft, 
to solve that instalment/date bug, I proceeded to /app/Services/OrderService.php and commended lines 774-776. That is the line of code causing the bug problem

**Comment by BienBrian** [comment]
> Hello @lim10soft, to solve that instalment/date bug, I proceeded to /app/Services/OrderService.php and commended lines 774-776. That is the line of code causing the bug problem

Here is the snapshot 

![image](https://user-images.githubusercontent.com/33430455/182391852-1f5f1631-e5b0-4a42-97be-917f491ba063.png)

**Comment by Blair2004** [comment]
Some of the suggested point were merged. For the rest we'll keep it asied.
