### ISSUE TITLE
Sign In Problem

### ISSUE THREAD

**Issue by devesh-takoor** [Blair2004/NexoPOS-4x#814]
Hello Blair, my main issue is that I can not even log in although I have already connected everything to the Database and registering my account was successful, I can even see my registering details in the database but when I sign in it tells me CSRF token mismatch. What can be don to solve this issue?

![image](https://user-images.githubusercontent.com/92701740/171556244-556a528e-653a-4e7f-8a70-a845669ee3b6.png)

**Comment by Blair2004** [comment]
Hi, the solution is explained here https://my.nexopos.com/en/documentation/troubleshooting/how-to-fix-csrf-token-mismatch-on-nexopos-4-x

**Comment by devesh-takoor** [comment]
Hello again Blair,

Thank you for the documentation

Regards,
Devesh
