### ISSUE TITLE
[Issue] Unable to create Product - Maximum Execution Time exceeded

### ISSUE THREAD

**Issue by muffaddal** [Blair2004/NexoPOS-4x#835]
While creating a new product, I am getting an error - maximum execution time 30 seconds exceeded

**To Reproduce**
1. Create new product
2. Add all relevant data
3. Click on save

Maximum execution time of 60 seconds exceeded in /Users/indiaitcandev4/workspace/wwtd/NexoPOS-4x/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 396

**Expected behavior**
The Product should be saved in the system

**Screenshots**

<img width="1680" alt="Screenshot 2022-06-07 at 12 12 00 PM" src="https://user-images.githubusercontent.com/5665522/172313196-096f9d6f-fe21-41f8-b2a8-5ec60f5452ad.png">

**Environment:**
 - NexoPOS [NexoPOS 4.7.8](https://my.nexopos.com/en)

**Comment by Blair2004** [comment]
Conside using 4.7.10 https://github.com/Blair2004/NexoPOS-4x/releases/tag/v4.7.10

**Comment by muffaddal** [comment]
@Blair2004 Thank you for your prompt response, Everything works like a charm! Thank you 🙏
