### ISSUE TITLE
DATA IMPORTATION FROM ANOTHER SOFTWARE

### ISSUE THREAD

**Issue by UkinnovationTechs** [Blair2004/NexoPOS-4x#837]
Hi,

My name is Harun from UK, UK INNOVATION INFORMATION TECHNOLOGIES LTD. 

Many of aour customers use Odoo Software, we would like to thansfer all off them to NexoPOS and start with one of them.  Sold NexoPOS, installed. Now implementing the Nexo for their usage.

At this point, allready import customers,products and categories from other software. Made aeducation for users and make arrangement for invoice , printers,m etc...

Now, I need help for  import rest of data. Orders, Invoices, Payments...from other software. could you gime a hand please. 

Parepare SQL statement or Table indicates for me?

**Comment by Blair2004** [comment]
Closed for inactivity.

**Comment by Blair2004** [comment]
If the error is specific to the free version of NexoPOS feel free to open a thread for each issues.

**Comment by UkinnovationTechs** [comment]
Licenced verison also all off the paid modules are licenced.  Multi Store, Stock Transfer, Rack Manager, Bulk import...etc..
