### ISSUE TITLE
[Issue] KITCHEN SCREEN SOUND PROBLEM

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#838]
IT DOESN'T MAKE A SOUND WHEN SENDING THE FIRST PRODUCT TO THE KITCHEN SCREEN, BUT IT DOES MAKE A SOUND WHEN SENDING THE 2ND PRODUCT. WE MUST NOT ALWAYS COMPLETE 1 PRODUCT TO MAKE A SOUND. THERE IS SUCH A PROBLEM.

**Comment by Blair2004** [comment]
Fixed with Gastro 4.8.7
