### ISSUE TITLE
[Issue] Order Problem

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#849]
![2022-06-10_00-47-51](https://user-images.githubusercontent.com/102427740/172951192-5974dcd7-409a-470b-82d8-89115271a692.png)
![2022-06-10_00-49-55](https://user-images.githubusercontent.com/102427740/172951279-a1da810f-4a64-4adc-b439-f256effe7073.png)

Orders remain open in this section even though the relevant orders have been paid for.  It doesn't happen with every order, but at the end of each day there are several orders left.

**Comment by lim10soft** [comment]
I have not yet received an answer to my question, it is an important problem.

**Comment by Blair2004** [comment]
We're not able to proceed your issue for the following reason : 

- Screenshot in Turkish
- Issue not correctly formated (missing modules with version used)
