### ISSUE TITLE
Missing Front End Style

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#85]
After successfully installing NexoPOS in Windows 10 and running 127.0.0.1, all I can see is this plain html page.

![image](https://user-images.githubusercontent.com/16180446/97088177-ba68c800-1661-11eb-8217-0ac2d1e04df4.png)

**Comment by scalinux** [comment]
composer require doctrine/dbal | php artisan storage:link |npm i | git pull | npm run prod | php artisan serve 

Copy and paste this on the command line. I hope it work for you. 

http://nexopos-4x.test/
This will work if you set default virtual host value.

Good luck!

**Comment by scalinux** [comment]
composer require doctrine/dbal | php artisan storage:link |npm i | git pull | npm run prod | php artisan serve 

Copy and paste this on the command line. I hope it work for you. 

Rem to set virtual host address. 
Good luck!

**Comment by Blair2004** [comment]
Hi, 
if you see this error, it means NexoPOS hasn't assets built. In order to built assets, you'll need to have nodejs installed (along with npm). Once installed as @scalinux has mentioned, you'll just need to run : 
```
npm run prod
```

**Comment by Cyaaaaaaaaan** [comment]
Thanks for the quick help! Now I'm getting this error after following @scalinux's suggestion 
![image](https://user-images.githubusercontent.com/16180446/97099040-f1b99200-16be-11eb-9442-4d98f62186e0.png)

**Comment by Blair2004** [comment]
Can you share details about the node version you're using ? And which
command cause this issue ?

**Comment by Cyaaaaaaaaan** [comment]
I'm using Node 15.0.1 and running npm run prod show me all these errors.

**Comment by Blair2004** [comment]
I see the thread is closed, did you find a wayout ?

**Comment by Cyaaaaaaaaan** [comment]
What I did was reset the while process and this time cloning the git repo
instead of downloading the zip, and then run 'npm install' then 'npm run
prod' before anything else. I don't if this is the fix. I might have to
replicate it again tomorrow to see if the real problem was the order of
process.

Sorry fpr my bad grammar.

**Comment by Blair2004** [comment]
Alright, let us know.

**Comment by Cyaaaaaaaaan** [comment]
Is this nexopos ready for use already? Or there are some features still
missing?

**Comment by Blair2004** [comment]
There are some feature missing.

**Comment by Cyaaaaaaaaan** [comment]
Aight, I think Im just gonna buy license for the NexoPOS 3 and use that for
a while

**Comment by Blair2004** [comment]
Alright then.

**Comment by Cyaaaaaaaaan** [comment]
Hi Blair!

Is there a reason why I'm getting this error when using PHP 7.1? I don't
get this error on PHP 7.2
[image: image.png]

**Comment by Blair2004** [comment]
Hi please if you're pointing to a new issue on NexoPOS 4.x please open a new thread. If you're asking support on NexoPOS 3.x : https://github.com/nexopos/v3-issues is the repository for that.
