### ISSUE TITLE
[Issue] Cannot setup the GMT time for store

### ISSUE THREAD

**Issue by tungnt-vn** [Blair2004/NexoPOS-4x#852]
**Describe the bug**
I setup the GMT time for one store is GMT + 7 Indochina Time but all orders of store in Database is created with GMT + 0 time.

**To Reproduce**
1. Go to 'Store setting > General > Date'
2. Change GMT time to 'GMT + 7 Indochina time'
3. Save it and go to POS screen
4. Create an Order then pay for it
5. Back to Dashboard screen > Orders List.
6. See the created date.
Result: the time of created date is followed GMT + 0 while setting is GMT + 7
Expect: Created time is following the setting 

Nexopos 4.7.7
Multistore module 4.7.4

**Screenshots**
![image](https://user-images.githubusercontent.com/38593321/173112978-d9aa2bcb-cce4-46f2-b947-271709c42350.png)

**Comment by Blair2004** [comment]
Fixed on recent update
