### ISSUE TITLE
[Issue] A problem with the installation wizard 

### ISSUE THREAD

**Issue by MElhalees** [Blair2004/NexoPOS-4x#853]
**Describe the bug**
I filled the database name input and tried to click on "Save Database" and I got this response:
![image](https://user-images.githubusercontent.com/107335169/173271113-097af3f0-9cec-4c7f-8770-d78f2b50b998.png)

And I made sure about all the form data.

Server Log:
```
[Mon Jun 13 04:58:53 2022] 127.0.0.1:53185 Accepted
Environment modified. Restarting server...
[Mon Jun 13 04:58:54 2022] PHP 8.1.4 Development Server (http://127.0.0.1:8000) started
```

**To Reproduce**
1. [Install the app](https://my.nexopos.com/en/documentation/getting-started/installation-wizard)
2. Go to the installation wizard page.
3. Set the database info.
4. Click on "Save Database"

**Expected behavior**
Successful connection to the database and running the installation wizard.

**Environment:**
 - NexoPOS 4.7.102
 - Web server:
   - Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.4
   - Database client version: libmysql - mysqlnd 8.1.4
   - PHP extension: mysqli, curl, mbstring
   - PHP version: 8.1.4
 - Database server:
   - Server: 127.0.0.1 via TCP/IP
   - Server type: MariaDB
   - Server connection: SSL is not being used
   - Server version: 10.4.24-MariaDB - mariadb.org binary distribution
   - Protocol version: 10
   - Server charset: UTF-8 Unicode (utf8mb4)

**Comment by MElhalees** [comment]
I am trying to solve this issue, but I figured out that after many clicks on the save database button, the app made a successful connection and went to the app config page.

Another strange thing sometimes it makes a successful connection without routing me to the app config page.

**Comment by Blair2004** [comment]
Any update ?

**Comment by MElhalees** [comment]
I gonna try now and I'll let you know.
Thanks

**Comment by MElhalees** [comment]
Yes, everything is working well, now.
I used laragon with env requirements stated [here](https://my.nexopos.com/en/documentation/getting-started/configuring-the-environment)

Thanks
