### ISSUE TITLE
[Issue] Cache register name validation error

### ISSUE THREAD

**Issue by MElhalees** [Blair2004/NexoPOS-4x#857]
**Describe the bug**
When I clicked create with an empty name field, I got this message error:
![image](https://user-images.githubusercontent.com/107335169/173711053-8511b5b9-8971-4df8-a44c-9440a20124c0.png)

**To Reproduce**
1. Enable cache registers.
2. POS > Create Cache register
3. Click "Save" without providing any data.

**Expected behavior**
Show the message "Name field is required!" instead of showing the SQL error message.

**Environment:**
 - NexoPOS 4.7.10

**Comment by Blair2004** [comment]
Thanks
