### ISSUE TITLE
Multiple EAN13 barcodes for the same product

### ISSUE THREAD

**Issue by saverioV** [Blair2004/NexoPOS-4x#865]
I want to add n Ean13 barcodes to the same product.
In the Eu there are many products that have multiple ean13 barcode. For example same product from different countries and  sometimes for the exact same product we have a different barcode.
How handle this case or what approach could be used to implement this feature (one to many relationship products-barcodes)?
Txs

**Comment by Blair2004** [comment]
Hi, 
For now we don't have a support for multiple barcodes. We believe such product should be treated as a separate product as it has a different inventory and different barcode. Scanning the barcode on the POS should deplete the corresponding inventory.
