### ISSUE TITLE
[Issue] Required validation for inputs

### ISSUE THREAD

**Issue by MElhalees** [Blair2004/NexoPOS-4x#866]
**Describe the bug**
There are some required inputs without "Required validation". As a result message like this appears:
![image](https://user-images.githubusercontent.com/107335169/174445426-dfa07502-5f11-409b-a7af-d42d6022ab55.png)

Problem exists in:
* Orders > Create new payment [priority]
* Inventory > Create category [name]
* Inventory > Create unit [name]
* Inventory > Create unit group [name]
* Providers > Create A Provider [name]
* Accounting > Create Expense [name, value, recurring]
* Accounting > Creat account [name, operation, account]
* Taxes > Create tax groups [name]
* Taxes > Create tax [name, parent, rate]
* Users > Create Roles [name]

**Environment:**
 - NexoPOS 4.8.0

Please, I would be happy if you assign me to test input validation through the dashboard.
There are also some fields that need to be validated on their data types, I will do it later.

Thanks

**Comment by Blair2004** [comment]
Hi,
Thank you for sharing such valuable feedback.

**Comment by Blair2004** [comment]
merged
