### ISSUE TITLE
[Issue] Can't edit product stock

### ISSUE THREAD

**Issue by kkr1pt3k** [Blair2004/NexoPOS-4x#875]
**Describe the bug**
The options button which will be used to update product quantity doesn't work. It does nothing when clicked. The video explains it clearly

**Screenshots**
https://user-images.githubusercontent.com/106962897/174760607-1810ac85-b9fe-4d0e-90c9-60ff6d06e9a4.mp4

**Environment:**
 - NexoPOS 4.x vesrion.
 - Installed on Laragon.

**Comment by Blair2004** [comment]
This is not an issue. 
Once added, the stock can only be edited through stock adjustment to be able to track the operation globally on the app.

https://my.nexopos.com/en/documentation/components/stock-adjustment
