### ISSUE TITLE
[Issue] When the refund is made, the amount refunded from the sale does not decrease according to the payment types.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#880]
I refunded a payment. When I enter sales according to payment types, the amount I return does not deduct from the amount sold.
![2022-06-23_00-00-20](https://user-images.githubusercontent.com/102427740/175135389-23e446ef-37b6-4242-b80f-b9aaab3625e5.png)
![2022-06-23_00-01-14](https://user-images.githubusercontent.com/102427740/175135419-e0c49f51-2376-45e6-a781-edc281a6349b.png)

**Comment by Blair2004** [comment]
Issue not correctly formatted

**Comment by lim10soft** [comment]
When I return an item, it should be deducted from my cash earnings.

**Comment by Blair2004** [comment]
Please make sure when you're creating an issue to follow this format #501 that will help us understanding your issue.
Thanks

**Comment by Blair2004** [comment]
Also, avoid uploading screenshot in Turkish as we provide support in English please.
