### ISSUE TITLE
No tax group assigned to the order

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#901]
**Describe the bug**
When I try to sell an item I am getting the error "No tax group assigned to the order"

**To Reproduce**

**Expected behavior**

**Screenshots**
![No tax group assigned to the order](https://user-images.githubusercontent.com/13999977/176604940-b88d5ded-eb44-435f-9499-3a96d9cbcbef.png)

**Environment:**
 - NexoPOS 4.x version: [4.7.12] Live Demo

**Comment by cdcede** [comment]
I have the same issue with the taxes, and  one more  with the unit price because the value not change in the POS. In the global settings is active.

**Comment by Blair2004** [comment]
Hi, we’re working on that.

**Comment by osama1998H** [comment]
i have the same problem

**Comment by Blair2004** [comment]
Hi, can anyone give a shot to the branch v4.8.x

**Comment by Blair2004** [comment]
Closed for inactivity.
