### ISSUE TITLE
Inclusive Tax Calculation on sales is Wrong

### ISSUE THREAD

**Issue by mbugikp** [Blair2004/NexoPOS-4x#902]
**Describe the bug**
When dealing with Inclusive tax on sales the calculation is wrong. If I am selling product z at 100 inclusive of tax the breakage is as follows. The customer will pay 100 however on the receipt the breakdown will be assuming Tax@16%.
Selling Price 100
Tax at 16%     13.79
Price before Tax 86.21
Total Price 100 (86.21+13.79)
How did we get 13.79 we take the selling price inclusive of tax (100) divide by 116 (100+tax rate) then multiply by100 we get 86.206 rounded to 86.21,we then less this amount from the selling price thus (Selling Price inclusive of tax 100-86.21) =13.79. 
To confirm take the Selling Price before tax 86.21 multiply by a factor of 1.16 you will get 100.0036 rounded to 100.00
Therefore the Customer will pay 100 not 86.
 

**To Reproduce**
Sell an item with tax inclusive

**Screenshots**
![tax inclusive1](https://user-images.githubusercontent.com/13999977/176610150-5af4d362-f8f6-461a-8ca9-898bf2bd8903.png)

customer payment

![tax inclusive2](https://user-images.githubusercontent.com/13999977/176610213-f892091a-5184-48ac-83fd-f37d8ff52385.png)

**Environment:**
 - NexoPOS 4.x version: [e.g. 4.7.12] Live Demo

**Comment by Blair2004** [comment]
Hi, 
Thank you for reporting.
On NexoPOS 4.8.x we've globally changed how taxes are computed. We'll expect a feedback from you went it will released.

A quick workaround is to :
- Enable gross sale price
- Change the currency precison to 2

Let us know if that worked.

**Comment by Blair2004** [comment]
Closed for inactivity
