### ISSUE TITLE
[Issue] You're not authenticated. on laravel forge

### ISSUE THREAD

**Issue by osama1998H** [Blair2004/NexoPOS-4x#908]
**Describe the bug**
I deployed nexoPos on Laravel forge 

when     APP_ENV=development the website works correctly
when     APP_ENV=production  the error [You're not authenticated] is appears

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/42488643/177214444-cfb2225a-5c33-4766-be00-10d2015137bd.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7.11]

**Comment by Blair2004** [comment]
Hi, thank you for reporting.
I've never tried laravel forge, i think i'll give it a try.

Thank you.

**Comment by stav3ng3r** [comment]
Hi, I booted up a fresh install of branch v4.8.x on my local machine, not Forge, and I'm getting the same problem on both dev and production ENV. I can login fine but getting 401Unauthorized en every request on the dashboard.
v4.7 is working fine except for the No tax group assigned error when opening the POS view.

![Screenshot from 2022-07-08 17-47-50](https://user-images.githubusercontent.com/2817560/178074680-5069f650-b2c1-47cb-8879-04ba8a7c578d.png)

**Comment by osama1998H** [comment]
Hi i faced that problem last week
You need to make changes at env file 
Change the production value to development 
And it will work
