### ISSUE TITLE
[Issue] Create Kitchens Now Showing in Sidebar

### ISSUE THREAD

**Issue by osama1998H** [Blair2004/NexoPOS-4x#909]
**Describe the bug**

### Create Kitchens Now Showing in Sidebar only can access it via URL 

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7.11]
 - Premium Extensions: [Gastro (4.7.2)]

**Comment by Blair2004** [comment]
Hi, 
make sure your account has permission to see the kitchen. Check that on the permission manager.

**Comment by Blair2004** [comment]
Closed for inactivity
