### ISSUE TITLE
[Issue] translation on gastro module not working

### ISSUE THREAD

**Issue by osama1998H** [Blair2004/NexoPOS-4x#911]
**Describe the bug**
hi a wanted to add Arabic translation to the gastro module 
what I did 

- add the ar.json file to the lang folder 
- copy all content from en.json to ar.json
- replace all translations with the corrected one 
- zip the folder 
- delete the gastro app 
- reupload the new app that contains the ar.json file 

**Expected behavior**
a new translation should be appears
**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/42488643/177387473-221e6960-ebdc-4e61-a98e-f19208e530b6.png)
![Screenshot (3)](https://user-images.githubusercontent.com/42488643/177387484-0661b5db-cddb-4522-a964-474072b0cb1b.png)
![Screenshot (4)](https://user-images.githubusercontent.com/42488643/177387489-edbfd3a1-d070-4e21-891a-928977ca24c2.png)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.7.11]
 - Premium Extensions: [Gastro (4.7.2)]

**Comment by Blair2004** [comment]
Hi, 
Can you check if you have a 404 error while loading each page.
It's likely that Gastro doesn't have his assets link.

Try this commands.
`php artisan modules:symlink NsGastro`

**Comment by Blair2004** [comment]
Closed for inactivity.
