### ISSUE TITLE
Bad Method Call Exception

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#92]
It's giving me this error on the latest commit, last commit I tried that works well was [Commit: 86b1e7b](https://github.com/Blair2004/NexoPOS-4x/commit/86b1e7ba5fceb1025ba6898db5f6e2af131e0fcd)

![image](https://user-images.githubusercontent.com/16180446/100655710-a01fb980-3386-11eb-8284-6d6c8a1ff9ea.png)

**Comment by Cyaaaaaaaaan** [comment]
I tried removing the line Cookie::clear(); in SetupController.php then the error disappear. But I'm pretty sure it's not a fix and it's just a temporary work around.

Why is this happening?

**Comment by Blair2004** [comment]
Hi, does that happen when you're trying to install the app ?

**Comment by Cyaaaaaaaaan** [comment]
Happens on a fresh install app.

I haven't tried installing app with **Commit 86b1e7b** and then pulling from the git repo then running the app again.

**Comment by Blair2004** [comment]
I'm currently trying to create a multistore module, so it's a long task I usually have to switch computer (to change pose), that's why I'm committing, but I'm not done already. I'll work on that and update you once it's done.
