### ISSUE TITLE
Total order amount 1$

### ISSUE THREAD

**Issue by sew0ns** [Blair2004/NexoPOS-4x#94]
When I place more than 1 product, the order price is $1 or $2

![1AF8D3D2-3C1C-461C-88FB-6581A9E458A9](https://user-images.githubusercontent.com/15718165/101479172-97754780-3973-11eb-8a3c-c6e1be97cd2c.jpeg)
![Uploading 63FB36ED-E406-47F8-9963-C51794D319C6.jpeg…](
![6F85EE8A-ECA3-47D3-B959-EF36D5AB0BE4](https://user-images.githubusercontent.com/15718165/101479184-9ba16500-3973-11eb-91ad-e4ac3a9dc17e.png)
![582A4098-DFB4-44B7-A691-6BEF3F7F876B](https://user-images.githubusercontent.com/15718165/101479186-9cd29200-3973-11eb-892f-72d52a84ce2e.jpeg)

**Comment by sew0ns** [comment]
![900FCD98-1EAD-449B-8B10-395CA1C31253](https://user-images.githubusercontent.com/15718165/101479287-c4c1f580-3973-11eb-9d3a-9418984d8c82.jpeg)

**Comment by Blair2004** [comment]
Hi, thank you for having shared this. I'll make some test based on this.

**Comment by sew0ns** [comment]
> Hi, thank you for having shared this. I'll make some test based on this.

Okay, I’m wait the results of the tests

**Comment by Blair2004** [comment]
Hi, i'm not able to reproduce the error. Do you mean, if you more than one product? The total of the order changes to "1" ?

**Comment by sew0ns** [comment]
> Hi, i'm not able to reproduce the error. Do you mean, if you more than one product? The total of the order changes to "1" ?

Yes

**Comment by Blair2004** [comment]
Please consider providing a video capture of the step you're going through to reproduce the error.
Kind Regards.

**Comment by Blair2004** [comment]
Hi, I'm still awaiting thanks.

**Comment by Blair2004** [comment]
Closed for inactivity.
