### ISSUE TITLE
[Issue] Page not found (404)

### ISSUE THREAD

**Issue by ibrahimBougaoua** [Blair2004/NexoPOS-4x#941]
**Describe the bug**
Replace this section with a clear description of your issue. 

**To Reproduce**
1. Go to 'Providers List'
2. Click on 'Options'
3. Scroll down to 'See products'
4. Click on '+ add'
5. See error

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/41789518/180454821-89fcffe7-8a2c-49c8-a109-e2c2a5f5c967.PNG)
![2](https://user-images.githubusercontent.com/41789518/180454865-b7961711-b653-4ecd-b99b-313ef10ba4f7.PNG)

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by Blair2004** [comment]
Hi, 
What version if NexoPOS are you using ?

**Comment by ibrahimBougaoua** [comment]
hi,last version.

**Comment by Blair2004** [comment]
Hi, Please give the exact number you're using.
Thanks.

**Comment by ibrahimBougaoua** [comment]
"name": "blair2004/nexopos",
    "type": "project",
    "description": "The Free Modern Point Of Sale System build with Laravel, TailwindCSS and Vue.js.",
    "keywords": [
        "nexopos",
        "point of sale",
        "pos",
        "pos system"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.0.0",
        "beyondcode/laravel-websockets": "^1.11",
        "dekor/php-array-table": "^1.0",
        "doctrine/dbal": "^3.0",
        "fakerphp/faker": "^1.12",
        "fruitcake/laravel-cors": "^3.0",
        "gumlet/php-image-resize": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "jackiedo/dotenv-editor": "^2.0",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/telescope": "^4.0",
        "laravel/tinker": "^2.0",
        "laravie/parser": "^2.1",
        "phpoffice/phpspreadsheet": "^1.17",
        "picqer/php-barcode-generator": "^2.1",
        "predis/predis": "^2.0",
        "pusher/pusher-php-server": "^7.0",
        "spatie/laravel-db-snapshots": "^2.2",
        "symfony/http-client": "^6.0",
        "symfony/mailgun-mailer": "^6.0",
        "tormjens/eventy": "^0.8"
    },

**Comment by Blair2004** [comment]
Hi, that is rather the composer file.
The version is visible at the bottom of the page while on dashboard or config/nexopos.php

By any chances have you made any modification to the core files ?

**Comment by Blair2004** [comment]
Your issue lacks concrete details about your system making reproducing your issue hard or impossible.

We do expect when you create an issue to provide all necessary information that will avoid us asking much question about your system and therefore speed up the support process.

![image](https://user-images.githubusercontent.com/5265663/180593424-de452fcf-8dcd-4729-a947-34dee5aeb298.png)

**Comment by ibrahimBougaoua** [comment]
**version : 4.8.0**
I didn't change anything.

**Comment by ibrahimBougaoua** [comment]
**_The error appears when you follow these steps._**

**1. Go to 'Providers List'
2. Click on 'Options'
3. Scroll down to 'See products'
4. Click on 'Add'
5. Error appears ( _404 | Not found_ )**

**Comment by ibrahimBougaoua** [comment]
![image](https://user-images.githubusercontent.com/41789518/180659690-05865d17-fbb8-412f-9e7b-b3c2c1c3ca34.png)
![image](https://user-images.githubusercontent.com/41789518/180659722-c741c590-6b69-443c-9399-ee16b760af32.png)

**Comment by Blair2004** [comment]
Hi, 
Thank you. You can't indeed create products like that. This is made to just display products provided by a specific provider.

**Comment by ibrahimBougaoua** [comment]
**_Thank you._**

**Comment by Blair2004** [comment]
Fixed on 4.8.1
