### ISSUE TITLE
Customer appearing as best customer after the order have been deleted

### ISSUE THREAD

**Issue by Spyloop** [Blair2004/NexoPOS-4x#942]
I have deleted a customer order yet it shows the customer as the best customer with the deleted amount showing on the dashboard. 

To Reproduce:
1. Create an order with amount higher than all customers purchase on Nexopos. 
2. check dashboard if it appears as the best. 
3. of it does appear, go to order list and deleted the order. 
4. check dashboard again if it shows as best customer.

**Comment by Blair2004** [comment]
Thank you for reporting this, we'll investigate.

**Comment by Blair2004** [comment]
Should be fixed on 4.8.1

**Comment by Spyloop** [comment]
What is the fix for the issue?

**Comment by Blair2004** [comment]
Hi
Does the service worker are correctly configured on your end ?

Note that it’s an async operation that update the customer status. Want is
the value of QUEUE_DRIVER on your .env?

Let us know.
