### ISSUE TITLE
[Issue] The Barcode Processing Problem Still Persists.

### ISSUE THREAD

**Issue by lim10soft** [Blair2004/NexoPOS-4x#955]
![2022-07-28_15-14-15](https://user-images.githubusercontent.com/102427740/181502652-70012e24-4572-4eed-8e23-3c918ba9b9ac.png)
You have closed the location by typing Fixed The Problem I downloaded the latest version and tried again, but the problem is still in progress Barcode does not process.

**Comment by Blair2004** [comment]
Make sure to clear your cache.

**Comment by lim10soft** [comment]
thank you i cleared the cache and problem solved

**Comment by Blair2004** [comment]
Please... once again and for the last time. Make sure to use the default template provided for your issues. 
For a reference, check this #501
