### ISSUE TITLE
Read Expense History - Database duplicate entry

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#96]
Am I the only one getting this error? Using the latest commit
![image](https://user-images.githubusercontent.com/16180446/102018076-d8bb8c00-3da5-11eb-816c-76189532b9ce.png)

**Comment by Blair2004** [comment]
When does this happen please ?

**Comment by Cyaaaaaaaaan** [comment]
I cloned a fresh repo, started again from the beginning then this happened on "create installation" page.

**Comment by Blair2004** [comment]
Ohh alright thank you

**Comment by Cyaaaaaaaaan** [comment]
After the latest update it now says this:
![image](https://user-images.githubusercontent.com/16180446/102109384-f0ab1280-3e6e-11eb-9c3a-b06fe8823ff2.png)

**Comment by Cyaaaaaaaaan** [comment]
I was able to get passed to it by removing this line:
`$table->string( 'status' )->default( ExpenseHistory::STATUS_ACTIVE );`
from this file:
`2020_10_29_150642_create_nexopos_expenses_history_table.php`

but now I'm getting a blank **sign-in** and **sign-up form:**
_sign-up_
![image](https://user-images.githubusercontent.com/16180446/102113829-7aa9aa00-3e74-11eb-8834-bcc629f6f341.png)

_sign-in_
![image](https://user-images.githubusercontent.com/16180446/102113976-ae84cf80-3e74-11eb-9a9f-f605ee17d335.png)

@Blair2004
