### ISSUE TITLE
Customer Debt is not Consistent with their oder history

### ISSUE THREAD

**Issue by BienBrian** [Blair2004/NexoPOS-4x#979]
Here is a scenario where a customer has purchased and paid for products in full. Please note that this is the only order this customer has ever purchased from the shop. 
![Customer Debt Inconsistent 1](https://user-images.githubusercontent.com/33430455/182900432-dfe881c0-424f-451b-b6fc-0a950c04da9f.png)

However, when you navigate to the customer list, it shows that this customer has a debt equivalent to the above order value. 
![Customer Debt Inconsistent](https://user-images.githubusercontent.com/33430455/182901634-477ae0a8-148d-4028-ad6a-89223c3948e1.png)

This is further affecting other customers partially. Take a look at the customer below. 
![image](https://user-images.githubusercontent.com/33430455/182902014-fe1da0ab-8d25-431d-b20c-8910770609b8.png)
This is their order account

However, after navigating to the Customer List, you notice that the system views part of the above order as unpaid
![image](https://user-images.githubusercontent.com/33430455/182902216-5a6b6411-db99-4120-b10f-c6c9aab5688a.png)

Why is this important? 
We need a central point where we can point out a customer's debt. When this point is not accurate, it's a huge problem. 

I believe this is part of the Debtors Management that's plaguing this beautiful piece of software.

**Comment by BienBrian** [comment]
Sorry, the above highighted amount of KES 4440 was a mistake. That account's record is consistent with their order history.

**Comment by Blair2004** [comment]
We'll investigate on this.

**Comment by BienBrian** [comment]
Okay. 
Thanks

**Comment by Blair2004** [comment]
Can this be checked with new update v4.8.3 ? If the issue persist, please reopen the thread.
