### ISSUE TITLE
"Broken" Media feature on local app

### ISSUE THREAD

**Issue by Cyaaaaaaaaan** [Blair2004/NexoPOS-4x#98]
Is this feature meant to work on an app that is deployed on a web hosting?

**_Error:_**
1
![image](https://user-images.githubusercontent.com/16180446/102136473-64134b00-3e94-11eb-9cd3-f2228bbf25dc.png)
2
![image](https://user-images.githubusercontent.com/16180446/102136483-67a6d200-3e94-11eb-9644-6b054d80bad9.png)

**_Console Error:_**
![image](https://user-images.githubusercontent.com/16180446/102136518-72f9fd80-3e94-11eb-8475-3dd4cb791bda.png)

**Comment by Blair2004** [comment]
Yes, it looks like NexoPOS wasn't able to retrieve the file it has stored. What is the address to reach the system on your end please.

**Comment by Cyaaaaaaaaan** [comment]
> Yes, it looks like NexoPOS wasn't able to retrieve the file it has stored. What is the address to reach the system on your end please.

I'm sorry I didn't quite understand what you mean by this part:
`What is the address to reach the system on your end`

**Comment by Blair2004** [comment]
I'm currently asking if NexoPOS is installed locally, what is the address you use to reach the system ?

**Comment by Cyaaaaaaaaan** [comment]
I just click the _web_ button from laragon, using my _ip addres_s to reach the system would give me this error:
![image](https://user-images.githubusercontent.com/16180446/102247746-4d73ff00-3f3b-11eb-8716-3ee56e0bddc2.png)

**Comment by Blair2004** [comment]
> I just click the _web_ button (_localhost_) from laragon, using my _ip addres_s to reach the system would give me this error:
> ![image](https://user-images.githubusercontent.com/16180446/102247746-4d73ff00-3f3b-11eb-8716-3ee56e0bddc2.png)

That's a common issue, it happens only on localhost. Try to clear your cookies and try to authenticate again. 
I'm using Sanctum and I can't figure out what's the matter for now.

**Comment by Cyaaaaaaaaan** [comment]
> > I just click the _web_ button (_localhost_) from laragon, using my _ip addres_s to reach the system would give me this error:
> > ![image](https://user-images.githubusercontent.com/16180446/102247746-4d73ff00-3f3b-11eb-8716-3ee56e0bddc2.png)
> 
> That's a common issue, it happens only on localhost. Try to clear your cookies and try to authenticate again.
> I'm using Sanctum and I can't figure out what's the matter for now.

Clearing cookies and everything didn't work. Should I be using sanctum as well?

**Comment by Blair2004** [comment]
No sanctum is already available behind the scene. Can you provide a fullscreen image of the issue ?

**Comment by Cyaaaaaaaaan** [comment]
Of the payload error or the media?

**Comment by Cyaaaaaaaaan** [comment]
Anyway here's the payload error.
![image](https://user-images.githubusercontent.com/16180446/102252486-19034180-3f41-11eb-8e34-1a685b568699.png)

**Comment by Blair2004** [comment]
I guess i'll have to fix that one time for good. Actually, clearing the cookies and refreshing (before submitting) fixes the issue. 
I'll deploy the fix soon.

**Comment by Cyaaaaaaaaan** [comment]
Okay thanks! I'll post another issue I found.

**Comment by Cyaaaaaaaaan** [comment]
Oh I forgot, is the media problem related to the payload error?

**Comment by Blair2004** [comment]
Hi, not both aren't related.

**Comment by Blair2004** [comment]
Does this issue still persist? Are you able to find your assets on your storage folder ?

**Comment by Cyaaaaaaaaan** [comment]
> Does this issue still persist? Are you able to find your assets on your storage folder ?

Yes issue still persists. I was able to find the assets in storage together with the thumbnail but it's still shows as a broken image.

**Comment by Blair2004** [comment]
Issue fixed
