### ISSUE TITLE
Annual Report showing strange values

### ISSUE THREAD

**Issue by BienBrian** [Blair2004/NexoPOS-4x#980]
Here is the snapshop for the annual report taking the case of June & July. 

![image](https://user-images.githubusercontent.com/33430455/182903759-eb74e5ae-b497-4c4e-911d-2e7f00c31865.png)

You can see that the system indicates that the expenses were more than sales. Mind you we have not recorded any expense into the software. None. 
The effect is that the system shows the business made enormous losses in July, which is not remotely accurate.

**Comment by Blair2004** [comment]
The expenses are automatically computed based on your purchases (procurement).

**Comment by BienBrian** [comment]
When you load Income & Losses, the sales for the month of July as 5.9 Million 
![image](https://user-images.githubusercontent.com/33430455/183051393-b5fd9f17-fe6c-4428-b0d3-6851092813a3.png)

In that case, the sales figure showed under the Annual Report for July is innacurate

**Comment by BienBrian** [comment]
That being said, if the "Expense" showed there refers to the amount spent under "Procurement" or product purchases, then I think the best way is to put it under "Cost of Goods Sold". (Suggestion) The word "Expense" is rather confusing because one cannot tell if it refers to operating costs such as bills and utilities.

**Comment by Blair2004** [comment]
Every expense can be categorized. Expense here refer to what has been spent by the store. It's up to you on the accounting settings to assign that to a specific category.

https://my.nexopos.com/en/documentation/components/accounting-incomes-expenses

**Comment by BienBrian** [comment]
Okay. I'll experiment and revert

**Comment by Blair2004** [comment]
Closed for inactivity.
