### ISSUE TITLE
[Issue] Cant update from nexopos 4.7.11 to 4.8.2

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#984]
**Describe the bug**
When upgrading from version 4.7.11 to version 4.8.2 throws an error

I can update from 4.7.11 to 4.8.0 without problems, but it already fails if I update to version 4.8.1 or version 4.8.2

**Screenshots**
![Captura de Pantalla 2022-08-08 a las 01 21 12](https://user-images.githubusercontent.com/80654041/183502658-5a31200b-1206-461c-943c-e146805bb737.png)

![Captura de Pantalla 2022-08-08 a las 22 14 51](https://user-images.githubusercontent.com/80654041/183564759-401cc364-641d-42ca-afea-66841e83d875.png)

**Environment:**
 - NexoPOS 4.7.11
 - Premium Extensions: Multistore (4.7.4), Nexo Print Adapter (4.7.5), Gastro (4.7.2), Sales Commissions (4.7.0) Pin Login (4.7.2), Bulk Importer (4.6.0), Stock Transfer (4.7.3) Rack Manager (4.7.0)

**Comment by Blair2004** [comment]
Consider updating to v4.8.3 with compatible Multistore module. If the problem persist, reopen the thread.
