### ISSUE TITLE
Save Customer Screen not disappearing

### ISSUE THREAD

**Issue by magedfathi** [Blair2004/NexoPOS-4x#994]
![1](https://user-images.githubusercontent.com/87772530/185603439-31210b8a-3d7a-4383-a58c-f31b4c3334c3.png)

while adding new customer from the POS screen and pressing on save, the customer page is not disappearing

Note:
the issue is also existing on your demo version

App: Nexo POS V4.8.2

**Comment by Blair2004** [comment]
Hi, 
Thank you, we'll be reviewing this.
