### ISSUE TITLE
Table Space Missing

### ISSUE THREAD

**Issue by BienBrian** [Blair2004/NexoPOS-4x#995]
I'm getting a bug about missing table space for database.ns_nexopos_orders_addresses. #General error: 1812

How do I remove the error? 

**Environment:**
 - NexoPOS 4.x vesrion: [e.g. 4.5.2]
 - Premium Extensions: [e.g Nexo Print Adapter (4.5.0), Gastro (4.5.2)]

**Comment by BienBrian** [comment]
It's v.4.8.1

**Comment by Blair2004** [comment]
Hi, can you provide any screenshot that can help understanding the issue.

**Comment by Blair2004** [comment]
closed for inactivity.

**Comment by BienBrian** [comment]
- ![IMG-20220826-WA0003.jpg](https://user-images.githubusercontent.com/33430455/186883768-6d733f1b-4960-4244-b614-d75308cab0f7.jpg)

**Comment by Blair2004** [comment]
This should guide on how to fix that issue: https://bobcares.com/blog/mysql-tablespace-is-missing-for-table/

**Comment by BienBrian** [comment]
> This should guide on how to fix that issue: https://bobcares.com/blog/mysql-tablespace-is-missing-for-table/

Alright. Let me take a look
