### ISSUE TITLE
Bcs(): Argument #1 ($num1) is not well-formed

### ISSUE THREAD

**Issue by ahorasoyfelipe** [Blair2004/NexoPOS-4x#998]
**Describe the bug**
when I add products and want to charge or send to the kitchen, it throws this error

**To Reproduce**
1. choose products
2. Click on pay or send
3. See error

**Expected behavior**
send to kitchen or be able to pay

**Screenshots**
![Screenshot_20220822-095249_WhatsAppBusiness](https://user-images.githubusercontent.com/80654041/185937818-7a4dabd6-61c0-4be7-804d-1731fbc89893.jpg)

**Environment:**
NexoPOS 4.7.11
Premium Extensions: Multistore (4.7.4), Nexo Print Adapter (4.7.5), Gastro (4.7.2), Sales Commissions (4.7.0) Pin Login (4.7.2), Bulk Importer (4.6.0), Stock Transfer (4.7.3) Rack Manager (4.7.0)

**Comment by Blair2004** [comment]
Thank you, we'll review that.

**Comment by Blair2004** [comment]
Hi, we need extra access to your installation for checking the error in action. Let us know at contact@nexopos.com

**Comment by Blair2004** [comment]
Closed for inactivity
